/**
 * RulebookEntryForm — edit one rulebook row.
 *
 * Schema-driven: takes a (table, id) pair, fetches the row + its column
 * schema, and renders an input per field. Editable fields are those with
 * `type ∈ {"raw", "relationship"}` — derived columns (calculated /
 * aggregation / lookup) render read-only because the server recomputes
 * them on every `effortless build`.
 *
 * Persistence model: PUT writes back to `effortless-rulebook.json` directly,
 * not to the postgres base tables. The `vw_*` views you see in the rest of
 * the app are downstream of the rulebook; they refresh on the next
 * `effortless build`. Editing here is "edit the SSoT," not "edit the cache."
 *
 * YAML mirror warning: for tables whose rows are regenerated by
 * `yaml-to-rulebook` (TypeVersions/EnumVersions/Formats), the server flags
 * `has_yaml_mirror`; the UI displays an "edit the YAML instead" banner so
 * the user doesn't make a change that gets silently overwritten.
 */
import { useCallback, useEffect, useMemo, useState } from "react";
import {
  adminApi,
  type FieldSchema,
  type RulebookEntry,
  type RulebookEntryError,
} from "../lib/admin";

interface Props {
  table: string;
  id: string;
  /** Called after a successful PUT so the parent can refresh parity. */
  onAfterSave?: () => void;
}

type Loaded = {
  entry: RulebookEntry;
  /** Local working copy of the row, mutated by inputs. */
  draft: Record<string, unknown>;
};

export function RulebookEntryForm({ table, id, onAfterSave }: Props) {
  const [loaded, setLoaded] = useState<Loaded | null>(null);
  const [editing, setEditing] = useState(false);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [conflict, setConflict] = useState<{ field: "row" | "rulebook"; expected: string; actual: string } | null>(null);
  const [savedAt, setSavedAt] = useState<number | null>(null);

  // Fetch on (table, id) change.
  useEffect(() => {
    let cancelled = false;
    setLoaded(null);
    setError(null);
    setEditing(false);
    setSavedAt(null);
    setConflict(null);
    adminApi.getRulebookEntry(table, id)
      .then((entry) => {
        if (cancelled) return;
        setLoaded({ entry, draft: { ...entry.row } });
      })
      .catch((e) => {
        if (cancelled) return;
        setError(e instanceof Error ? e.message : String(e));
      });
    return () => { cancelled = true; };
  }, [table, id]);

  const dirty = useMemo(() => {
    if (!loaded) return false;
    const a = loaded.entry.row;
    const b = loaded.draft;
    const keys = new Set([...Object.keys(a), ...Object.keys(b)]);
    for (const k of keys) {
      if (a[k] !== b[k]) {
        // Loose-equality compare also catches null vs undefined cases.
        if (a[k] == null && b[k] == null) continue;
        return true;
      }
    }
    return false;
  }, [loaded]);

  const updateField = useCallback((name: string, value: unknown) => {
    setLoaded((prev) => prev ? { ...prev, draft: { ...prev.draft, [name]: value } } : prev);
  }, []);

  const cancelEdit = useCallback(() => {
    if (!loaded) return;
    setLoaded({ ...loaded, draft: { ...loaded.entry.row } });
    setEditing(false);
    setError(null);
    setConflict(null);
  }, [loaded]);

  const reloadFromDisk = useCallback(async () => {
    setError(null);
    setConflict(null);
    try {
      const entry = await adminApi.getRulebookEntry(table, id);
      setLoaded({ entry, draft: { ...entry.row } });
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    }
  }, [table, id]);

  const save = useCallback(async () => {
    if (!loaded || !dirty) return;
    setSaving(true);
    setError(null);
    setConflict(null);
    try {
      const result = await adminApi.putRulebookEntry(table, id, {
        row: loaded.draft,
        expected_row_sha256: loaded.entry.row_sha256,
      });
      setLoaded({ entry: result, draft: { ...result.row } });
      setSavedAt(Date.now());
      setEditing(false);
      onAfterSave?.();
    } catch (e) {
      const err = e as Error & { detail?: RulebookEntryError; status?: number };
      const d = err.detail;
      if (err.status === 409 && d?.error === "row_sha256_mismatch") {
        setConflict({ field: "row", expected: d.expected ?? "?", actual: d.actual ?? "?" });
      } else if (err.status === 409 && d?.error === "rulebook_sha256_mismatch") {
        setConflict({ field: "rulebook", expected: d.expected ?? "?", actual: d.actual ?? "?" });
      } else if (d?.error === "unknown_columns") {
        setError(`Unknown columns: ${(d.columns ?? []).join(", ")}`);
      } else if (d?.error === "id_mismatch") {
        setError(`Identifier fields can't be changed (URL=${d.url_id}, submitted=${d.submitted_id}).`);
      } else {
        setError(err.message);
      }
    } finally {
      setSaving(false);
    }
  }, [loaded, dirty, table, id, onAfterSave]);

  if (error && !loaded) {
    return <div className="admin-error">Error loading rulebook entry: {error}</div>;
  }
  if (!loaded) {
    return <div className="rulebook-form-loading">Loading rulebook entry…</div>;
  }

  const isRecentlySaved = savedAt !== null && Date.now() - savedAt < 4000;

  return (
    <div className="rulebook-form">
      <div className="rulebook-form-head">
        <div className="rulebook-form-title">
          <span className="rulebook-form-table">{table}</span>
          <span className="rulebook-form-sep">·</span>
          <code className="rulebook-form-id">{id}</code>
        </div>
        <div className="rulebook-form-actions">
          {!editing && (
            <button type="button" className="diff-pane-btn" onClick={() => { setEditing(true); setError(null); setSavedAt(null); }}>
              Edit
            </button>
          )}
          {editing && (
            <>
              {dirty && <span className="diff-pane-dirty" title="Unsaved changes">●</span>}
              <button
                type="button"
                className="diff-pane-btn diff-pane-btn-primary"
                disabled={!dirty || saving}
                onClick={save}
              >
                {saving ? "Saving…" : "Save"}
              </button>
              <button type="button" className="diff-pane-btn" disabled={saving} onClick={cancelEdit}>
                {dirty ? "Discard" : "Done"}
              </button>
            </>
          )}
          {isRecentlySaved && <span className="diff-pane-saved">saved ✓</span>}
        </div>
      </div>

      {loaded.entry.has_yaml_mirror && (
        <div className="rulebook-form-warn">
          ⚠ This row mirrors a YAML file under <code>definitions/</code>. Changes here will be
          overwritten on the next <strong>yaml-to-rulebook</strong> run. Edit the YAML for permanent changes.
        </div>
      )}

      {conflict && (
        <div className="admin-error">
          <strong>Conflict</strong> ({conflict.field} sha256): the {conflict.field === "row" ? "row" : "rulebook file"} changed since you started editing
          (expected <code>{conflict.expected.slice(0, 12)}…</code>, found <code>{conflict.actual.slice(0, 12)}…</code>).{" "}
          <button type="button" className="diff-pane-btn" onClick={reloadFromDisk}>
            Reload entry (discard draft)
          </button>
        </div>
      )}
      {error && <div className="admin-error">Error: {error}</div>}

      <table className="rulebook-form-table-grid">
        <tbody>
          {loaded.entry.schema.map((col) => (
            <FieldRow
              key={col.name}
              col={col}
              value={loaded.draft[col.name]}
              editing={editing}
              onChange={(v) => updateField(col.name, v)}
            />
          ))}
        </tbody>
      </table>
    </div>
  );
}

function FieldRow({
  col,
  value,
  editing,
  onChange,
}: {
  col: FieldSchema;
  value: unknown;
  editing: boolean;
  onChange: (v: unknown) => void;
}) {
  const isEditable = editing && (col.type === "raw" || col.type === "relationship");

  return (
    <tr className={`rulebook-form-row rulebook-form-row-${col.type}`}>
      <th>
        <div className="rulebook-form-field-name">{col.name}</div>
        <div className="rulebook-form-field-meta">
          <span className={`rulebook-form-type-pill rulebook-form-type-${col.type}`}>{col.type}</span>
          <span className="rulebook-form-datatype">{col.datatype}</span>
          {col.nullable ? <span className="rulebook-form-nullable">null-ok</span> : <span className="rulebook-form-required">required</span>}
          {col.related_to && <span className="rulebook-form-fk">→ {col.related_to}</span>}
        </div>
        {col.description && <div className="rulebook-form-desc">{col.description}</div>}
        {col.formula && (
          <div className="rulebook-form-formula"><code>{col.formula}</code></div>
        )}
      </th>
      <td>
        <FieldInput col={col} value={value} editable={isEditable} onChange={onChange} />
      </td>
    </tr>
  );
}

function FieldInput({
  col,
  value,
  editable,
  onChange,
}: {
  col: FieldSchema;
  value: unknown;
  editable: boolean;
  onChange: (v: unknown) => void;
}) {
  // Derived (non-raw, non-relationship) fields render read-only regardless of edit mode.
  if (!editable) {
    return <ReadOnlyValue col={col} value={value} />;
  }

  // Boolean → checkbox + null clear
  if (col.datatype === "boolean") {
    const checked = value === true;
    const isNull = value == null;
    return (
      <span className="rulebook-form-bool">
        <label>
          <input
            type="checkbox"
            checked={checked}
            onChange={(e) => onChange(e.target.checked)}
          />
          <span>{checked ? "true" : isNull ? "(null)" : "false"}</span>
        </label>
        {col.nullable && !isNull && (
          <button type="button" className="rulebook-form-null-btn" onClick={() => onChange(null)}>
            set null
          </button>
        )}
      </span>
    );
  }

  // Integer → number input
  if (col.datatype === "integer") {
    const display = value == null ? "" : String(value);
    return (
      <input
        type="number"
        className="rulebook-form-input"
        value={display}
        onChange={(e) => {
          const v = e.target.value;
          if (v === "") {
            onChange(col.nullable ? null : 0);
          } else {
            const n = Number.parseInt(v, 10);
            onChange(Number.isNaN(n) ? v : n);
          }
        }}
      />
    );
  }

  // datetime → text input (full ISO 8601 string). A real date picker can come later.
  // string and everything else → multi-line textarea for long descriptions, single-line for short ones
  const display = value == null ? "" : String(value);
  const useTextarea = display.length > 80 || display.includes("\n") || col.name === "Description" || col.name === "Statement";
  if (useTextarea) {
    return (
      <textarea
        className="rulebook-form-textarea"
        value={display}
        rows={Math.min(8, Math.max(2, display.split("\n").length))}
        onChange={(e) => onChange(e.target.value === "" && col.nullable ? null : e.target.value)}
      />
    );
  }
  return (
    <input
      type="text"
      className="rulebook-form-input"
      value={display}
      onChange={(e) => onChange(e.target.value === "" && col.nullable ? null : e.target.value)}
    />
  );
}

function ReadOnlyValue({ col, value }: { col: FieldSchema; value: unknown }) {
  if (value == null) return <span className="rulebook-form-readonly rulebook-form-null">(null)</span>;
  if (typeof value === "boolean") {
    return (
      <span className={`rulebook-form-readonly rulebook-form-bool-${value}`}>
        {value ? "true" : "false"}
      </span>
    );
  }
  if (typeof value === "object") {
    return <pre className="rulebook-form-readonly-json">{JSON.stringify(value, null, 2)}</pre>;
  }
  const text = String(value);
  if (text.length > 120 || text.includes("\n")) {
    return <pre className="rulebook-form-readonly-long">{text}</pre>;
  }
  return (
    <span className={`rulebook-form-readonly rulebook-form-datatype-${col.datatype}`}>
      {text}
    </span>
  );
}
