/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/owners": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Owners */
        get: operations["list_owners_api_owners_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/owners/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Owner */
        get: operations["get_owner_api_owners__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Types */
        get: operations["list_types_api_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/types/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Type */
        get: operations["get_type_api_types__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/types/{name}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Type Versions */
        get: operations["list_type_versions_api_types__name__versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/type-versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List All Type Versions */
        get: operations["list_all_type_versions_api_type_versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/type-versions/{type_name}/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Type Version */
        get: operations["get_type_version_api_type_versions__type_name___version__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/type-versions/{type_name}/{version}/attributes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Type Version Attributes */
        get: operations["list_type_version_attributes_api_type_versions__type_name___version__attributes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/type-versions/{type_name}/{version}/axioms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Type Version Axioms */
        get: operations["list_type_version_axioms_api_type_versions__type_name___version__axioms_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/type-versions/{type_name}/{version}/examples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Type Version Examples */
        get: operations["list_type_version_examples_api_type_versions__type_name___version__examples_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/enums": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Enums */
        get: operations["list_enums_api_enums_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/enums/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Enum */
        get: operations["get_enum_api_enums__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/enums/{name}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Enum Versions */
        get: operations["list_enum_versions_api_enums__name__versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/enum-versions/{enum_name}/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Enum Version */
        get: operations["get_enum_version_api_enum_versions__enum_name___version__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/enum-versions/{enum_name}/{version}/values": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Enum Values */
        get: operations["list_enum_values_api_enum_versions__enum_name___version__values_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/formats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Formats */
        get: operations["list_formats_api_formats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/formats/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Format */
        get: operations["get_format_api_formats__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/formats/{name}/examples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Format Examples */
        get: operations["list_format_examples_api_formats__name__examples_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/helpers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Helpers */
        get: operations["list_helpers_api_helpers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/helpers/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Helper */
        get: operations["get_helper_api_helpers__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/helpers/{name}/attributes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Helper Attributes */
        get: operations["list_helper_attributes_api_helpers__name__attributes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projections */
        get: operations["list_projections_api_projections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projections/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Projection */
        get: operations["get_projection_api_projections__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projections/{name}/mappings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projection Mappings */
        get: operations["list_projection_mappings_api_projections__name__mappings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/type-upgrades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Type Upgrades */
        get: operations["list_type_upgrades_api_type_upgrades_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/type-upgrades/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Type Upgrade */
        get: operations["get_type_upgrade_api_type_upgrades__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/type-upgrades/{name}/ops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Type Upgrade Ops */
        get: operations["list_type_upgrade_ops_api_type_upgrades__name__ops_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/enum-upgrades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Enum Upgrades */
        get: operations["list_enum_upgrades_api_enum_upgrades_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/enum-upgrades/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Enum Upgrade */
        get: operations["get_enum_upgrade_api_enum_upgrades__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/enum-upgrades/{name}/mappings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Enum Upgrade Mappings */
        get: operations["list_enum_upgrade_mappings_api_enum_upgrades__name__mappings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Enum */
        Enum: {
            /** Enums Id */
            enums_id: string;
            /** Name */
            name: string;
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Owner */
            owner?: string | null;
            /** Owner Name */
            owner_name?: string | null;
            /** Replaced By */
            replaced_by?: string | null;
            /** Is Retired */
            is_retired?: boolean | null;
            /** Version Count */
            version_count?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** EnumUpgrade */
        EnumUpgrade: {
            /** Enum Upgrades Id */
            enum_upgrades_id: string;
            /** Name */
            name: string;
            /** From Enum Version */
            from_enum_version?: string | null;
            /** To Enum Version */
            to_enum_version?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** EnumUpgradeMapping */
        EnumUpgradeMapping: {
            /** Enum Upgrade Mappings Id */
            enum_upgrade_mappings_id: string;
            /** Name */
            name: string;
            /** Enum Upgrade */
            enum_upgrade?: string | null;
            /** From Value */
            from_value?: string | null;
            /** To Value */
            to_value?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** EnumValue */
        EnumValue: {
            /** Enum Values Id */
            enum_values_id: string;
            /** Name */
            name: string;
            /** Enum Version */
            enum_version?: string | null;
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Idx */
            idx?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** EnumVersion */
        EnumVersion: {
            /** Enum Versions Id */
            enum_versions_id: string;
            /** Name */
            name: string;
            /** Enum */
            enum: string;
            /** Version */
            version: string;
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Status */
            status?: string | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Is Deprecated */
            is_deprecated?: boolean | null;
            /** Is Draft */
            is_draft?: boolean | null;
            /** Value Count */
            value_count?: number | null;
            /** Total Attribute Usage Count */
            total_attribute_usage_count?: number | null;
            /** Owner Name */
            owner_name?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** Format */
        Format: {
            /** Formats Id */
            formats_id: string;
            /** Name */
            name: string;
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Owner */
            owner?: string | null;
            /** Owner Name */
            owner_name?: string | null;
            /** Pattern */
            pattern?: string | null;
            /** Json Schema Format */
            json_schema_format?: string | null;
            /** Min Length */
            min_length?: number | null;
            /** Max Length */
            max_length?: number | null;
            /** Replaced By */
            replaced_by?: string | null;
            /** Is Retired */
            is_retired?: boolean | null;
            /** Total Usage Count */
            total_usage_count?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** FormatExample */
        FormatExample: {
            /** Format Examples Id */
            format_examples_id: string;
            /** Name */
            name: string;
            /** Format */
            format?: string | null;
            /** Value */
            value?: string | null;
            /** Is Counter */
            is_counter?: boolean | null;
            /** Example Kind */
            example_kind?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Ok */
            ok: boolean;
            /** Db */
            db: boolean;
            /** Rulebook */
            rulebook: boolean;
            /** Tables */
            tables: components["schemas"]["TableSummary"][];
        };
        /** Owner */
        Owner: {
            /** Owners Id */
            owners_id: string;
            /** Name */
            name: string;
            /** Owner Type */
            owner_type?: string | null;
            /** Contact */
            contact?: string | null;
            /** Website */
            website?: string | null;
            /** Github */
            github?: string | null;
            /** Organization */
            organization?: string | null;
            /** Description */
            description?: string | null;
            /** Support Policy */
            support_policy?: string | null;
            /** License */
            license?: string | null;
            /** Is Organization */
            is_organization?: boolean | null;
            /** Has Github */
            has_github?: boolean | null;
            /** Format Count */
            format_count?: number | null;
            /** Enum Count */
            enum_count?: number | null;
            /** Type Count */
            type_count?: number | null;
            /** Draft Type Version Count */
            draft_type_version_count?: number | null;
            /** Active Type Version Count */
            active_type_version_count?: number | null;
            /** Deprecated Type Version Count */
            deprecated_type_version_count?: number | null;
            /** Draft Enum Version Count */
            draft_enum_version_count?: number | null;
            /** Active Enum Version Count */
            active_enum_version_count?: number | null;
            /** Deprecated Enum Version Count */
            deprecated_enum_version_count?: number | null;
            /** Retired Type Count */
            retired_type_count?: number | null;
            /** Retired Enum Count */
            retired_enum_count?: number | null;
            /** Retired Format Count */
            retired_format_count?: number | null;
            /** Has Open Drafts */
            has_open_drafts?: boolean | null;
            /** Has Published Artifacts */
            has_published_artifacts?: boolean | null;
            /** Latest Type Version At */
            latest_type_version_at?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** Projection */
        Projection: {
            /** Projections Id */
            projections_id: string;
            /** Name */
            name: string;
            /** From Enum Version */
            from_enum_version?: string | null;
            /** To Enum Version */
            to_enum_version?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** ProjectionMapping */
        ProjectionMapping: {
            /** Projection Mappings Id */
            projection_mappings_id: string;
            /** Name */
            name: string;
            /** Projection */
            projection?: string | null;
            /** From Value */
            from_value?: string | null;
            /** To Value */
            to_value?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** SearchHit */
        SearchHit: {
            /** Table */
            table: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Snippet */
            snippet?: string | null;
        };
        /** TableSummary */
        TableSummary: {
            /** Table */
            table: string;
            /** Row Count */
            row_count: number;
        };
        /** Type */
        Type: {
            /** Types Id */
            types_id: string;
            /** Name */
            name: string;
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Owner */
            owner?: string | null;
            /** Owner Name */
            owner_name?: string | null;
            /** Replaced By */
            replaced_by?: string | null;
            /** Is Retired */
            is_retired?: boolean | null;
            /** Version Count */
            version_count?: number | null;
            /** Active Version Count */
            active_version_count?: number | null;
            /** Draft Version Count */
            draft_version_count?: number | null;
            /** Deprecated Version Count */
            deprecated_version_count?: number | null;
            /** Has Drafts */
            has_drafts?: boolean | null;
            /** Latest Version */
            latest_version?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** TypeAttribute */
        TypeAttribute: {
            /** Type Attributes Id */
            type_attributes_id: string;
            /** Name */
            name: string;
            /** Type Version */
            type_version?: string | null;
            /** Attribute Name */
            attribute_name?: string | null;
            /** Idx */
            idx?: number | null;
            /** Description */
            description?: string | null;
            /** Default */
            default?: string | null;
            /** Is Required */
            is_required?: boolean | null;
            /** Is Optional */
            is_optional?: boolean | null;
            /** Has Default */
            has_default?: boolean | null;
            /** Is List */
            is_list?: boolean | null;
            /** Primitive Type */
            primitive_type?: string | null;
            /** Format Ref */
            format_ref?: string | null;
            /** Enum Version Ref */
            enum_version_ref?: string | null;
            /** Sub Type Version Ref */
            sub_type_version_ref?: string | null;
            /** Helper Ref */
            helper_ref?: string | null;
            /** Ref Kind */
            ref_kind?: string | null;
            /** Ref Format Is Retired */
            ref_format_is_retired?: boolean | null;
            /** Ref Enum Is Active */
            ref_enum_is_active?: boolean | null;
            /** Ref Enum Is Draft */
            ref_enum_is_draft?: boolean | null;
            /** Ref Enum Word Is Retired */
            ref_enum_word_is_retired?: boolean | null;
            /** Ref Subtype Is Active */
            ref_subtype_is_active?: boolean | null;
            /** Ref Subtype Is Draft */
            ref_subtype_is_draft?: boolean | null;
            /** Ref Subtype Word Is Retired */
            ref_subtype_word_is_retired?: boolean | null;
            /** Ref Is Stale */
            ref_is_stale?: boolean | null;
        } & {
            [key: string]: unknown;
        };
        /** TypeAxiom */
        TypeAxiom: {
            /** Type Axioms Id */
            type_axioms_id: string;
            /** Name */
            name: string;
            /** Type Version */
            type_version?: string | null;
            /** Statement */
            statement?: string | null;
            /** Idx */
            idx?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** TypeExample */
        TypeExample: {
            /** Type Examples Id */
            type_examples_id: string;
            /** Name */
            name: string;
            /** Type Version */
            type_version?: string | null;
            /** Example Json */
            example_json?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** TypeHelper */
        TypeHelper: {
            /** Type Helpers Id */
            type_helpers_id: string;
            /** Name */
            name: string;
            /** Origin Type Version */
            origin_type_version?: string | null;
            /** Origin Path */
            origin_path?: string | null;
            /** Extra Allowed */
            extra_allowed?: boolean | null;
            /** Is Closed */
            is_closed?: boolean | null;
            /** Total Usage Count */
            total_usage_count?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** TypeHelperAttribute */
        TypeHelperAttribute: {
            /** Type Helper Attributes Id */
            type_helper_attributes_id: string;
            /** Name */
            name: string;
            /** Type Helper */
            type_helper?: string | null;
            /** Attribute Name */
            attribute_name?: string | null;
            /** Idx */
            idx?: number | null;
            /** Description */
            description?: string | null;
            /** Is Required */
            is_required?: boolean | null;
            /** Is List */
            is_list?: boolean | null;
            /** Primitive Type */
            primitive_type?: string | null;
            /** Format Ref */
            format_ref?: string | null;
            /** Enum Version Ref */
            enum_version_ref?: string | null;
            /** Sub Type Version Ref */
            sub_type_version_ref?: string | null;
            /** Helper Ref */
            helper_ref?: string | null;
            /** Ref Kind */
            ref_kind?: string | null;
            /** Ref Format Is Retired */
            ref_format_is_retired?: boolean | null;
            /** Ref Enum Is Draft */
            ref_enum_is_draft?: boolean | null;
            /** Ref Enum Word Is Retired */
            ref_enum_word_is_retired?: boolean | null;
            /** Ref Subtype Is Draft */
            ref_subtype_is_draft?: boolean | null;
            /** Ref Subtype Word Is Retired */
            ref_subtype_word_is_retired?: boolean | null;
            /** Ref Is Stale */
            ref_is_stale?: boolean | null;
        } & {
            [key: string]: unknown;
        };
        /** TypeUpgrade */
        TypeUpgrade: {
            /** Type Upgrades Id */
            type_upgrades_id: string;
            /** Name */
            name: string;
            /** From Type Version */
            from_type_version?: string | null;
            /** To Type Version */
            to_type_version?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** TypeUpgradeOp */
        TypeUpgradeOp: {
            /** Type Upgrade Ops Id */
            type_upgrade_ops_id: string;
            /** Name */
            name: string;
            /** Type Upgrade */
            type_upgrade?: string | null;
            /** Op Kind */
            op_kind?: string | null;
            /** Idx */
            idx?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** TypeVersion */
        TypeVersion: {
            /** Type Versions Id */
            type_versions_id: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Version */
            version: string;
            /** Schema Url */
            schema_url?: string | null;
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Extra Allowed */
            extra_allowed?: boolean | null;
            /** Status */
            status?: string | null;
            /** Created */
            created?: string | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Is Deprecated */
            is_deprecated?: boolean | null;
            /** Is Draft */
            is_draft?: boolean | null;
            /** Is Closed */
            is_closed?: boolean | null;
            /** Attribute Count */
            attribute_count?: number | null;
            /** Required Attribute Count */
            required_attribute_count?: number | null;
            /** Axiom Count */
            axiom_count?: number | null;
            /** Example Count */
            example_count?: number | null;
            /** Outgoing Upgrade Count */
            outgoing_upgrade_count?: number | null;
            /** Incoming Upgrade Count */
            incoming_upgrade_count?: number | null;
            /** Originated Helper Count */
            originated_helper_count?: number | null;
            /** Total Subtype Usage Count */
            total_subtype_usage_count?: number | null;
            /** Is Used As Subtype */
            is_used_as_subtype?: boolean | null;
            /** Has Incoming Upgrade */
            has_incoming_upgrade?: boolean | null;
            /** Has Outgoing Upgrade */
            has_outgoing_upgrade?: boolean | null;
            /** Is Root */
            is_root?: boolean | null;
            /** Is Leaf */
            is_leaf?: boolean | null;
            /** Originates Helpers */
            originates_helpers?: boolean | null;
            /** Owner Name */
            owner_name?: string | null;
            /** Word Title */
            word_title?: string | null;
            /** Word Is Retired */
            word_is_retired?: boolean | null;
            /** Last Modified */
            last_modified?: string | null;
            /** Promoted At */
            promoted_at?: string | null;
            /** Deprecated At */
            deprecated_at?: string | null;
            /** Stale Reference Count */
            stale_reference_count?: number | null;
            /** Has Stale References */
            has_stale_references?: boolean | null;
            /** Is Promotable */
            is_promotable?: boolean | null;
        } & {
            [key: string]: unknown;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_owners_api_owners_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Owner"][];
                };
            };
        };
    };
    get_owner_api_owners__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Owner"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_types_api_types_get: {
        parameters: {
            query?: {
                owner?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Type"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_type_api_types__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Type"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_type_versions_api_types__name__versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypeVersion"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_all_type_versions_api_type_versions_get: {
        parameters: {
            query?: {
                status?: string | null;
                owner?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypeVersion"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_type_version_api_type_versions__type_name___version__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type_name: string;
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypeVersion"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_type_version_attributes_api_type_versions__type_name___version__attributes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type_name: string;
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypeAttribute"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_type_version_axioms_api_type_versions__type_name___version__axioms_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type_name: string;
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypeAxiom"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_type_version_examples_api_type_versions__type_name___version__examples_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type_name: string;
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypeExample"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_enums_api_enums_get: {
        parameters: {
            query?: {
                owner?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Enum"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_enum_api_enums__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Enum"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_enum_versions_api_enums__name__versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnumVersion"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_enum_version_api_enum_versions__enum_name___version__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                enum_name: string;
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnumVersion"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_enum_values_api_enum_versions__enum_name___version__values_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                enum_name: string;
                version: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnumValue"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_formats_api_formats_get: {
        parameters: {
            query?: {
                owner?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Format"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_format_api_formats__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Format"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_format_examples_api_formats__name__examples_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormatExample"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_helpers_api_helpers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypeHelper"][];
                };
            };
        };
    };
    get_helper_api_helpers__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypeHelper"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_helper_attributes_api_helpers__name__attributes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypeHelperAttribute"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projections_api_projections_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Projection"][];
                };
            };
        };
    };
    get_projection_api_projections__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Projection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projection_mappings_api_projections__name__mappings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectionMapping"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_type_upgrades_api_type_upgrades_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypeUpgrade"][];
                };
            };
        };
    };
    get_type_upgrade_api_type_upgrades__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypeUpgrade"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_type_upgrade_ops_api_type_upgrades__name__ops_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypeUpgradeOp"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_enum_upgrades_api_enum_upgrades_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnumUpgrade"][];
                };
            };
        };
    };
    get_enum_upgrade_api_enum_upgrades__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnumUpgrade"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_enum_upgrade_mappings_api_enum_upgrades__name__mappings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnumUpgradeMapping"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_search_get: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchHit"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
