-- ============================================================================
-- 0001_initial_baseline.sql
-- ============================================================================
-- This migration carries no DDL. It exists so that the day-of-bootstrap
-- INSERT into public.schema_migrations happens through the same channel
-- every subsequent migration uses, keeping the audit trail consistent.
--
-- On the day prod is bootstrapped:
--   1. ./postgres/init-db.sh "$BASE_ADMIN_URL"   ← creates the schema
--      (NB: 01b-customize-schema.sql's CREATE SCHEMA / CREATE TABLE will
--       no-op in prod because bases owns auth.trusted_tenants — that's
--       fine, the IF NOT EXISTS guards make it harmless.)
--   2. POST /bases/{id}/auth/toggle-magic-links {enabled:true}
--      ← bases superuser installs auth.set_jwt(), auth.email(), etc.
--   3. POST /bases/{id}/auth/trusted-tenants  {tenant_id, public_key_pem}
--      ← register the magic-links tenant (table owned by bases superuser,
--        so we go through the API, not direct INSERT).
--   4. POST /bases/{id}/auth/apply-privileges-template
--      ← anon + admin role grants on sema's tables and views.
--   5. ./postgres/migrations/migrate-prod.sh "$BASE_ADMIN_URL"
--      ← applies this file, recording version 0001 in schema_migrations,
--        which is what tells future runs "the baseline is in place."
--
-- After this, every rulebook change ships as 0002, 0003, … in this dir.
-- ============================================================================

-- No-op. The migrate-prod.sh runner records the version for us.
SELECT 1 AS baseline_recorded;
