-- ============================================================================
-- 00-BOOTSTRAP - Run first by init-db.sh (overwrite Never)
-- ============================================================================
-- Use this file for one-time setup or to add your own bootstrap SQL.
-- Below: commented-out script to remove all views, functions, and tables
-- in this schema. Uncomment the block to run a full clean slate.
-- ============================================================================

-- -- ============================================================================
-- -- DROP ALL OBJECTS - Clean slate for database
-- -- ============================================================================
-- -- Generated by rulebook-to-postgres tool
-- -- ============================================================================

-- DO $$
-- DECLARE r RECORD; v_count INTEGER := 0;
-- BEGIN
--     RAISE NOTICE 'Dropping views...';
--     FOR r IN (SELECT table_name FROM information_schema.views WHERE table_schema = 'public') LOOP
--         EXECUTE 'DROP VIEW IF EXISTS ' || quote_ident(r.table_name) || ' CASCADE';
--         v_count := v_count + 1;
--     END LOOP;
--     RAISE NOTICE 'Dropped % views', v_count; v_count := 0;

--     RAISE NOTICE 'Dropping functions...';
--     FOR r IN (SELECT DISTINCT p.proname as function_name, pg_get_function_identity_arguments(p.oid) as function_args
--               FROM pg_proc p JOIN pg_namespace n ON p.pronamespace = n.oid
--               WHERE n.nspname = 'public' AND p.prokind = 'f') LOOP
--         EXECUTE 'DROP FUNCTION IF EXISTS ' || quote_ident(r.function_name) || '(' || r.function_args || ') CASCADE';
--         v_count := v_count + 1;
--     END LOOP;
--     RAISE NOTICE 'Dropped % functions', v_count; v_count := 0;

--     RAISE NOTICE 'Dropping tables...';
--     FOR r IN (SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_type = 'BASE TABLE') LOOP
--         EXECUTE 'DROP TABLE IF EXISTS ' || quote_ident(r.table_name) || ' CASCADE';
--         v_count := v_count + 1;
--     END LOOP;
--     RAISE NOTICE 'Dropped % tables', v_count;
-- END $$;


