-- ============================================================================
-- CREATE TABLES (check-add mode) - Idempotent schema, never drops columns
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: check-add    Stage: dev
-- Total Tables: 29
-- Total Raw Fields: 184
-- ============================================================================

SET timezone = 'UTC';

-- ============================================================================
-- CREATE TABLES - Normalized data only (no calculated fields)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Owners: Entities (organizations or individuals) that own Types, Enums, and Formats. Sourced from definitions/owners.yaml.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS owners (
  owners_id                           TEXT                 PRIMARY KEY          -- Primary key (auto-synthesized: Owners had no field named 'Id' or ending in 'Id').
);
ALTER TABLE owners ADD COLUMN IF NOT EXISTS name TEXT;                                              -- Owner identifier slug. Example: 'gridworks-energy'. Acts as the primary key.
ALTER TABLE owners ADD COLUMN IF NOT EXISTS owner_type TEXT;                                        -- Either 'organization' or 'individual'.
ALTER TABLE owners ADD COLUMN IF NOT EXISTS contact TEXT;                                           -- Primary contact email.
ALTER TABLE owners ADD COLUMN IF NOT EXISTS website TEXT;                                           -- Owner's website URL.
ALTER TABLE owners ADD COLUMN IF NOT EXISTS github TEXT;                                            -- Owner's GitHub URL (optional).
ALTER TABLE owners ADD COLUMN IF NOT EXISTS organization TEXT;                                      -- Full legal/organization name.
ALTER TABLE owners ADD COLUMN IF NOT EXISTS description TEXT;                                       -- Free-text description of the owner's domain or focus.
ALTER TABLE owners ADD COLUMN IF NOT EXISTS support_policy TEXT;                                    -- How users get support from this owner.
ALTER TABLE owners ADD COLUMN IF NOT EXISTS license TEXT;                                           -- License under which the owner's contributions are published (e.g. 'MIT').
COMMENT ON TABLE owners IS 'Entities (organizations or individuals) that own Types, Enums, and Formats. Sourced from definitions/owners.yaml.';
COMMENT ON COLUMN owners.owners_id IS 'Primary key (auto-synthesized: Owners had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN owners.name IS 'Owner identifier slug. Example: ''gridworks-energy''. Acts as the primary key.';
COMMENT ON COLUMN owners.owner_type IS 'Either ''organization'' or ''individual''.';
COMMENT ON COLUMN owners.contact IS 'Primary contact email.';
COMMENT ON COLUMN owners.website IS 'Owner''s website URL.';
COMMENT ON COLUMN owners.github IS 'Owner''s GitHub URL (optional).';
COMMENT ON COLUMN owners.organization IS 'Full legal/organization name.';
COMMENT ON COLUMN owners.description IS 'Free-text description of the owner''s domain or focus.';
COMMENT ON COLUMN owners.support_policy IS 'How users get support from this owner.';
COMMENT ON COLUMN owners.license IS 'License under which the owner''s contributions are published (e.g. ''MIT'').';

-- ----------------------------------------------------------------------------
-- Formats: JSON-Schema string formats with regex patterns and length bounds. Sourced from definitions/formats/*.yaml. Formats are not versioned.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS formats (
  formats_id                          TEXT                 PRIMARY KEY          -- Primary key (auto-synthesized: Formats had no field named 'Id' or ending in 'Id').
);
ALTER TABLE formats ADD COLUMN IF NOT EXISTS name TEXT;                                             -- Format identifier slug. Example: 'uuid4.str'. Acts as the primary key.
ALTER TABLE formats ADD COLUMN IF NOT EXISTS owner TEXT;                                            -- Owner of this format.
ALTER TABLE formats ADD COLUMN IF NOT EXISTS schema_url TEXT;                                       -- Schema URL from JSON-Schema $id.
ALTER TABLE formats ADD COLUMN IF NOT EXISTS title TEXT;                                            -- Human-readable title.
ALTER TABLE formats ADD COLUMN IF NOT EXISTS description TEXT;                                      -- Free-text description of the format.
ALTER TABLE formats ADD COLUMN IF NOT EXISTS replaced_by TEXT;                                      -- Advisory pointer to another Format that supersedes this one. The original Format remains valid and queryable — ReplacedBy is just a hint to consumers about a preferred successor. NOT a state change; published versions are immutable.
ALTER TABLE formats ADD COLUMN IF NOT EXISTS pattern TEXT;                                          -- Regex pattern that valid values must match.
ALTER TABLE formats ADD COLUMN IF NOT EXISTS min_length INTEGER;                                    -- Minimum string length, if constrained.
ALTER TABLE formats ADD COLUMN IF NOT EXISTS max_length INTEGER;                                    -- Maximum string length, if constrained.
ALTER TABLE formats ADD COLUMN IF NOT EXISTS json_schema_format TEXT;                               -- JSON-Schema 'format' keyword if present (e.g. 'date-time', 'email').
ALTER TABLE formats ADD COLUMN IF NOT EXISTS created TIMESTAMPTZ;                                   -- Created timestamp from registry.yaml.
ALTER TABLE formats ADD COLUMN IF NOT EXISTS raw_json TEXT;                                         -- Escape hatch: any unmodeled JSON-Schema fields, serialized as JSON string.
COMMENT ON TABLE formats IS 'JSON-Schema string formats with regex patterns and length bounds. Sourced from definitions/formats/*.yaml. Formats are not versioned.';
COMMENT ON COLUMN formats.formats_id IS 'Primary key (auto-synthesized: Formats had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN formats.name IS 'Format identifier slug. Example: ''uuid4.str''. Acts as the primary key.';
COMMENT ON COLUMN formats.owner IS 'Owner of this format.';
COMMENT ON COLUMN formats.schema_url IS 'Schema URL from JSON-Schema $id.';
COMMENT ON COLUMN formats.title IS 'Human-readable title.';
COMMENT ON COLUMN formats.description IS 'Free-text description of the format.';
COMMENT ON COLUMN formats.replaced_by IS 'Advisory pointer to another Format that supersedes this one. The original Format remains valid and queryable — ReplacedBy is just a hint to consumers about a preferred successor. NOT a state change; published versions are immutable.';
COMMENT ON COLUMN formats.pattern IS 'Regex pattern that valid values must match.';
COMMENT ON COLUMN formats.min_length IS 'Minimum string length, if constrained.';
COMMENT ON COLUMN formats.max_length IS 'Maximum string length, if constrained.';
COMMENT ON COLUMN formats.json_schema_format IS 'JSON-Schema ''format'' keyword if present (e.g. ''date-time'', ''email'').';
COMMENT ON COLUMN formats.created IS 'Created timestamp from registry.yaml.';
COMMENT ON COLUMN formats.raw_json IS 'Escape hatch: any unmodeled JSON-Schema fields, serialized as JSON string.';

-- ----------------------------------------------------------------------------
-- FormatExamples: Per-format examples and counterexamples (with order preserved). Sourced from format YAML 'examples' and 'counterexamples' arrays.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS format_examples (
  format_examples_id                  TEXT                 PRIMARY KEY          -- Primary key (auto-synthesized: FormatExamples had no field named 'Id' or ending in 'Id').
);
ALTER TABLE format_examples ADD COLUMN IF NOT EXISTS format TEXT;                                   -- Foreign key to the parent Format.
ALTER TABLE format_examples ADD COLUMN IF NOT EXISTS idx INTEGER;                                   -- Preserves YAML ordering (0-indexed within examples or counterexamples).
ALTER TABLE format_examples ADD COLUMN IF NOT EXISTS is_counter BOOLEAN;                            -- True if this is a counterexample (must NOT match), false if a positive example.
ALTER TABLE format_examples ADD COLUMN IF NOT EXISTS value TEXT;                                    -- The example string itself.
ALTER TABLE format_examples ADD COLUMN IF NOT EXISTS description TEXT;                              -- Optional description (e.g. YAML inline comment).
COMMENT ON TABLE format_examples IS 'Per-format examples and counterexamples (with order preserved). Sourced from format YAML ''examples'' and ''counterexamples'' arrays.';
COMMENT ON COLUMN format_examples.format_examples_id IS 'Primary key (auto-synthesized: FormatExamples had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN format_examples.format IS 'Foreign key to the parent Format.';
COMMENT ON COLUMN format_examples.idx IS 'Preserves YAML ordering (0-indexed within examples or counterexamples).';
COMMENT ON COLUMN format_examples.is_counter IS 'True if this is a counterexample (must NOT match), false if a positive example.';
COMMENT ON COLUMN format_examples.value IS 'The example string itself.';
COMMENT ON COLUMN format_examples.description IS 'Optional description (e.g. YAML inline comment).';

-- ----------------------------------------------------------------------------
-- Enums: Top-level enum definitions (name-level). Versioned enums have multiple EnumVersions; literal enums have one. Sourced from definitions/registry.yaml + definitions/enums/.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS enums (
  enums_id                            TEXT                 PRIMARY KEY          -- Primary key (auto-synthesized: Enums had no field named 'Id' or ending in 'Id').
);
ALTER TABLE enums ADD COLUMN IF NOT EXISTS name TEXT;                                               -- Enum identifier slug. Example: 'gw1.actor.class'. Acts as the primary key.
ALTER TABLE enums ADD COLUMN IF NOT EXISTS owner TEXT;                                              -- Owner of this enum.
ALTER TABLE enums ADD COLUMN IF NOT EXISTS enum_type TEXT;                                          -- Either 'versioned' (additive-only multi-version) or 'literal' (single immutable version).
ALTER TABLE enums ADD COLUMN IF NOT EXISTS value_type TEXT;                                         -- JSON Schema datatype of the enum's symbols. If present, SHALL be 'integer' and version YAML files SHALL have type: integer. If null, the enum SHALL be treated as string-valued.
ALTER TABLE enums ADD COLUMN IF NOT EXISTS description TEXT;                                        -- Name-level description (registry-level).
ALTER TABLE enums ADD COLUMN IF NOT EXISTS replaced_by TEXT;                                        -- Advisory pointer to another Enum that supersedes this one. The original Enum remains valid and queryable — ReplacedBy is just a hint to consumers about a preferred successor. NOT a state change; published versions are immutable.
ALTER TABLE enums ADD COLUMN IF NOT EXISTS raw_json TEXT;                                           -- Escape hatch: any unmodeled YAML keys (e.g., x-gridworks extended_description). JSON-encoded.
COMMENT ON TABLE enums IS 'Top-level enum definitions (name-level). Versioned enums have multiple EnumVersions; literal enums have one. Sourced from definitions/registry.yaml + definitions/enums/.';
COMMENT ON COLUMN enums.enums_id IS 'Primary key (auto-synthesized: Enums had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN enums.name IS 'Enum identifier slug. Example: ''gw1.actor.class''. Acts as the primary key.';
COMMENT ON COLUMN enums.owner IS 'Owner of this enum.';
COMMENT ON COLUMN enums.enum_type IS 'Either ''versioned'' (additive-only multi-version) or ''literal'' (single immutable version).';
COMMENT ON COLUMN enums.value_type IS 'JSON Schema datatype of the enum''s symbols. If present, SHALL be ''integer'' and version YAML files SHALL have type: integer. If null, the enum SHALL be treated as string-valued.';
COMMENT ON COLUMN enums.description IS 'Name-level description (registry-level).';
COMMENT ON COLUMN enums.replaced_by IS 'Advisory pointer to another Enum that supersedes this one. The original Enum remains valid and queryable — ReplacedBy is just a hint to consumers about a preferred successor. NOT a state change; published versions are immutable.';
COMMENT ON COLUMN enums.raw_json IS 'Escape hatch: any unmodeled YAML keys (e.g., x-gridworks extended_description). JSON-encoded.';

-- ----------------------------------------------------------------------------
-- EnumVersions: Specific versions of an enum. Each enum can have multiple versions (e.g. gw1.actor.class has versions 009, 010, 011).
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS enum_versions (
  enum_versions_id                    TEXT                 PRIMARY KEY          -- Primary key (auto-synthesized: EnumVersions had no field named 'Id' or ending in 'Id').
);
ALTER TABLE enum_versions ADD COLUMN IF NOT EXISTS enum TEXT;                                       -- Foreign key to the parent Enum.
ALTER TABLE enum_versions ADD COLUMN IF NOT EXISTS version TEXT;                                    -- Three-digit version string. Example: '007'.
ALTER TABLE enum_versions ADD COLUMN IF NOT EXISTS schema_url TEXT;                                 -- Schema URL from JSON-Schema $id.
ALTER TABLE enum_versions ADD COLUMN IF NOT EXISTS title TEXT;                                      -- Human-readable title.
ALTER TABLE enum_versions ADD COLUMN IF NOT EXISTS description TEXT;                                -- Version-specific description.
ALTER TABLE enum_versions ADD COLUMN IF NOT EXISTS default_symbol TEXT;                             -- The default symbol value for this version.
ALTER TABLE enum_versions ADD COLUMN IF NOT EXISTS status TEXT;                                     -- Lifecycle status. One of 'draft' (still being designed; mutable) or 'published' (promoted; immutable thereafter). Versions never leave 'published' — successors are introduced as new versions, optionally pointed at via the parent Word's ReplacedBy.
ALTER TABLE enum_versions ADD COLUMN IF NOT EXISTS created TIMESTAMPTZ;                             -- Creation timestamp from registry.yaml.
ALTER TABLE enum_versions ADD COLUMN IF NOT EXISTS raw_json TEXT;                                   -- Escape hatch: any unmodeled YAML keys (e.g., type: integer for non-string enums, x-gridworks extended_description). JSON-encoded.
ALTER TABLE enum_versions ADD COLUMN IF NOT EXISTS last_modified TIMESTAMPTZ;                       -- Most recent edit to this EnumVersion or its child EnumValues.
ALTER TABLE enum_versions ADD COLUMN IF NOT EXISTS promoted_at TIMESTAMPTZ;                         -- When Status flipped from draft to active.
COMMENT ON TABLE enum_versions IS 'Specific versions of an enum. Each enum can have multiple versions (e.g. gw1.actor.class has versions 009, 010, 011).';
COMMENT ON COLUMN enum_versions.enum_versions_id IS 'Primary key (auto-synthesized: EnumVersions had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN enum_versions.enum IS 'Foreign key to the parent Enum.';
COMMENT ON COLUMN enum_versions.version IS 'Three-digit version string. Example: ''007''.';
COMMENT ON COLUMN enum_versions.schema_url IS 'Schema URL from JSON-Schema $id.';
COMMENT ON COLUMN enum_versions.title IS 'Human-readable title.';
COMMENT ON COLUMN enum_versions.description IS 'Version-specific description.';
COMMENT ON COLUMN enum_versions.default_symbol IS 'The default symbol value for this version.';
COMMENT ON COLUMN enum_versions.status IS 'Lifecycle status. One of ''draft'' (still being designed; mutable) or ''published'' (promoted; immutable thereafter). Versions never leave ''published'' — successors are introduced as new versions, optionally pointed at via the parent Word''s ReplacedBy.';
COMMENT ON COLUMN enum_versions.created IS 'Creation timestamp from registry.yaml.';
COMMENT ON COLUMN enum_versions.raw_json IS 'Escape hatch: any unmodeled YAML keys (e.g., type: integer for non-string enums, x-gridworks extended_description). JSON-encoded.';
COMMENT ON COLUMN enum_versions.last_modified IS 'Most recent edit to this EnumVersion or its child EnumValues.';
COMMENT ON COLUMN enum_versions.promoted_at IS 'When Status flipped from draft to active.';

-- ----------------------------------------------------------------------------
-- EnumValues: Individual symbol values within an EnumVersion (with order preserved and per-symbol descriptions).
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS enum_values (
  enum_values_id                      TEXT                 PRIMARY KEY          -- Primary key (auto-synthesized: EnumValues had no field named 'Id' or ending in 'Id').
);
ALTER TABLE enum_values ADD COLUMN IF NOT EXISTS enum_version TEXT;                                 -- Foreign key to the parent EnumVersion.
ALTER TABLE enum_values ADD COLUMN IF NOT EXISTS symbol TEXT;                                       -- The literal symbol value, e.g. 'Power'.
ALTER TABLE enum_values ADD COLUMN IF NOT EXISTS idx INTEGER;                                       -- Preserves YAML ordering of symbols.
ALTER TABLE enum_values ADD COLUMN IF NOT EXISTS description TEXT;                                  -- Per-symbol description from value_descriptions map.
COMMENT ON TABLE enum_values IS 'Individual symbol values within an EnumVersion (with order preserved and per-symbol descriptions).';
COMMENT ON COLUMN enum_values.enum_values_id IS 'Primary key (auto-synthesized: EnumValues had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN enum_values.enum_version IS 'Foreign key to the parent EnumVersion.';
COMMENT ON COLUMN enum_values.symbol IS 'The literal symbol value, e.g. ''Power''.';
COMMENT ON COLUMN enum_values.idx IS 'Preserves YAML ordering of symbols.';
COMMENT ON COLUMN enum_values.description IS 'Per-symbol description from value_descriptions map.';

-- ----------------------------------------------------------------------------
-- Types: Top-level type definitions (name-level). Each type can have multiple TypeVersions. Sourced from definitions/registry.yaml + definitions/types/.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS types (
  types_id                            TEXT                 PRIMARY KEY          -- Primary key (auto-synthesized: Types had no field named 'Id' or ending in 'Id').
);
ALTER TABLE types ADD COLUMN IF NOT EXISTS name TEXT;                                               -- Type identifier slug. Example: 'report'. Acts as the primary key.
ALTER TABLE types ADD COLUMN IF NOT EXISTS owner TEXT;                                              -- Owner of this type.
ALTER TABLE types ADD COLUMN IF NOT EXISTS title TEXT;                                              -- Name-level title.
ALTER TABLE types ADD COLUMN IF NOT EXISTS description TEXT;                                        -- Name-level description.
ALTER TABLE types ADD COLUMN IF NOT EXISTS replaced_by TEXT;                                        -- Advisory pointer to another Type that supersedes this one. The original Type remains valid and queryable — ReplacedBy is just a hint to consumers about a preferred successor. NOT a state change; published versions are immutable.
ALTER TABLE types ADD COLUMN IF NOT EXISTS python_class_name TEXT;                                  -- Tier-2 placeholder: ODXML-derived Python class name (populated when ODXML data absorbs in).
ALTER TABLE types ADD COLUMN IF NOT EXISTS make_data_class BOOLEAN;                                 -- Tier-2 placeholder: ODXML invariant.
ALTER TABLE types ADD COLUMN IF NOT EXISTS is_cac BOOLEAN;                                          -- Tier-2 placeholder: ODXML invariant (component access control marker).
ALTER TABLE types ADD COLUMN IF NOT EXISTS is_component BOOLEAN;                                    -- Tier-2 placeholder: ODXML invariant.
COMMENT ON TABLE types IS 'Top-level type definitions (name-level). Each type can have multiple TypeVersions. Sourced from definitions/registry.yaml + definitions/types/.';
COMMENT ON COLUMN types.types_id IS 'Primary key (auto-synthesized: Types had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN types.name IS 'Type identifier slug. Example: ''report''. Acts as the primary key.';
COMMENT ON COLUMN types.owner IS 'Owner of this type.';
COMMENT ON COLUMN types.title IS 'Name-level title.';
COMMENT ON COLUMN types.description IS 'Name-level description.';
COMMENT ON COLUMN types.replaced_by IS 'Advisory pointer to another Type that supersedes this one. The original Type remains valid and queryable — ReplacedBy is just a hint to consumers about a preferred successor. NOT a state change; published versions are immutable.';
COMMENT ON COLUMN types.python_class_name IS 'Tier-2 placeholder: ODXML-derived Python class name (populated when ODXML data absorbs in).';
COMMENT ON COLUMN types.make_data_class IS 'Tier-2 placeholder: ODXML invariant.';
COMMENT ON COLUMN types.is_cac IS 'Tier-2 placeholder: ODXML invariant (component access control marker).';
COMMENT ON COLUMN types.is_component IS 'Tier-2 placeholder: ODXML invariant.';

-- ----------------------------------------------------------------------------
-- TypeVersions: Specific versions of a type. Each declares its JSON-Schema shape. Versions follow a 3-digit suffix in the YAML files.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS type_versions (
  type_versions_id                    TEXT                 PRIMARY KEY          -- Primary key (auto-synthesized: TypeVersions had no field named 'Id' or ending in 'Id').
);
ALTER TABLE type_versions ADD COLUMN IF NOT EXISTS type TEXT;                                       -- Foreign key to the parent Type.
ALTER TABLE type_versions ADD COLUMN IF NOT EXISTS version TEXT;                                    -- Three-digit version string. Example: '002'.
ALTER TABLE type_versions ADD COLUMN IF NOT EXISTS schema_url TEXT;                                 -- Schema URL from JSON-Schema $id.
ALTER TABLE type_versions ADD COLUMN IF NOT EXISTS title TEXT;                                      -- Human-readable title.
ALTER TABLE type_versions ADD COLUMN IF NOT EXISTS description TEXT;                                -- Version-specific description.
ALTER TABLE type_versions ADD COLUMN IF NOT EXISTS extra_allowed BOOLEAN;                           -- From JSON-Schema additionalProperties (true=open, false=closed).
ALTER TABLE type_versions ADD COLUMN IF NOT EXISTS status TEXT;                                     -- Lifecycle status. One of 'draft' (still being designed; mutable) or 'published' (promoted; immutable thereafter). Versions never leave 'published' — successors are introduced as new versions, optionally pointed at via the parent Word's ReplacedBy.
ALTER TABLE type_versions ADD COLUMN IF NOT EXISTS created TIMESTAMPTZ;                             -- Creation timestamp.
ALTER TABLE type_versions ADD COLUMN IF NOT EXISTS raw_json TEXT;                                   -- Escape hatch: unmodeled top-level JSON-Schema fields (if/then/else, conditionals, etc.).
ALTER TABLE type_versions ADD COLUMN IF NOT EXISTS last_modified TIMESTAMPTZ;                       -- Most recent edit to this Definition or any of its child rows. Null until the editor lands. Drives Activity-feed sort.
ALTER TABLE type_versions ADD COLUMN IF NOT EXISTS promoted_at TIMESTAMPTZ;                         -- When Status flipped from draft to active. Null for never-promoted drafts. Activity feed renders 'promoted on...' distinct from 'created on...'.
COMMENT ON TABLE type_versions IS 'Specific versions of a type. Each declares its JSON-Schema shape. Versions follow a 3-digit suffix in the YAML files.';
COMMENT ON COLUMN type_versions.type_versions_id IS 'Primary key (auto-synthesized: TypeVersions had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN type_versions.type IS 'Foreign key to the parent Type.';
COMMENT ON COLUMN type_versions.version IS 'Three-digit version string. Example: ''002''.';
COMMENT ON COLUMN type_versions.schema_url IS 'Schema URL from JSON-Schema $id.';
COMMENT ON COLUMN type_versions.title IS 'Human-readable title.';
COMMENT ON COLUMN type_versions.description IS 'Version-specific description.';
COMMENT ON COLUMN type_versions.extra_allowed IS 'From JSON-Schema additionalProperties (true=open, false=closed).';
COMMENT ON COLUMN type_versions.status IS 'Lifecycle status. One of ''draft'' (still being designed; mutable) or ''published'' (promoted; immutable thereafter). Versions never leave ''published'' — successors are introduced as new versions, optionally pointed at via the parent Word''s ReplacedBy.';
COMMENT ON COLUMN type_versions.created IS 'Creation timestamp.';
COMMENT ON COLUMN type_versions.raw_json IS 'Escape hatch: unmodeled top-level JSON-Schema fields (if/then/else, conditionals, etc.).';
COMMENT ON COLUMN type_versions.last_modified IS 'Most recent edit to this Definition or any of its child rows. Null until the editor lands. Drives Activity-feed sort.';
COMMENT ON COLUMN type_versions.promoted_at IS 'When Status flipped from draft to active. Null for never-promoted drafts. Activity feed renders ''promoted on...'' distinct from ''created on...''.';

-- ----------------------------------------------------------------------------
-- TypeAttributes: The shape-of-record for every property declared on a TypeVersion. Polymorphic via mutually-exclusive FK columns: at most one of FormatRef / EnumVersionRef / SubTypeVersionRef / HelperRef is non-null per row.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS type_attributes (
  type_attributes_id                  TEXT                 PRIMARY KEY          -- Primary key (auto-synthesized: TypeAttributes had no field named 'Id' or ending in 'Id').
);
ALTER TABLE type_attributes ADD COLUMN IF NOT EXISTS type_version TEXT;                             -- Foreign key to the owning TypeVersion.
ALTER TABLE type_attributes ADD COLUMN IF NOT EXISTS attribute_name TEXT;                           -- Property key in the JSON-Schema.
ALTER TABLE type_attributes ADD COLUMN IF NOT EXISTS idx INTEGER;                                   -- Preserves YAML ordering of properties.
ALTER TABLE type_attributes ADD COLUMN IF NOT EXISTS description TEXT;                              -- Per-attribute description from JSON-Schema.
ALTER TABLE type_attributes ADD COLUMN IF NOT EXISTS "default" TEXT;                                -- JSON-encoded default value for this attribute (e.g., '"002"', '12', 'false', '1.0', 'null'). Mirrors the JSON Schema 'default:' keyword. Encode as JSON string for typing-uniformity (matches TypeUpgradeOps.LiteralValue convention).
ALTER TABLE type_attributes ADD COLUMN IF NOT EXISTS is_required BOOLEAN;                           -- Derived from the parent TypeVersion's 'required' array.
ALTER TABLE type_attributes ADD COLUMN IF NOT EXISTS is_list BOOLEAN;                               -- True if attribute is type=array. Refs then describe the item type.
ALTER TABLE type_attributes ADD COLUMN IF NOT EXISTS primitive_type TEXT;                           -- Primitive JSON type when none of the *Ref columns apply: string, integer, number, boolean, null.
ALTER TABLE type_attributes ADD COLUMN IF NOT EXISTS format_ref TEXT;                               -- FK to a Format, when this attribute uses a $ref to /formats/X.
ALTER TABLE type_attributes ADD COLUMN IF NOT EXISTS enum_version_ref TEXT;                         -- FK to an EnumVersion, when this attribute uses a $ref to /enums/X/NNN.
ALTER TABLE type_attributes ADD COLUMN IF NOT EXISTS sub_type_version_ref TEXT;                     -- FK to another TypeVersion, when this attribute uses a $ref to /types/X/NNN.
ALTER TABLE type_attributes ADD COLUMN IF NOT EXISTS helper_ref TEXT;                               -- FK to a TypeHelper, when this attribute is an inline-nested object auto-promoted to a helper.
ALTER TABLE type_attributes ADD COLUMN IF NOT EXISTS raw_json TEXT;                                 -- Escape hatch: unmodeled JSON-Schema specifics, including oneOf bodies (v1 parking lot for n=1 cases).
COMMENT ON TABLE type_attributes IS 'The shape-of-record for every property declared on a TypeVersion. Polymorphic via mutually-exclusive FK columns: at most one of FormatRef / EnumVersionRef / SubTypeVersionRef / HelperRef is non-null per row.';
COMMENT ON COLUMN type_attributes.type_attributes_id IS 'Primary key (auto-synthesized: TypeAttributes had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN type_attributes.type_version IS 'Foreign key to the owning TypeVersion.';
COMMENT ON COLUMN type_attributes.attribute_name IS 'Property key in the JSON-Schema.';
COMMENT ON COLUMN type_attributes.idx IS 'Preserves YAML ordering of properties.';
COMMENT ON COLUMN type_attributes.description IS 'Per-attribute description from JSON-Schema.';
COMMENT ON COLUMN type_attributes."default" IS 'JSON-encoded default value for this attribute (e.g., ''"002"'', ''12'', ''false'', ''1.0'', ''null''). Mirrors the JSON Schema ''default:'' keyword. Encode as JSON string for typing-uniformity (matches TypeUpgradeOps.LiteralValue convention).';
COMMENT ON COLUMN type_attributes.is_required IS 'Derived from the parent TypeVersion''s ''required'' array.';
COMMENT ON COLUMN type_attributes.is_list IS 'True if attribute is type=array. Refs then describe the item type.';
COMMENT ON COLUMN type_attributes.primitive_type IS 'Primitive JSON type when none of the *Ref columns apply: string, integer, number, boolean, null.';
COMMENT ON COLUMN type_attributes.format_ref IS 'FK to a Format, when this attribute uses a $ref to /formats/X.';
COMMENT ON COLUMN type_attributes.enum_version_ref IS 'FK to an EnumVersion, when this attribute uses a $ref to /enums/X/NNN.';
COMMENT ON COLUMN type_attributes.sub_type_version_ref IS 'FK to another TypeVersion, when this attribute uses a $ref to /types/X/NNN.';
COMMENT ON COLUMN type_attributes.helper_ref IS 'FK to a TypeHelper, when this attribute is an inline-nested object auto-promoted to a helper.';
COMMENT ON COLUMN type_attributes.raw_json IS 'Escape hatch: unmodeled JSON-Schema specifics, including oneOf bodies (v1 parking lot for n=1 cases).';

-- ----------------------------------------------------------------------------
-- TypeExamples: Per-TypeVersion full-instance examples (with order preserved). Sourced from JSON-Schema 'examples' arrays.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS type_examples (
  type_examples_id                    TEXT                 PRIMARY KEY          -- Primary key (auto-synthesized: TypeExamples had no field named 'Id' or ending in 'Id').
);
ALTER TABLE type_examples ADD COLUMN IF NOT EXISTS type_version TEXT;                               -- Foreign key to the parent TypeVersion.
ALTER TABLE type_examples ADD COLUMN IF NOT EXISTS idx INTEGER;                                     -- Preserves YAML ordering.
ALTER TABLE type_examples ADD COLUMN IF NOT EXISTS example_json TEXT;                               -- Full instance example, serialized as JSON string.
COMMENT ON TABLE type_examples IS 'Per-TypeVersion full-instance examples (with order preserved). Sourced from JSON-Schema ''examples'' arrays.';
COMMENT ON COLUMN type_examples.type_examples_id IS 'Primary key (auto-synthesized: TypeExamples had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN type_examples.type_version IS 'Foreign key to the parent TypeVersion.';
COMMENT ON COLUMN type_examples.idx IS 'Preserves YAML ordering.';
COMMENT ON COLUMN type_examples.example_json IS 'Full instance example, serialized as JSON string.';

-- ----------------------------------------------------------------------------
-- TypeAxioms: Per-TypeVersion axioms (numbered invariants stated in natural language). Sourced from x-gridworks.axioms in YAML.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS type_axioms (
  type_axioms_id                      TEXT                 PRIMARY KEY          -- Primary key (auto-synthesized: TypeAxioms had no field named 'Id' or ending in 'Id').
);
ALTER TABLE type_axioms ADD COLUMN IF NOT EXISTS type_version TEXT;                                 -- Foreign key to the parent TypeVersion.
ALTER TABLE type_axioms ADD COLUMN IF NOT EXISTS number INTEGER;                                    -- Axiom number from YAML.
ALTER TABLE type_axioms ADD COLUMN IF NOT EXISTS axiom_name TEXT;                                   -- Axiom name from YAML.
ALTER TABLE type_axioms ADD COLUMN IF NOT EXISTS statement TEXT;                                    -- Axiom statement (the natural-language invariant).
COMMENT ON TABLE type_axioms IS 'Per-TypeVersion axioms (numbered invariants stated in natural language). Sourced from x-gridworks.axioms in YAML.';
COMMENT ON COLUMN type_axioms.type_axioms_id IS 'Primary key (auto-synthesized: TypeAxioms had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN type_axioms.type_version IS 'Foreign key to the parent TypeVersion.';
COMMENT ON COLUMN type_axioms.number IS 'Axiom number from YAML.';
COMMENT ON COLUMN type_axioms.axiom_name IS 'Axiom name from YAML.';
COMMENT ON COLUMN type_axioms.statement IS 'Axiom statement (the natural-language invariant).';

-- ----------------------------------------------------------------------------
-- TypeHelpers: Non-versioned reusable subtypes auto-promoted from inline nested objects (array items, oneOf branches). Synthesized at migration time. Origin metadata preserves provenance for round-trip YAML emission.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS type_helpers (
  type_helpers_id                     TEXT                 PRIMARY KEY          -- Primary key (auto-synthesized: TypeHelpers had no field named 'Id' or ending in 'Id').
);
ALTER TABLE type_helpers ADD COLUMN IF NOT EXISTS name TEXT;                                        -- Synthesized helper name. Example: 'scada.control.capabilities.RelayNode'. Acts as the primary key.
ALTER TABLE type_helpers ADD COLUMN IF NOT EXISTS title TEXT;                                       -- From inline 'description' if present.
ALTER TABLE type_helpers ADD COLUMN IF NOT EXISTS description TEXT;                                 -- Description of the helper.
ALTER TABLE type_helpers ADD COLUMN IF NOT EXISTS extra_allowed BOOLEAN;                            -- From inline additionalProperties.
ALTER TABLE type_helpers ADD COLUMN IF NOT EXISTS origin_type_version TEXT;                         -- The TypeVersion whose YAML body originally introduced this helper.
ALTER TABLE type_helpers ADD COLUMN IF NOT EXISTS origin_path TEXT;                                 -- JSON-Pointer-ish path within origin (e.g. '/properties/RelayNodes/items') — used to re-inline on YAML emit.
COMMENT ON TABLE type_helpers IS 'Non-versioned reusable subtypes auto-promoted from inline nested objects (array items, oneOf branches). Synthesized at migration time. Origin metadata preserves provenance for round-trip YAML emission.';
COMMENT ON COLUMN type_helpers.type_helpers_id IS 'Primary key (auto-synthesized: TypeHelpers had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN type_helpers.name IS 'Synthesized helper name. Example: ''scada.control.capabilities.RelayNode''. Acts as the primary key.';
COMMENT ON COLUMN type_helpers.title IS 'From inline ''description'' if present.';
COMMENT ON COLUMN type_helpers.description IS 'Description of the helper.';
COMMENT ON COLUMN type_helpers.extra_allowed IS 'From inline additionalProperties.';
COMMENT ON COLUMN type_helpers.origin_type_version IS 'The TypeVersion whose YAML body originally introduced this helper.';
COMMENT ON COLUMN type_helpers.origin_path IS 'JSON-Pointer-ish path within origin (e.g. ''/properties/RelayNodes/items'') — used to re-inline on YAML emit.';

-- ----------------------------------------------------------------------------
-- TypeHelperAttributes: Properties of a TypeHelper. Same shape as TypeAttributes minus the oneOf machinery, since helpers are not versioned.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS type_helper_attributes (
  type_helper_attributes_id           TEXT                 PRIMARY KEY          -- Primary key (auto-synthesized: TypeHelperAttributes had no field named 'Id' or ending in 'Id').
);
ALTER TABLE type_helper_attributes ADD COLUMN IF NOT EXISTS type_helper TEXT;                       -- Foreign key to the parent TypeHelper.
ALTER TABLE type_helper_attributes ADD COLUMN IF NOT EXISTS attribute_name TEXT;                    -- Property key.
ALTER TABLE type_helper_attributes ADD COLUMN IF NOT EXISTS idx INTEGER;                            -- Preserves YAML ordering.
ALTER TABLE type_helper_attributes ADD COLUMN IF NOT EXISTS description TEXT;                       -- Per-attribute description.
ALTER TABLE type_helper_attributes ADD COLUMN IF NOT EXISTS is_required BOOLEAN;                    -- From inline 'required' array.
ALTER TABLE type_helper_attributes ADD COLUMN IF NOT EXISTS is_list BOOLEAN;                        -- True if type=array.
ALTER TABLE type_helper_attributes ADD COLUMN IF NOT EXISTS primitive_type TEXT;                    -- Primitive JSON type when none of the *Ref columns apply.
ALTER TABLE type_helper_attributes ADD COLUMN IF NOT EXISTS format_ref TEXT;                        -- FK to a Format, if this attribute references one.
ALTER TABLE type_helper_attributes ADD COLUMN IF NOT EXISTS enum_version_ref TEXT;                  -- FK to an EnumVersion, if this attribute references one.
ALTER TABLE type_helper_attributes ADD COLUMN IF NOT EXISTS sub_type_version_ref TEXT;              -- FK to a TypeVersion, if this attribute references one.
ALTER TABLE type_helper_attributes ADD COLUMN IF NOT EXISTS helper_ref TEXT;                        -- FK to another TypeHelper (supports nested helpers).
ALTER TABLE type_helper_attributes ADD COLUMN IF NOT EXISTS raw_json TEXT;                          -- Escape hatch for unmodeled JSON-Schema specifics.
COMMENT ON TABLE type_helper_attributes IS 'Properties of a TypeHelper. Same shape as TypeAttributes minus the oneOf machinery, since helpers are not versioned.';
COMMENT ON COLUMN type_helper_attributes.type_helper_attributes_id IS 'Primary key (auto-synthesized: TypeHelperAttributes had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN type_helper_attributes.type_helper IS 'Foreign key to the parent TypeHelper.';
COMMENT ON COLUMN type_helper_attributes.attribute_name IS 'Property key.';
COMMENT ON COLUMN type_helper_attributes.idx IS 'Preserves YAML ordering.';
COMMENT ON COLUMN type_helper_attributes.description IS 'Per-attribute description.';
COMMENT ON COLUMN type_helper_attributes.is_required IS 'From inline ''required'' array.';
COMMENT ON COLUMN type_helper_attributes.is_list IS 'True if type=array.';
COMMENT ON COLUMN type_helper_attributes.primitive_type IS 'Primitive JSON type when none of the *Ref columns apply.';
COMMENT ON COLUMN type_helper_attributes.format_ref IS 'FK to a Format, if this attribute references one.';
COMMENT ON COLUMN type_helper_attributes.enum_version_ref IS 'FK to an EnumVersion, if this attribute references one.';
COMMENT ON COLUMN type_helper_attributes.sub_type_version_ref IS 'FK to a TypeVersion, if this attribute references one.';
COMMENT ON COLUMN type_helper_attributes.helper_ref IS 'FK to another TypeHelper (supports nested helpers).';
COMMENT ON COLUMN type_helper_attributes.raw_json IS 'Escape hatch for unmodeled JSON-Schema specifics.';

-- ----------------------------------------------------------------------------
-- Projections: Named, deterministic enum-to-enum (or value-to-value) mappings used by AddProjected upgrade ops. Today: SpaceheatTelemetryQuantityProjection, Gw1UnitQuantityProjection.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS projections (
  projections_id                      TEXT                 PRIMARY KEY          -- Primary key (auto-synthesized: Projections had no field named 'Id' or ending in 'Id').
);
ALTER TABLE projections ADD COLUMN IF NOT EXISTS name TEXT;                                         -- Projection name. Example: 'SpaceheatTelemetryQuantityProjection'. Acts as the primary key.
ALTER TABLE projections ADD COLUMN IF NOT EXISTS description TEXT;                                  -- Description of what the projection computes.
ALTER TABLE projections ADD COLUMN IF NOT EXISTS from_enum_version TEXT;                            -- Source enum version.
ALTER TABLE projections ADD COLUMN IF NOT EXISTS to_enum_version TEXT;                              -- Target enum version.
ALTER TABLE projections ADD COLUMN IF NOT EXISTS raw_script TEXT;                                   -- Populated only if the projection isn't a flat lookup (escape hatch).
COMMENT ON TABLE projections IS 'Named, deterministic enum-to-enum (or value-to-value) mappings used by AddProjected upgrade ops. Today: SpaceheatTelemetryQuantityProjection, Gw1UnitQuantityProjection.';
COMMENT ON COLUMN projections.projections_id IS 'Primary key (auto-synthesized: Projections had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN projections.name IS 'Projection name. Example: ''SpaceheatTelemetryQuantityProjection''. Acts as the primary key.';
COMMENT ON COLUMN projections.description IS 'Description of what the projection computes.';
COMMENT ON COLUMN projections.from_enum_version IS 'Source enum version.';
COMMENT ON COLUMN projections.to_enum_version IS 'Target enum version.';
COMMENT ON COLUMN projections.raw_script IS 'Populated only if the projection isn''t a flat lookup (escape hatch).';

-- ----------------------------------------------------------------------------
-- ProjectionMappings: Per-symbol mappings for flat-lookup Projections. Empty when the parent Projection uses RawScript.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS projection_mappings (
  projection_mappings_id              TEXT                 PRIMARY KEY          -- Primary key (auto-synthesized: ProjectionMappings had no field named 'Id' or ending in 'Id').
);
ALTER TABLE projection_mappings ADD COLUMN IF NOT EXISTS projection TEXT;                           -- Foreign key to the parent Projection.
ALTER TABLE projection_mappings ADD COLUMN IF NOT EXISTS from_symbol TEXT;                          -- Source enum symbol.
ALTER TABLE projection_mappings ADD COLUMN IF NOT EXISTS to_symbol TEXT;                            -- Target enum symbol.
ALTER TABLE projection_mappings ADD COLUMN IF NOT EXISTS description TEXT;                          -- Optional per-mapping description.
COMMENT ON TABLE projection_mappings IS 'Per-symbol mappings for flat-lookup Projections. Empty when the parent Projection uses RawScript.';
COMMENT ON COLUMN projection_mappings.projection_mappings_id IS 'Primary key (auto-synthesized: ProjectionMappings had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN projection_mappings.projection IS 'Foreign key to the parent Projection.';
COMMENT ON COLUMN projection_mappings.from_symbol IS 'Source enum symbol.';
COMMENT ON COLUMN projection_mappings.to_symbol IS 'Target enum symbol.';
COMMENT ON COLUMN projection_mappings.description IS 'Optional per-mapping description.';

-- ----------------------------------------------------------------------------
-- TypeUpgrades: One row per ordered version pair (N, N+1) for a given type. Mirrors src/sema/runtime/types/old_versions/<type>_<NNN>.py.upgrade() methods.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS type_upgrades (
  type_upgrades_id                    TEXT                 PRIMARY KEY          -- Primary key (auto-synthesized: TypeUpgrades had no field named 'Id' or ending in 'Id').
);
ALTER TABLE type_upgrades ADD COLUMN IF NOT EXISTS from_type_version TEXT;                          -- Source TypeVersion.
ALTER TABLE type_upgrades ADD COLUMN IF NOT EXISTS to_type_version TEXT;                            -- Target TypeVersion.
ALTER TABLE type_upgrades ADD COLUMN IF NOT EXISTS description TEXT;                                -- Description (typically the docstring summary from the .py method).
ALTER TABLE type_upgrades ADD COLUMN IF NOT EXISTS raw_script TEXT;                                 -- Whole-method escape hatch when no clean op decomposition is possible. Prefer per-op RawScript on TypeUpgradeOps.
COMMENT ON TABLE type_upgrades IS 'One row per ordered version pair (N, N+1) for a given type. Mirrors src/sema/runtime/types/old_versions/<type>_<NNN>.py.upgrade() methods.';
COMMENT ON COLUMN type_upgrades.type_upgrades_id IS 'Primary key (auto-synthesized: TypeUpgrades had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN type_upgrades.from_type_version IS 'Source TypeVersion.';
COMMENT ON COLUMN type_upgrades.to_type_version IS 'Target TypeVersion.';
COMMENT ON COLUMN type_upgrades.description IS 'Description (typically the docstring summary from the .py method).';
COMMENT ON COLUMN type_upgrades.raw_script IS 'Whole-method escape hatch when no clean op decomposition is possible. Prefer per-op RawScript on TypeUpgradeOps.';

-- ----------------------------------------------------------------------------
-- TypeUpgradeOps: Atomic operations within a TypeUpgrade. Most upgrades decompose into 1-4 ops. OpKind controls semantics (vocabulary: AddOptional, AddWithDefault, Remove, RequireToOptional, OptionalToRequire, EnumVersionBump, CoerceToEnum, UpgradeChild, UpgradeChildIf, UpgradeListItems, UpgradeListItemsIf, AddProjected, Custom).
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS type_upgrade_ops (
  type_upgrade_ops_id                 TEXT                 PRIMARY KEY          -- Primary key (auto-synthesized: TypeUpgradeOps had no field named 'Id' or ending in 'Id').
);
ALTER TABLE type_upgrade_ops ADD COLUMN IF NOT EXISTS type_upgrade TEXT;                            -- Foreign key to the parent TypeUpgrade.
ALTER TABLE type_upgrade_ops ADD COLUMN IF NOT EXISTS idx INTEGER;                                  -- Execution order within the upgrade.
ALTER TABLE type_upgrade_ops ADD COLUMN IF NOT EXISTS op_kind TEXT;                                 -- Op vocabulary: AddOptional, AddWithDefault, Remove, RequireToOptional, OptionalToRequire, EnumVersionBump, CoerceToEnum, UpgradeChild, UpgradeChildIf, UpgradeListItems, UpgradeListItemsIf, AddProjected, Custom.
ALTER TABLE type_upgrade_ops ADD COLUMN IF NOT EXISTS field_name TEXT;                              -- The attribute name being touched (most ops).
ALTER TABLE type_upgrade_ops ADD COLUMN IF NOT EXISTS literal_value TEXT;                           -- JSON-encoded literal default (AddWithDefault) or source field name (AddProjected).
ALTER TABLE type_upgrade_ops ADD COLUMN IF NOT EXISTS from_version TEXT;                            -- Source version for conditional upgrades (UpgradeChildIf, UpgradeListItemsIf).
ALTER TABLE type_upgrade_ops ADD COLUMN IF NOT EXISTS to_version TEXT;                              -- Target version for explicit version bumps.
ALTER TABLE type_upgrade_ops ADD COLUMN IF NOT EXISTS enum_version_ref TEXT;                        -- FK for enum-related ops (EnumVersionBump, CoerceToEnum).
ALTER TABLE type_upgrade_ops ADD COLUMN IF NOT EXISTS projection_ref TEXT;                          -- FK for AddProjected ops.
ALTER TABLE type_upgrade_ops ADD COLUMN IF NOT EXISTS raw_script TEXT;                              -- Per-op Python escape hatch for Custom ops. Snippet runs in scope of `self` and `data` dict.
ALTER TABLE type_upgrade_ops ADD COLUMN IF NOT EXISTS description TEXT;                             -- Optional op-level description.
COMMENT ON TABLE type_upgrade_ops IS 'Atomic operations within a TypeUpgrade. Most upgrades decompose into 1-4 ops. OpKind controls semantics (vocabulary: AddOptional, AddWithDefault, Remove, RequireToOptional, OptionalToRequire, EnumVersionBump, CoerceToEnum, UpgradeChild, UpgradeChildIf, UpgradeListItems, UpgradeListItemsIf, AddProjected, Custom).';
COMMENT ON COLUMN type_upgrade_ops.type_upgrade_ops_id IS 'Primary key (auto-synthesized: TypeUpgradeOps had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN type_upgrade_ops.type_upgrade IS 'Foreign key to the parent TypeUpgrade.';
COMMENT ON COLUMN type_upgrade_ops.idx IS 'Execution order within the upgrade.';
COMMENT ON COLUMN type_upgrade_ops.op_kind IS 'Op vocabulary: AddOptional, AddWithDefault, Remove, RequireToOptional, OptionalToRequire, EnumVersionBump, CoerceToEnum, UpgradeChild, UpgradeChildIf, UpgradeListItems, UpgradeListItemsIf, AddProjected, Custom.';
COMMENT ON COLUMN type_upgrade_ops.field_name IS 'The attribute name being touched (most ops).';
COMMENT ON COLUMN type_upgrade_ops.literal_value IS 'JSON-encoded literal default (AddWithDefault) or source field name (AddProjected).';
COMMENT ON COLUMN type_upgrade_ops.from_version IS 'Source version for conditional upgrades (UpgradeChildIf, UpgradeListItemsIf).';
COMMENT ON COLUMN type_upgrade_ops.to_version IS 'Target version for explicit version bumps.';
COMMENT ON COLUMN type_upgrade_ops.enum_version_ref IS 'FK for enum-related ops (EnumVersionBump, CoerceToEnum).';
COMMENT ON COLUMN type_upgrade_ops.projection_ref IS 'FK for AddProjected ops.';
COMMENT ON COLUMN type_upgrade_ops.raw_script IS 'Per-op Python escape hatch for Custom ops. Snippet runs in scope of `self` and `data` dict.';
COMMENT ON COLUMN type_upgrade_ops.description IS 'Optional op-level description.';

-- ----------------------------------------------------------------------------
-- EnumUpgrades: Mirror of TypeUpgrades for enum value renames or splits when name preservation breaks. Today's 5 multi-version enums all preserved names, so this table starts empty.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS enum_upgrades (
  enum_upgrades_id                    TEXT                 PRIMARY KEY          -- Primary key (auto-synthesized: EnumUpgrades had no field named 'Id' or ending in 'Id').
);
ALTER TABLE enum_upgrades ADD COLUMN IF NOT EXISTS from_enum_version TEXT;                          -- Source EnumVersion.
ALTER TABLE enum_upgrades ADD COLUMN IF NOT EXISTS to_enum_version TEXT;                            -- Target EnumVersion.
ALTER TABLE enum_upgrades ADD COLUMN IF NOT EXISTS description TEXT;                                -- Description of the enum upgrade.
ALTER TABLE enum_upgrades ADD COLUMN IF NOT EXISTS raw_script TEXT;                                 -- Whole-upgrade escape hatch.
COMMENT ON TABLE enum_upgrades IS 'Mirror of TypeUpgrades for enum value renames or splits when name preservation breaks. Today''s 5 multi-version enums all preserved names, so this table starts empty.';
COMMENT ON COLUMN enum_upgrades.enum_upgrades_id IS 'Primary key (auto-synthesized: EnumUpgrades had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN enum_upgrades.from_enum_version IS 'Source EnumVersion.';
COMMENT ON COLUMN enum_upgrades.to_enum_version IS 'Target EnumVersion.';
COMMENT ON COLUMN enum_upgrades.description IS 'Description of the enum upgrade.';
COMMENT ON COLUMN enum_upgrades.raw_script IS 'Whole-upgrade escape hatch.';

-- ----------------------------------------------------------------------------
-- EnumUpgradeMappings: Per-symbol value renames for an EnumUpgrade. Empty when the parent EnumUpgrade preserves all names.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS enum_upgrade_mappings (
  enum_upgrade_mappings_id            TEXT                 PRIMARY KEY          -- Primary key (auto-synthesized: EnumUpgradeMappings had no field named 'Id' or ending in 'Id').
);
ALTER TABLE enum_upgrade_mappings ADD COLUMN IF NOT EXISTS enum_upgrade TEXT;                       -- Foreign key to the parent EnumUpgrade.
ALTER TABLE enum_upgrade_mappings ADD COLUMN IF NOT EXISTS from_symbol TEXT;                        -- Source enum symbol.
ALTER TABLE enum_upgrade_mappings ADD COLUMN IF NOT EXISTS to_symbol TEXT;                          -- Target enum symbol (or empty/null when symbol is removed).
ALTER TABLE enum_upgrade_mappings ADD COLUMN IF NOT EXISTS description TEXT;                        -- Optional per-mapping description.
COMMENT ON TABLE enum_upgrade_mappings IS 'Per-symbol value renames for an EnumUpgrade. Empty when the parent EnumUpgrade preserves all names.';
COMMENT ON COLUMN enum_upgrade_mappings.enum_upgrade_mappings_id IS 'Primary key (auto-synthesized: EnumUpgradeMappings had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN enum_upgrade_mappings.enum_upgrade IS 'Foreign key to the parent EnumUpgrade.';
COMMENT ON COLUMN enum_upgrade_mappings.from_symbol IS 'Source enum symbol.';
COMMENT ON COLUMN enum_upgrade_mappings.to_symbol IS 'Target enum symbol (or empty/null when symbol is removed).';
COMMENT ON COLUMN enum_upgrade_mappings.description IS 'Optional per-mapping description.';

-- ----------------------------------------------------------------------------
-- AppUsers: Application users authenticated via magic-links. The Name field is the lowercased email — it is both the primary key and the value that the JWT 'email' claim resolves against. AppUsers are editing principals (who can sign in and act in the Explorer); they are independent of Owners (who own published artifacts in the registry).
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS app_users (
  app_users_id                        TEXT                 PRIMARY KEY          -- Primary key (auto-synthesized: AppUsers had no field named 'Id' or ending in 'Id').
);
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS name TEXT;                                           -- Lowercased email address. Acts as the primary key. The verified 'email' claim from a magic-links JWT must equal this value for the user to be recognized.
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS display_name TEXT;                                   -- Optional human-friendly display name shown in the Explorer UI.
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS role TEXT;                                           -- App role. One of: 'admin' (full edit/promote rights once Phase 5 lands) or 'member' (read-only today). Word-level promotion to a finer-grained role table can land later as an additive change.
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS notes TEXT;                                          -- Free-text notes — provenance, why-granted, whatever the registry maintainer wants future readers to know.
ALTER TABLE app_users ADD COLUMN IF NOT EXISTS created TIMESTAMPTZ;                                 -- Creation timestamp.
COMMENT ON TABLE app_users IS 'Application users authenticated via magic-links. The Name field is the lowercased email — it is both the primary key and the value that the JWT ''email'' claim resolves against. AppUsers are editing principals (who can sign in and act in the Explorer); they are independent of Owners (who own published artifacts in the registry).';
COMMENT ON COLUMN app_users.app_users_id IS 'Primary key (auto-synthesized: AppUsers had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN app_users.name IS 'Lowercased email address. Acts as the primary key. The verified ''email'' claim from a magic-links JWT must equal this value for the user to be recognized.';
COMMENT ON COLUMN app_users.display_name IS 'Optional human-friendly display name shown in the Explorer UI.';
COMMENT ON COLUMN app_users.role IS 'App role. One of: ''admin'' (full edit/promote rights once Phase 5 lands) or ''member'' (read-only today). Word-level promotion to a finer-grained role table can land later as an additive change.';
COMMENT ON COLUMN app_users.notes IS 'Free-text notes — provenance, why-granted, whatever the registry maintainer wants future readers to know.';
COMMENT ON COLUMN app_users.created IS 'Creation timestamp.';

-- ----------------------------------------------------------------------------
-- SeedRequests: Seed requests catalogued by the snapshot pipeline. Each row describes the inputs of one `effortless snapshot prepare`/`build` invocation — which Types/Enums to include and how to pin their versions. Mirrors the legacy seed YAML schema (see template_seed_request.yaml).
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS seed_requests (
  seed_requests_id                    TEXT                 PRIMARY KEY          -- Primary key (auto-synthesized: SeedRequests had no field named 'Id' or ending in 'Id').
);
ALTER TABLE seed_requests ADD COLUMN IF NOT EXISTS name TEXT;                                       -- Identifier for this seed request (e.g. 'gridworks-spaceheat'). Acts as the primary key.
ALTER TABLE seed_requests ADD COLUMN IF NOT EXISTS owner TEXT;                                      -- Owner sponsoring this seed request.
ALTER TABLE seed_requests ADD COLUMN IF NOT EXISTS package_name TEXT;                               -- Python package name produced when this seed request is built (e.g. 'gridworks_sema').
ALTER TABLE seed_requests ADD COLUMN IF NOT EXISTS description TEXT;                                -- What this seed request covers and why.
ALTER TABLE seed_requests ADD COLUMN IF NOT EXISTS include_all_versions_default BOOLEAN;            -- When true, entries default to include_all_versions=true unless overridden. Mirrors the top-level convenience flag in the legacy seed YAML.
ALTER TABLE seed_requests ADD COLUMN IF NOT EXISTS created TIMESTAMPTZ;                             -- When this seed request was added to the registry.
COMMENT ON TABLE seed_requests IS 'Seed requests catalogued by the snapshot pipeline. Each row describes the inputs of one `effortless snapshot prepare`/`build` invocation — which Types/Enums to include and how to pin their versions. Mirrors the legacy seed YAML schema (see template_seed_request.yaml).';
COMMENT ON COLUMN seed_requests.seed_requests_id IS 'Primary key (auto-synthesized: SeedRequests had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN seed_requests.name IS 'Identifier for this seed request (e.g. ''gridworks-spaceheat''). Acts as the primary key.';
COMMENT ON COLUMN seed_requests.owner IS 'Owner sponsoring this seed request.';
COMMENT ON COLUMN seed_requests.package_name IS 'Python package name produced when this seed request is built (e.g. ''gridworks_sema'').';
COMMENT ON COLUMN seed_requests.description IS 'What this seed request covers and why.';
COMMENT ON COLUMN seed_requests.include_all_versions_default IS 'When true, entries default to include_all_versions=true unless overridden. Mirrors the top-level convenience flag in the legacy seed YAML.';
COMMENT ON COLUMN seed_requests.created IS 'When this seed request was added to the registry.';

-- ----------------------------------------------------------------------------
-- SeedRequestEntries: Individual targets within a SeedRequest. Each row is one Type or one Enum to include (Formats are never listed directly — they come in via type dependencies).
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS seed_request_entries (
  seed_request_entries_id             TEXT                 PRIMARY KEY          -- Primary key (auto-synthesized: SeedRequestEntries had no field named 'Id' or ending in 'Id').
);
ALTER TABLE seed_request_entries ADD COLUMN IF NOT EXISTS seed_request TEXT;                        -- Parent SeedRequest.
ALTER TABLE seed_request_entries ADD COLUMN IF NOT EXISTS entry_kind TEXT;                          -- What kind of registry word this entry pulls in. One of 'type', 'enum'. (Formats are never listed directly — they come in via type dependencies.)
ALTER TABLE seed_request_entries ADD COLUMN IF NOT EXISTS target_name TEXT;                         -- The Word's Name (e.g. 'synced.readings.bundle', 'relay.energization.state').
ALTER TABLE seed_request_entries ADD COLUMN IF NOT EXISTS include_all_versions BOOLEAN;             -- When true, expand all registry versions for this target. Mirrors `include_all_versions: true` in the seed YAML.
ALTER TABLE seed_request_entries ADD COLUMN IF NOT EXISTS versions TEXT;                            -- Comma-separated explicit version list (e.g. '001,003'). Null/empty means 'use only the latest registry version' unless IncludeAllVersions is true.
ALTER TABLE seed_request_entries ADD COLUMN IF NOT EXISTS reason TEXT;                              -- Free-text why this target is in the request.
COMMENT ON TABLE seed_request_entries IS 'Individual targets within a SeedRequest. Each row is one Type or one Enum to include (Formats are never listed directly — they come in via type dependencies).';
COMMENT ON COLUMN seed_request_entries.seed_request_entries_id IS 'Primary key (auto-synthesized: SeedRequestEntries had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN seed_request_entries.seed_request IS 'Parent SeedRequest.';
COMMENT ON COLUMN seed_request_entries.entry_kind IS 'What kind of registry word this entry pulls in. One of ''type'', ''enum''. (Formats are never listed directly — they come in via type dependencies.)';
COMMENT ON COLUMN seed_request_entries.target_name IS 'The Word''s Name (e.g. ''synced.readings.bundle'', ''relay.energization.state'').';
COMMENT ON COLUMN seed_request_entries.include_all_versions IS 'When true, expand all registry versions for this target. Mirrors `include_all_versions: true` in the seed YAML.';
COMMENT ON COLUMN seed_request_entries.versions IS 'Comma-separated explicit version list (e.g. ''001,003''). Null/empty means ''use only the latest registry version'' unless IncludeAllVersions is true.';
COMMENT ON COLUMN seed_request_entries.reason IS 'Free-text why this target is in the request.';

-- ----------------------------------------------------------------------------
-- Snapshots: Built snapshots produced by the snapshot pipeline. Each row records one materialized `output/sema/<name>` directory plus pointers back to the SeedRequest that produced it.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS snapshots (
  snapshots_id                        TEXT                 PRIMARY KEY          -- Primary key (auto-synthesized: Snapshots had no field named 'Id' or ending in 'Id').
);
ALTER TABLE snapshots ADD COLUMN IF NOT EXISTS name TEXT;                                           -- Identifier for this snapshot build (e.g. 'gridworks-spaceheat@2026-05-13'). Acts as the primary key.
ALTER TABLE snapshots ADD COLUMN IF NOT EXISTS seed_request TEXT;                                   -- Seed request that produced this snapshot.
ALTER TABLE snapshots ADD COLUMN IF NOT EXISTS built_at TIMESTAMPTZ;                                -- When this snapshot was built (UTC).
ALTER TABLE snapshots ADD COLUMN IF NOT EXISTS output_path TEXT;                                    -- Filesystem path where the snapshot was written (e.g. 'output/sema/gridworks-spaceheat').
ALTER TABLE snapshots ADD COLUMN IF NOT EXISTS package_import_root TEXT;                            -- Python import root used for the generated SDK (e.g. 'gridworks_sema').
ALTER TABLE snapshots ADD COLUMN IF NOT EXISTS status TEXT;                                         -- One of 'prepared' (definitions restricted + indexes written), 'built' (runtime generated), or 'published' (released externally).
ALTER TABLE snapshots ADD COLUMN IF NOT EXISTS commit_sha TEXT;                                     -- Git commit sha of the rulebook used to build this snapshot.
COMMENT ON TABLE snapshots IS 'Built snapshots produced by the snapshot pipeline. Each row records one materialized `output/sema/<name>` directory plus pointers back to the SeedRequest that produced it.';
COMMENT ON COLUMN snapshots.snapshots_id IS 'Primary key (auto-synthesized: Snapshots had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN snapshots.name IS 'Identifier for this snapshot build (e.g. ''gridworks-spaceheat@2026-05-13''). Acts as the primary key.';
COMMENT ON COLUMN snapshots.seed_request IS 'Seed request that produced this snapshot.';
COMMENT ON COLUMN snapshots.built_at IS 'When this snapshot was built (UTC).';
COMMENT ON COLUMN snapshots.output_path IS 'Filesystem path where the snapshot was written (e.g. ''output/sema/gridworks-spaceheat'').';
COMMENT ON COLUMN snapshots.package_import_root IS 'Python import root used for the generated SDK (e.g. ''gridworks_sema'').';
COMMENT ON COLUMN snapshots.status IS 'One of ''prepared'' (definitions restricted + indexes written), ''built'' (runtime generated), or ''published'' (released externally).';
COMMENT ON COLUMN snapshots.commit_sha IS 'Git commit sha of the rulebook used to build this snapshot.';

-- ----------------------------------------------------------------------------
-- LocalNames: Per-snapshot local-naming overrides. Models `local_names.yaml` inside a snapshot — each row pairs a canonical registry name with the local rebranding used inside the snapshot's generated package.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS local_names (
  local_names_id                      TEXT                 PRIMARY KEY          -- Primary key (auto-synthesized: LocalNames had no field named 'Id' or ending in 'Id').
);
ALTER TABLE local_names ADD COLUMN IF NOT EXISTS snapshot TEXT;                                     -- Parent Snapshot.
ALTER TABLE local_names ADD COLUMN IF NOT EXISTS kind TEXT;                                         -- One of 'type', 'enum', 'format'.
ALTER TABLE local_names ADD COLUMN IF NOT EXISTS canonical_name TEXT;                               -- The full canonical name as it appears in the registry (e.g. 'synced.readings.bundle').
ALTER TABLE local_names ADD COLUMN IF NOT EXISTS local_name TEXT;                                   -- The locally-rebranded name within this snapshot's local_names.yaml. Often identical to CanonicalName when no rebranding is applied.
COMMENT ON TABLE local_names IS 'Per-snapshot local-naming overrides. Models `local_names.yaml` inside a snapshot — each row pairs a canonical registry name with the local rebranding used inside the snapshot''s generated package.';
COMMENT ON COLUMN local_names.local_names_id IS 'Primary key (auto-synthesized: LocalNames had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN local_names.snapshot IS 'Parent Snapshot.';
COMMENT ON COLUMN local_names.kind IS 'One of ''type'', ''enum'', ''format''.';
COMMENT ON COLUMN local_names.canonical_name IS 'The full canonical name as it appears in the registry (e.g. ''synced.readings.bundle'').';
COMMENT ON COLUMN local_names.local_name IS 'The locally-rebranded name within this snapshot''s local_names.yaml. Often identical to CanonicalName when no rebranding is applied.';

-- ----------------------------------------------------------------------------
-- IndexBuilders: Catalogue of the Python builder scripts orchestrated by scripts/build_indexes.sh. The rulebook describes the build sequence (run order, output path, re-run pass) rather than the output files themselves — those are downstream artifacts.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS index_builders (
  index_builders_id                   TEXT                 PRIMARY KEY          -- Primary key (auto-synthesized: IndexBuilders had no field named 'Id' or ending in 'Id').
);
ALTER TABLE index_builders ADD COLUMN IF NOT EXISTS name TEXT;                                      -- Builder name (e.g. 'build_public_registry'). Primary key.
ALTER TABLE index_builders ADD COLUMN IF NOT EXISTS script_path TEXT;                               -- Path to the Python script that implements this builder (relative to repo root).
ALTER TABLE index_builders ADD COLUMN IF NOT EXISTS run_order INTEGER;                              -- Position in the orchestrated build sequence (lower runs first).
ALTER TABLE index_builders ADD COLUMN IF NOT EXISTS output_path TEXT;                               -- Path of the YAML index file this builder emits (relative to repo root).
ALTER TABLE index_builders ADD COLUMN IF NOT EXISTS inputs_description TEXT;                        -- Brief description of what this builder reads to produce its output.
ALTER TABLE index_builders ADD COLUMN IF NOT EXISTS description TEXT;                               -- What the builder does and why it exists.
ALTER TABLE index_builders ADD COLUMN IF NOT EXISTS rerun_at_end BOOLEAN;                           -- True iff this builder is re-run as a final pass after all other builders complete (currently only build_public_registry needs this, to incorporate facts surfaced by downstream builders).
COMMENT ON TABLE index_builders IS 'Catalogue of the Python builder scripts orchestrated by scripts/build_indexes.sh. The rulebook describes the build sequence (run order, output path, re-run pass) rather than the output files themselves — those are downstream artifacts.';
COMMENT ON COLUMN index_builders.index_builders_id IS 'Primary key (auto-synthesized: IndexBuilders had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN index_builders.name IS 'Builder name (e.g. ''build_public_registry''). Primary key.';
COMMENT ON COLUMN index_builders.script_path IS 'Path to the Python script that implements this builder (relative to repo root).';
COMMENT ON COLUMN index_builders.run_order IS 'Position in the orchestrated build sequence (lower runs first).';
COMMENT ON COLUMN index_builders.output_path IS 'Path of the YAML index file this builder emits (relative to repo root).';
COMMENT ON COLUMN index_builders.inputs_description IS 'Brief description of what this builder reads to produce its output.';
COMMENT ON COLUMN index_builders.description IS 'What the builder does and why it exists.';
COMMENT ON COLUMN index_builders.rerun_at_end IS 'True iff this builder is re-run as a final pass after all other builders complete (currently only build_public_registry needs this, to incorporate facts surfaced by downstream builders).';

-- ----------------------------------------------------------------------------
-- Templates: Generator templates that implement axiom and upgrade behavior. Runtime generation REQUIRES that every TypeVersion declaring an axiom (or upgrade) has a matching Templates row pointing at the corresponding `.jinja2` file (see runtime_generation/templates/).
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS templates (
  templates_id                        TEXT                 PRIMARY KEY          -- Primary key (auto-synthesized: Templates had no field named 'Id' or ending in 'Id').
);
ALTER TABLE templates ADD COLUMN IF NOT EXISTS name TEXT;                                           -- Composite template identifier. Convention: '<kind>:<owner-version-id>' (e.g. 'axiom:atn.bid/002', 'upgrade:bid/000->bid/002'). Primary key.
ALTER TABLE templates ADD COLUMN IF NOT EXISTS kind TEXT;                                           -- Template kind. One of 'axiom' or 'upgrade'.
ALTER TABLE templates ADD COLUMN IF NOT EXISTS path TEXT;                                           -- Path to the .jinja2 template file relative to repo root.
ALTER TABLE templates ADD COLUMN IF NOT EXISTS language TEXT;                                       -- Target language. Currently always 'python'.
ALTER TABLE templates ADD COLUMN IF NOT EXISTS status TEXT;                                         -- Template status: 'present' (file exists), 'missing' (declared but not yet scaffolded), 'deprecated'.
ALTER TABLE templates ADD COLUMN IF NOT EXISTS axiom_type_version TEXT;                             -- When Kind='axiom': the TypeVersion this axiom implements.
ALTER TABLE templates ADD COLUMN IF NOT EXISTS upgrade_from_type_version TEXT;                      -- When Kind='upgrade' between types: the source TypeVersion.
ALTER TABLE templates ADD COLUMN IF NOT EXISTS upgrade_to_type_version TEXT;                        -- When Kind='upgrade' between types: the destination TypeVersion.
ALTER TABLE templates ADD COLUMN IF NOT EXISTS upgrade_from_enum_version TEXT;                      -- When Kind='upgrade' between enums: the source EnumVersion.
ALTER TABLE templates ADD COLUMN IF NOT EXISTS upgrade_to_enum_version TEXT;                        -- When Kind='upgrade' between enums: the destination EnumVersion.
COMMENT ON TABLE templates IS 'Generator templates that implement axiom and upgrade behavior. Runtime generation REQUIRES that every TypeVersion declaring an axiom (or upgrade) has a matching Templates row pointing at the corresponding `.jinja2` file (see runtime_generation/templates/).';
COMMENT ON COLUMN templates.templates_id IS 'Primary key (auto-synthesized: Templates had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN templates.name IS 'Composite template identifier. Convention: ''<kind>:<owner-version-id>'' (e.g. ''axiom:atn.bid/002'', ''upgrade:bid/000->bid/002''). Primary key.';
COMMENT ON COLUMN templates.kind IS 'Template kind. One of ''axiom'' or ''upgrade''.';
COMMENT ON COLUMN templates.path IS 'Path to the .jinja2 template file relative to repo root.';
COMMENT ON COLUMN templates.language IS 'Target language. Currently always ''python''.';
COMMENT ON COLUMN templates.status IS 'Template status: ''present'' (file exists), ''missing'' (declared but not yet scaffolded), ''deprecated''.';
COMMENT ON COLUMN templates.axiom_type_version IS 'When Kind=''axiom'': the TypeVersion this axiom implements.';
COMMENT ON COLUMN templates.upgrade_from_type_version IS 'When Kind=''upgrade'' between types: the source TypeVersion.';
COMMENT ON COLUMN templates.upgrade_to_type_version IS 'When Kind=''upgrade'' between types: the destination TypeVersion.';
COMMENT ON COLUMN templates.upgrade_from_enum_version IS 'When Kind=''upgrade'' between enums: the source EnumVersion.';
COMMENT ON COLUMN templates.upgrade_to_enum_version IS 'When Kind=''upgrade'' between enums: the destination EnumVersion.';

-- ----------------------------------------------------------------------------
-- CliCommands: The hierarchical surface of the `sema` CLI — every parser node from src/sema/interfaces/cli/. Each row is one subcommand or the root. Parent links form a tree; flags and examples attach via CliFlags.Command and CliExamples.Command. This is descriptive scaffolding (Tier B of ERB-SCAFFOLD-PLAN.md) — the CLI is still implemented in Python, but the rulebook now points at every node.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS cli_commands (
  cli_commands_id                     TEXT                 PRIMARY KEY          -- Primary key (auto-synthesized: CliCommands had no field named 'Id' or ending in 'Id').
);
ALTER TABLE cli_commands ADD COLUMN IF NOT EXISTS name TEXT;                                        -- Fully-qualified command path. Example: 'sema snapshot prepare'. Acts as the primary key.
ALTER TABLE cli_commands ADD COLUMN IF NOT EXISTS parent TEXT;                                      -- FK to the parent CliCommand. NULL for the root 'sema'. Children's Names start with their Parent's Name followed by a single space.
ALTER TABLE cli_commands ADD COLUMN IF NOT EXISTS impl_file TEXT;                                   -- Path (relative to repo root) of the Python file that defines this command's parser/handler.
ALTER TABLE cli_commands ADD COLUMN IF NOT EXISTS summary TEXT;                                     -- Short one-line description, mirroring the argparse `help=` for this subparser.
ALTER TABLE cli_commands ADD COLUMN IF NOT EXISTS description TEXT;                                 -- Longer description, mirroring the argparse `description=` for this subparser. Often spans multiple sentences.
COMMENT ON TABLE cli_commands IS 'The hierarchical surface of the `sema` CLI — every parser node from src/sema/interfaces/cli/. Each row is one subcommand or the root. Parent links form a tree; flags and examples attach via CliFlags.Command and CliExamples.Command. This is descriptive scaffolding (Tier B of ERB-SCAFFOLD-PLAN.md) — the CLI is still implemented in Python, but the rulebook now points at every node.';
COMMENT ON COLUMN cli_commands.cli_commands_id IS 'Primary key (auto-synthesized: CliCommands had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN cli_commands.name IS 'Fully-qualified command path. Example: ''sema snapshot prepare''. Acts as the primary key.';
COMMENT ON COLUMN cli_commands.parent IS 'FK to the parent CliCommand. NULL for the root ''sema''. Children''s Names start with their Parent''s Name followed by a single space.';
COMMENT ON COLUMN cli_commands.impl_file IS 'Path (relative to repo root) of the Python file that defines this command''s parser/handler.';
COMMENT ON COLUMN cli_commands.summary IS 'Short one-line description, mirroring the argparse `help=` for this subparser.';
COMMENT ON COLUMN cli_commands.description IS 'Longer description, mirroring the argparse `description=` for this subparser. Often spans multiple sentences.';

-- ----------------------------------------------------------------------------
-- CliFlags: Every flag (positional or named) declared on a CliCommand. Name is the compound key Command::FlagName. Kind names a primitive value type; EnumValuesRef points at an Enum when a flag's value is constrained to a rulebook enum (no current flag uses this, but the column is reserved for future use).
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS cli_flags (
  cli_flags_id                        TEXT                 PRIMARY KEY          -- Primary key (auto-synthesized: CliFlags had no field named 'Id' or ending in 'Id').
);
ALTER TABLE cli_flags ADD COLUMN IF NOT EXISTS command TEXT;                                        -- FK to the CliCommands row this flag attaches to.
ALTER TABLE cli_flags ADD COLUMN IF NOT EXISTS flag_name TEXT;                                      -- Flag spelling. Positional args use the bare identifier ('name', 'version'). Named args use the long form including dashes ('--package-name').
ALTER TABLE cli_flags ADD COLUMN IF NOT EXISTS short_name TEXT;                                     -- Short alias if defined ('-p'). NULL for positional args and named-only flags.
ALTER TABLE cli_flags ADD COLUMN IF NOT EXISTS is_positional BOOLEAN;                               -- True when the argparse action is a positional argument. False for named flags.
ALTER TABLE cli_flags ADD COLUMN IF NOT EXISTS kind TEXT;                                           -- Primitive value type. One of 'string', 'bool', 'int', 'path'. Reserved value 'enum' applies when EnumValuesRef is non-null.
ALTER TABLE cli_flags ADD COLUMN IF NOT EXISTS required BOOLEAN;                                    -- True when the flag is mandatory. For positional args this maps to nargs not being '?' or '*'.
ALTER TABLE cli_flags ADD COLUMN IF NOT EXISTS "default" TEXT;                                      -- Stringified default value, or NULL when there is no default.
ALTER TABLE cli_flags ADD COLUMN IF NOT EXISTS description TEXT;                                    -- Short description, taken from argparse `help=` where available.
ALTER TABLE cli_flags ADD COLUMN IF NOT EXISTS enum_values_ref TEXT;                                -- When the flag accepts values constrained to a rulebook Enum, points at the Enum row. NULL otherwise.
COMMENT ON TABLE cli_flags IS 'Every flag (positional or named) declared on a CliCommand. Name is the compound key Command::FlagName. Kind names a primitive value type; EnumValuesRef points at an Enum when a flag''s value is constrained to a rulebook enum (no current flag uses this, but the column is reserved for future use).';
COMMENT ON COLUMN cli_flags.cli_flags_id IS 'Primary key (auto-synthesized: CliFlags had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN cli_flags.command IS 'FK to the CliCommands row this flag attaches to.';
COMMENT ON COLUMN cli_flags.flag_name IS 'Flag spelling. Positional args use the bare identifier (''name'', ''version''). Named args use the long form including dashes (''--package-name'').';
COMMENT ON COLUMN cli_flags.short_name IS 'Short alias if defined (''-p''). NULL for positional args and named-only flags.';
COMMENT ON COLUMN cli_flags.is_positional IS 'True when the argparse action is a positional argument. False for named flags.';
COMMENT ON COLUMN cli_flags.kind IS 'Primitive value type. One of ''string'', ''bool'', ''int'', ''path''. Reserved value ''enum'' applies when EnumValuesRef is non-null.';
COMMENT ON COLUMN cli_flags.required IS 'True when the flag is mandatory. For positional args this maps to nargs not being ''?'' or ''*''.';
COMMENT ON COLUMN cli_flags."default" IS 'Stringified default value, or NULL when there is no default.';
COMMENT ON COLUMN cli_flags.description IS 'Short description, taken from argparse `help=` where available.';
COMMENT ON COLUMN cli_flags.enum_values_ref IS 'When the flag accepts values constrained to a rulebook Enum, points at the Enum row. NULL otherwise.';

-- ----------------------------------------------------------------------------
-- CliExamples: Concrete example invocations for a CliCommand. Sourced from argparse `epilog=` blocks. Idx preserves listing order. ExpectedExitCode defaults to 0 (success); future rows can document expected-failure examples.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS cli_examples (
  cli_examples_id                     TEXT                 PRIMARY KEY          -- Primary key (auto-synthesized: CliExamples had no field named 'Id' or ending in 'Id').
);
ALTER TABLE cli_examples ADD COLUMN IF NOT EXISTS command TEXT;                                     -- FK to the CliCommands row this example illustrates.
ALTER TABLE cli_examples ADD COLUMN IF NOT EXISTS idx INTEGER;                                      -- 0-indexed ordering of this example within its Command's epilog.
ALTER TABLE cli_examples ADD COLUMN IF NOT EXISTS example_string TEXT;                              -- The full command-line invocation as it would be typed in a terminal.
ALTER TABLE cli_examples ADD COLUMN IF NOT EXISTS description TEXT;                                 -- Optional short note about what this example demonstrates.
ALTER TABLE cli_examples ADD COLUMN IF NOT EXISTS expected_exit_code INTEGER;                       -- POSIX exit code the example is expected to produce. 0 for success.
COMMENT ON TABLE cli_examples IS 'Concrete example invocations for a CliCommand. Sourced from argparse `epilog=` blocks. Idx preserves listing order. ExpectedExitCode defaults to 0 (success); future rows can document expected-failure examples.';
COMMENT ON COLUMN cli_examples.cli_examples_id IS 'Primary key (auto-synthesized: CliExamples had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN cli_examples.command IS 'FK to the CliCommands row this example illustrates.';
COMMENT ON COLUMN cli_examples.idx IS '0-indexed ordering of this example within its Command''s epilog.';
COMMENT ON COLUMN cli_examples.example_string IS 'The full command-line invocation as it would be typed in a terminal.';
COMMENT ON COLUMN cli_examples.description IS 'Optional short note about what this example demonstrates.';
COMMENT ON COLUMN cli_examples.expected_exit_code IS 'POSIX exit code the example is expected to produce. 0 for success.';

-- ============================================================================
-- FK INDEXES - Performance only, always applied
-- ============================================================================

-- Formats
CREATE INDEX IF NOT EXISTS idx_formats_owner ON formats (owner);
CREATE INDEX IF NOT EXISTS idx_formats_replaced_by ON formats (replaced_by);

-- FormatExamples
CREATE INDEX IF NOT EXISTS idx_format_examples_format ON format_examples (format);

-- Enums
CREATE INDEX IF NOT EXISTS idx_enums_owner ON enums (owner);
CREATE INDEX IF NOT EXISTS idx_enums_replaced_by ON enums (replaced_by);

-- EnumVersions
CREATE INDEX IF NOT EXISTS idx_enum_versions_enum ON enum_versions (enum);

-- EnumValues
CREATE INDEX IF NOT EXISTS idx_enum_values_enum_version ON enum_values (enum_version);

-- Types
CREATE INDEX IF NOT EXISTS idx_types_owner ON types (owner);
CREATE INDEX IF NOT EXISTS idx_types_replaced_by ON types (replaced_by);

-- TypeVersions
CREATE INDEX IF NOT EXISTS idx_type_versions_type ON type_versions (type);

-- TypeAttributes
CREATE INDEX IF NOT EXISTS idx_type_attributes_type_version ON type_attributes (type_version);
CREATE INDEX IF NOT EXISTS idx_type_attributes_format_ref ON type_attributes (format_ref);
CREATE INDEX IF NOT EXISTS idx_type_attributes_enum_version_ref ON type_attributes (enum_version_ref);
CREATE INDEX IF NOT EXISTS idx_type_attributes_sub_type_version_ref ON type_attributes (sub_type_version_ref);
CREATE INDEX IF NOT EXISTS idx_type_attributes_helper_ref ON type_attributes (helper_ref);

-- TypeExamples
CREATE INDEX IF NOT EXISTS idx_type_examples_type_version ON type_examples (type_version);

-- TypeAxioms
CREATE INDEX IF NOT EXISTS idx_type_axioms_type_version ON type_axioms (type_version);

-- TypeHelpers
CREATE INDEX IF NOT EXISTS idx_type_helpers_origin_type_version ON type_helpers (origin_type_version);

-- TypeHelperAttributes
CREATE INDEX IF NOT EXISTS idx_type_helper_attributes_type_helper ON type_helper_attributes (type_helper);
CREATE INDEX IF NOT EXISTS idx_type_helper_attributes_format_ref ON type_helper_attributes (format_ref);
CREATE INDEX IF NOT EXISTS idx_type_helper_attributes_enum_version_ref ON type_helper_attributes (enum_version_ref);
CREATE INDEX IF NOT EXISTS idx_type_helper_attributes_sub_type_version_ref ON type_helper_attributes (sub_type_version_ref);
CREATE INDEX IF NOT EXISTS idx_type_helper_attributes_helper_ref ON type_helper_attributes (helper_ref);

-- Projections
CREATE INDEX IF NOT EXISTS idx_projections_from_enum_version ON projections (from_enum_version);
CREATE INDEX IF NOT EXISTS idx_projections_to_enum_version ON projections (to_enum_version);

-- ProjectionMappings
CREATE INDEX IF NOT EXISTS idx_projection_mappings_projection ON projection_mappings (projection);

-- TypeUpgrades
CREATE INDEX IF NOT EXISTS idx_type_upgrades_from_type_version ON type_upgrades (from_type_version);
CREATE INDEX IF NOT EXISTS idx_type_upgrades_to_type_version ON type_upgrades (to_type_version);

-- TypeUpgradeOps
CREATE INDEX IF NOT EXISTS idx_type_upgrade_ops_type_upgrade ON type_upgrade_ops (type_upgrade);
CREATE INDEX IF NOT EXISTS idx_type_upgrade_ops_enum_version_ref ON type_upgrade_ops (enum_version_ref);
CREATE INDEX IF NOT EXISTS idx_type_upgrade_ops_projection_ref ON type_upgrade_ops (projection_ref);

-- EnumUpgrades
CREATE INDEX IF NOT EXISTS idx_enum_upgrades_from_enum_version ON enum_upgrades (from_enum_version);
CREATE INDEX IF NOT EXISTS idx_enum_upgrades_to_enum_version ON enum_upgrades (to_enum_version);

-- EnumUpgradeMappings
CREATE INDEX IF NOT EXISTS idx_enum_upgrade_mappings_enum_upgrade ON enum_upgrade_mappings (enum_upgrade);

-- SeedRequests
CREATE INDEX IF NOT EXISTS idx_seed_requests_owner ON seed_requests (owner);

-- SeedRequestEntries
CREATE INDEX IF NOT EXISTS idx_seed_request_entries_seed_request ON seed_request_entries (seed_request);

-- Snapshots
CREATE INDEX IF NOT EXISTS idx_snapshots_seed_request ON snapshots (seed_request);

-- LocalNames
CREATE INDEX IF NOT EXISTS idx_local_names_snapshot ON local_names (snapshot);

-- Templates
CREATE INDEX IF NOT EXISTS idx_templates_axiom_type_version ON templates (axiom_type_version);
CREATE INDEX IF NOT EXISTS idx_templates_upgrade_from_type_version ON templates (upgrade_from_type_version);
CREATE INDEX IF NOT EXISTS idx_templates_upgrade_to_type_version ON templates (upgrade_to_type_version);
CREATE INDEX IF NOT EXISTS idx_templates_upgrade_from_enum_version ON templates (upgrade_from_enum_version);
CREATE INDEX IF NOT EXISTS idx_templates_upgrade_to_enum_version ON templates (upgrade_to_enum_version);

-- CliCommands
CREATE INDEX IF NOT EXISTS idx_cli_commands_parent ON cli_commands (parent);

-- CliFlags
CREATE INDEX IF NOT EXISTS idx_cli_flags_command ON cli_flags (command);
CREATE INDEX IF NOT EXISTS idx_cli_flags_enum_values_ref ON cli_flags (enum_values_ref);

-- CliExamples
CREATE INDEX IF NOT EXISTS idx_cli_examples_command ON cli_examples (command);

-- 47 FK index(es) declared.
