-- ============================================================================
-- DROP AND CREATE TABLES - Clean slate + Normalized schema
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Total Tables: 19
-- Total Raw Fields: 119
-- ============================================================================

SET timezone = 'UTC';

-- ============================================================================
-- DROP SPECIFIC OBJECTS - Only dropping objects that will be recreated
-- ============================================================================

-- Drop functions (order: first, because views depend on them)
DROP FUNCTION IF EXISTS calc_enum_upgrade_mappings_is_identity(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_enum_upgrade_mappings_is_removal(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_enum_upgrade_mappings_name(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_enum_upgrades_is_decomposed(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_enum_upgrades_is_scripted(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_enum_upgrades_mapping_count(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_enum_upgrades_name(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_enum_values_has_description(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_enum_values_name(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_enum_versions_has_default_symbol(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_enum_versions_is_active(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_enum_versions_is_deprecated(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_enum_versions_name(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_enum_versions_value_count(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_enums_is_integer_valued(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_enums_is_literal(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_enums_is_retired(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_enums_is_versioned(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_enums_version_count(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_format_examples_example_kind(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_format_examples_name(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_formats_counter_example_count(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_formats_example_count(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_formats_has_length_bounds(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_formats_has_pattern(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_formats_is_retired(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_owners_enum_count(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_owners_format_count(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_owners_has_github(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_owners_is_organization(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_owners_type_count(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_projection_mappings_is_identity(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_projection_mappings_is_removal(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_projection_mappings_name(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_projections_is_flat_lookup(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_projections_is_scripted(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_projections_mapping_count(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_type_attributes_has_default(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_type_attributes_is_optional(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_type_attributes_name(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_type_attributes_ref_kind(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_type_axioms_has_statement(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_type_axioms_name(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_type_examples_name(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_type_helper_attributes_is_optional(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_type_helper_attributes_name(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_type_helper_attributes_ref_kind(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_type_helpers_attribute_count(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_type_helpers_is_closed(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_type_helpers_required_attribute_count(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_type_upgrade_ops_has_raw_script(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_type_upgrade_ops_is_custom(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_type_upgrade_ops_name(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_type_upgrade_ops_reference_kind(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_type_upgrades_is_decomposed(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_type_upgrades_is_scripted(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_type_upgrades_name(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_type_upgrades_op_count(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_type_versions_attribute_count(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_type_versions_axiom_count(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_type_versions_example_count(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_type_versions_is_active(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_type_versions_is_closed(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_type_versions_is_deprecated(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_type_versions_name(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_type_versions_required_attribute_count(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_types_is_retired(TEXT) CASCADE;
DROP FUNCTION IF EXISTS calc_types_version_count(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_enum_upgrades_description(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_enum_upgrades_raw_script(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_enum_versions_created(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_enum_versions_default_symbol(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_enum_versions_description(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_enum_versions_raw_json(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_enum_versions_schema_url(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_enum_versions_status(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_enum_versions_title(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_enum_versions_version(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_enums_description(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_enums_enum_type(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_enums_name(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_enums_raw_json(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_enums_value_type(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_formats_created(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_formats_description(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_formats_json_schema_format(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_formats_max_length(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_formats_min_length(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_formats_name(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_formats_pattern(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_formats_raw_json(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_formats_schema_url(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_formats_title(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_owners_contact(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_owners_description(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_owners_github(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_owners_license(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_owners_name(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_owners_organization(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_owners_owner_type(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_owners_support_policy(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_owners_website(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_projections_description(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_projections_name(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_projections_raw_script(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_type_helpers_description(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_type_helpers_extra_allowed(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_type_helpers_name(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_type_helpers_origin_path(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_type_helpers_title(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_type_upgrades_description(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_type_upgrades_raw_script(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_type_versions_created(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_type_versions_description(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_type_versions_extra_allowed(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_type_versions_raw_json(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_type_versions_schema_url(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_type_versions_status(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_type_versions_title(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_type_versions_version(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_types_description(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_types_is_cac(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_types_is_component(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_types_make_data_class(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_types_name(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_types_python_class_name(TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_types_title(TEXT) CASCADE;

-- Drop views (order: second, because they depend on tables)
DROP VIEW IF EXISTS vw_enum_upgrade_mappings CASCADE;
DROP VIEW IF EXISTS vw_enum_upgrades CASCADE;
DROP VIEW IF EXISTS vw_enum_values CASCADE;
DROP VIEW IF EXISTS vw_enum_versions CASCADE;
DROP VIEW IF EXISTS vw_enums CASCADE;
DROP VIEW IF EXISTS vw_format_examples CASCADE;
DROP VIEW IF EXISTS vw_formats CASCADE;
DROP VIEW IF EXISTS vw_owners CASCADE;
DROP VIEW IF EXISTS vw_projection_mappings CASCADE;
DROP VIEW IF EXISTS vw_projections CASCADE;
DROP VIEW IF EXISTS vw_type_attributes CASCADE;
DROP VIEW IF EXISTS vw_type_axioms CASCADE;
DROP VIEW IF EXISTS vw_type_examples CASCADE;
DROP VIEW IF EXISTS vw_type_helper_attributes CASCADE;
DROP VIEW IF EXISTS vw_type_helpers CASCADE;
DROP VIEW IF EXISTS vw_type_upgrade_ops CASCADE;
DROP VIEW IF EXISTS vw_type_upgrades CASCADE;
DROP VIEW IF EXISTS vw_type_versions CASCADE;
DROP VIEW IF EXISTS vw_types CASCADE;

-- Drop tables (order: last, after dependent objects are removed)
DROP TABLE IF EXISTS enum_upgrade_mappings CASCADE;
DROP TABLE IF EXISTS enum_upgrades CASCADE;
DROP TABLE IF EXISTS enum_values CASCADE;
DROP TABLE IF EXISTS enum_versions CASCADE;
DROP TABLE IF EXISTS enums CASCADE;
DROP TABLE IF EXISTS format_examples CASCADE;
DROP TABLE IF EXISTS formats CASCADE;
DROP TABLE IF EXISTS owners CASCADE;
DROP TABLE IF EXISTS projection_mappings CASCADE;
DROP TABLE IF EXISTS projections CASCADE;
DROP TABLE IF EXISTS type_attributes CASCADE;
DROP TABLE IF EXISTS type_axioms CASCADE;
DROP TABLE IF EXISTS type_examples CASCADE;
DROP TABLE IF EXISTS type_helper_attributes CASCADE;
DROP TABLE IF EXISTS type_helpers CASCADE;
DROP TABLE IF EXISTS type_upgrade_ops CASCADE;
DROP TABLE IF EXISTS type_upgrades CASCADE;
DROP TABLE IF EXISTS type_versions CASCADE;
DROP TABLE IF EXISTS types CASCADE;

-- ============================================================================
-- CREATE TABLES - Normalized data only (no calculated fields)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Owners: Entities (organizations or individuals) that own Types, Enums, and Formats. Sourced from definitions/owners.yaml.
-- ----------------------------------------------------------------------------
CREATE TABLE owners (
  owners_id                           TEXT                 PRIMARY KEY,         -- Primary key (auto-synthesized: Owners had no field named 'Id' or ending in 'Id').
  name                                TEXT                ,                     -- Owner identifier slug. Example: 'gridworks-energy'. Acts as the primary key.
  owner_type                          TEXT                ,                     -- Either 'organization' or 'individual'.
  contact                             TEXT                ,                     -- Primary contact email.
  website                             TEXT                ,                     -- Owner's website URL.
  github                              TEXT                ,                     -- Owner's GitHub URL (optional).
  organization                        TEXT                ,                     -- Full legal/organization name.
  description                         TEXT                ,                     -- Free-text description of the owner's domain or focus.
  support_policy                      TEXT                ,                     -- How users get support from this owner.
  license                             TEXT                                      -- License under which the owner's contributions are published (e.g. 'MIT').
);
COMMENT ON TABLE owners IS 'Entities (organizations or individuals) that own Types, Enums, and Formats. Sourced from definitions/owners.yaml.';
COMMENT ON COLUMN owners.owners_id IS 'Primary key (auto-synthesized: Owners had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN owners.name IS 'Owner identifier slug. Example: ''gridworks-energy''. Acts as the primary key.';
COMMENT ON COLUMN owners.owner_type IS 'Either ''organization'' or ''individual''.';
COMMENT ON COLUMN owners.contact IS 'Primary contact email.';
COMMENT ON COLUMN owners.website IS 'Owner''s website URL.';
COMMENT ON COLUMN owners.github IS 'Owner''s GitHub URL (optional).';
COMMENT ON COLUMN owners.organization IS 'Full legal/organization name.';
COMMENT ON COLUMN owners.description IS 'Free-text description of the owner''s domain or focus.';
COMMENT ON COLUMN owners.support_policy IS 'How users get support from this owner.';
COMMENT ON COLUMN owners.license IS 'License under which the owner''s contributions are published (e.g. ''MIT'').';

-- ----------------------------------------------------------------------------
-- Formats: JSON-Schema string formats with regex patterns and length bounds. Sourced from definitions/formats/*.yaml. Formats are not versioned.
-- ----------------------------------------------------------------------------
CREATE TABLE formats (
  formats_id                          TEXT                 PRIMARY KEY,         -- Primary key (auto-synthesized: Formats had no field named 'Id' or ending in 'Id').
  name                                TEXT                ,                     -- Format identifier slug. Example: 'uuid4.str'. Acts as the primary key.
  owner                               TEXT                ,                     -- Owner of this format.
  schema_url                          TEXT                ,                     -- Schema URL from JSON-Schema $id.
  title                               TEXT                ,                     -- Human-readable title.
  description                         TEXT                ,                     -- Free-text description of the format.
  replaced_by                         TEXT                ,                     -- Optional pointer to another Format that retires this one. If non-null, this format has been retired in favor of the named successor. Words are immutable and may only be retired at the registry level (not per-version, per-value, or per-attribute).
  pattern                             TEXT                ,                     -- Regex pattern that valid values must match.
  min_length                          INTEGER             ,                     -- Minimum string length, if constrained.
  max_length                          INTEGER             ,                     -- Maximum string length, if constrained.
  json_schema_format                  TEXT                ,                     -- JSON-Schema 'format' keyword if present (e.g. 'date-time', 'email').
  created                             TIMESTAMPTZ         ,                     -- Created timestamp from registry.yaml.
  raw_json                            TEXT                                      -- Escape hatch: any unmodeled JSON-Schema fields, serialized as JSON string.
);
COMMENT ON TABLE formats IS 'JSON-Schema string formats with regex patterns and length bounds. Sourced from definitions/formats/*.yaml. Formats are not versioned.';
COMMENT ON COLUMN formats.formats_id IS 'Primary key (auto-synthesized: Formats had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN formats.name IS 'Format identifier slug. Example: ''uuid4.str''. Acts as the primary key.';
COMMENT ON COLUMN formats.owner IS 'Owner of this format.';
COMMENT ON COLUMN formats.schema_url IS 'Schema URL from JSON-Schema $id.';
COMMENT ON COLUMN formats.title IS 'Human-readable title.';
COMMENT ON COLUMN formats.description IS 'Free-text description of the format.';
COMMENT ON COLUMN formats.replaced_by IS 'Optional pointer to another Format that retires this one. If non-null, this format has been retired in favor of the named successor. Words are immutable and may only be retired at the registry level (not per-version, per-value, or per-attribute).';
COMMENT ON COLUMN formats.pattern IS 'Regex pattern that valid values must match.';
COMMENT ON COLUMN formats.min_length IS 'Minimum string length, if constrained.';
COMMENT ON COLUMN formats.max_length IS 'Maximum string length, if constrained.';
COMMENT ON COLUMN formats.json_schema_format IS 'JSON-Schema ''format'' keyword if present (e.g. ''date-time'', ''email'').';
COMMENT ON COLUMN formats.created IS 'Created timestamp from registry.yaml.';
COMMENT ON COLUMN formats.raw_json IS 'Escape hatch: any unmodeled JSON-Schema fields, serialized as JSON string.';

-- ----------------------------------------------------------------------------
-- FormatExamples: Per-format examples and counterexamples (with order preserved). Sourced from format YAML 'examples' and 'counterexamples' arrays.
-- ----------------------------------------------------------------------------
CREATE TABLE format_examples (
  format_examples_id                  TEXT                 PRIMARY KEY,         -- Primary key (auto-synthesized: FormatExamples had no field named 'Id' or ending in 'Id').
  format                              TEXT                ,                     -- Foreign key to the parent Format.
  idx                                 INTEGER             ,                     -- Preserves YAML ordering (0-indexed within examples or counterexamples).
  is_counter                          BOOLEAN             ,                     -- True if this is a counterexample (must NOT match), false if a positive example.
  value                               TEXT                ,                     -- The example string itself.
  description                         TEXT                                      -- Optional description (e.g. YAML inline comment).
);
COMMENT ON TABLE format_examples IS 'Per-format examples and counterexamples (with order preserved). Sourced from format YAML ''examples'' and ''counterexamples'' arrays.';
COMMENT ON COLUMN format_examples.format_examples_id IS 'Primary key (auto-synthesized: FormatExamples had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN format_examples.format IS 'Foreign key to the parent Format.';
COMMENT ON COLUMN format_examples.idx IS 'Preserves YAML ordering (0-indexed within examples or counterexamples).';
COMMENT ON COLUMN format_examples.is_counter IS 'True if this is a counterexample (must NOT match), false if a positive example.';
COMMENT ON COLUMN format_examples.value IS 'The example string itself.';
COMMENT ON COLUMN format_examples.description IS 'Optional description (e.g. YAML inline comment).';

-- ----------------------------------------------------------------------------
-- Enums: Top-level enum definitions (name-level). Versioned enums have multiple EnumVersions; literal enums have one. Sourced from definitions/registry.yaml + definitions/enums/.
-- ----------------------------------------------------------------------------
CREATE TABLE enums (
  enums_id                            TEXT                 PRIMARY KEY,         -- Primary key (auto-synthesized: Enums had no field named 'Id' or ending in 'Id').
  name                                TEXT                ,                     -- Enum identifier slug. Example: 'gw1.actor.class'. Acts as the primary key.
  owner                               TEXT                ,                     -- Owner of this enum.
  enum_type                           TEXT                ,                     -- Either 'versioned' (additive-only multi-version) or 'literal' (single immutable version).
  value_type                          TEXT                ,                     -- JSON Schema datatype of the enum's symbols. If present, SHALL be 'integer' and version YAML files SHALL have type: integer. If null, the enum SHALL be treated as string-valued.
  description                         TEXT                ,                     -- Name-level description (registry-level).
  replaced_by                         TEXT                ,                     -- Optional pointer to another Enum that retires this one. If non-null, this enum has been retired in favor of the named successor. Words are immutable and may only be retired at the registry level (not per-version, per-value, or per-attribute).
  raw_json                            TEXT                                      -- Escape hatch: any unmodeled YAML keys (e.g., x-gridworks extended_description). JSON-encoded.
);
COMMENT ON TABLE enums IS 'Top-level enum definitions (name-level). Versioned enums have multiple EnumVersions; literal enums have one. Sourced from definitions/registry.yaml + definitions/enums/.';
COMMENT ON COLUMN enums.enums_id IS 'Primary key (auto-synthesized: Enums had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN enums.name IS 'Enum identifier slug. Example: ''gw1.actor.class''. Acts as the primary key.';
COMMENT ON COLUMN enums.owner IS 'Owner of this enum.';
COMMENT ON COLUMN enums.enum_type IS 'Either ''versioned'' (additive-only multi-version) or ''literal'' (single immutable version).';
COMMENT ON COLUMN enums.value_type IS 'JSON Schema datatype of the enum''s symbols. If present, SHALL be ''integer'' and version YAML files SHALL have type: integer. If null, the enum SHALL be treated as string-valued.';
COMMENT ON COLUMN enums.description IS 'Name-level description (registry-level).';
COMMENT ON COLUMN enums.replaced_by IS 'Optional pointer to another Enum that retires this one. If non-null, this enum has been retired in favor of the named successor. Words are immutable and may only be retired at the registry level (not per-version, per-value, or per-attribute).';
COMMENT ON COLUMN enums.raw_json IS 'Escape hatch: any unmodeled YAML keys (e.g., x-gridworks extended_description). JSON-encoded.';

-- ----------------------------------------------------------------------------
-- EnumVersions: Specific versions of an enum. Each enum can have multiple versions (e.g. gw1.actor.class has versions 009, 010, 011).
-- ----------------------------------------------------------------------------
CREATE TABLE enum_versions (
  enum_versions_id                    TEXT                 PRIMARY KEY,         -- Primary key (auto-synthesized: EnumVersions had no field named 'Id' or ending in 'Id').
  enum                                TEXT                ,                     -- Foreign key to the parent Enum.
  version                             TEXT                ,                     -- Three-digit version string. Example: '007'.
  schema_url                          TEXT                ,                     -- Schema URL from JSON-Schema $id.
  title                               TEXT                ,                     -- Human-readable title.
  description                         TEXT                ,                     -- Version-specific description.
  default_symbol                      TEXT                ,                     -- The default symbol value for this version.
  status                              TEXT                ,                     -- Lifecycle status (e.g. 'active', 'deprecated').
  created                             TIMESTAMPTZ         ,                     -- Creation timestamp from registry.yaml.
  raw_json                            TEXT                                      -- Escape hatch: any unmodeled YAML keys (e.g., type: integer for non-string enums, x-gridworks extended_description). JSON-encoded.
);
COMMENT ON TABLE enum_versions IS 'Specific versions of an enum. Each enum can have multiple versions (e.g. gw1.actor.class has versions 009, 010, 011).';
COMMENT ON COLUMN enum_versions.enum_versions_id IS 'Primary key (auto-synthesized: EnumVersions had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN enum_versions.enum IS 'Foreign key to the parent Enum.';
COMMENT ON COLUMN enum_versions.version IS 'Three-digit version string. Example: ''007''.';
COMMENT ON COLUMN enum_versions.schema_url IS 'Schema URL from JSON-Schema $id.';
COMMENT ON COLUMN enum_versions.title IS 'Human-readable title.';
COMMENT ON COLUMN enum_versions.description IS 'Version-specific description.';
COMMENT ON COLUMN enum_versions.default_symbol IS 'The default symbol value for this version.';
COMMENT ON COLUMN enum_versions.status IS 'Lifecycle status (e.g. ''active'', ''deprecated'').';
COMMENT ON COLUMN enum_versions.created IS 'Creation timestamp from registry.yaml.';
COMMENT ON COLUMN enum_versions.raw_json IS 'Escape hatch: any unmodeled YAML keys (e.g., type: integer for non-string enums, x-gridworks extended_description). JSON-encoded.';

-- ----------------------------------------------------------------------------
-- EnumValues: Individual symbol values within an EnumVersion (with order preserved and per-symbol descriptions).
-- ----------------------------------------------------------------------------
CREATE TABLE enum_values (
  enum_values_id                      TEXT                 PRIMARY KEY,         -- Primary key (auto-synthesized: EnumValues had no field named 'Id' or ending in 'Id').
  enum_version                        TEXT                ,                     -- Foreign key to the parent EnumVersion.
  symbol                              TEXT                ,                     -- The literal symbol value, e.g. 'Power'.
  idx                                 INTEGER             ,                     -- Preserves YAML ordering of symbols.
  description                         TEXT                                      -- Per-symbol description from value_descriptions map.
);
COMMENT ON TABLE enum_values IS 'Individual symbol values within an EnumVersion (with order preserved and per-symbol descriptions).';
COMMENT ON COLUMN enum_values.enum_values_id IS 'Primary key (auto-synthesized: EnumValues had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN enum_values.enum_version IS 'Foreign key to the parent EnumVersion.';
COMMENT ON COLUMN enum_values.symbol IS 'The literal symbol value, e.g. ''Power''.';
COMMENT ON COLUMN enum_values.idx IS 'Preserves YAML ordering of symbols.';
COMMENT ON COLUMN enum_values.description IS 'Per-symbol description from value_descriptions map.';

-- ----------------------------------------------------------------------------
-- Types: Top-level type definitions (name-level). Each type can have multiple TypeVersions. Sourced from definitions/registry.yaml + definitions/types/.
-- ----------------------------------------------------------------------------
CREATE TABLE types (
  types_id                            TEXT                 PRIMARY KEY,         -- Primary key (auto-synthesized: Types had no field named 'Id' or ending in 'Id').
  name                                TEXT                ,                     -- Type identifier slug. Example: 'report'. Acts as the primary key.
  owner                               TEXT                ,                     -- Owner of this type.
  title                               TEXT                ,                     -- Name-level title.
  description                         TEXT                ,                     -- Name-level description.
  replaced_by                         TEXT                ,                     -- Optional pointer to another Type that retires this one. If non-null, this type has been retired in favor of the named successor. Words are immutable and may only be retired at the registry level (not per-version, per-value, or per-attribute).
  python_class_name                   TEXT                ,                     -- Tier-2 placeholder: ODXML-derived Python class name (populated when ODXML data absorbs in).
  make_data_class                     BOOLEAN             ,                     -- Tier-2 placeholder: ODXML invariant.
  is_cac                              BOOLEAN             ,                     -- Tier-2 placeholder: ODXML invariant (component access control marker).
  is_component                        BOOLEAN                                   -- Tier-2 placeholder: ODXML invariant.
);
COMMENT ON TABLE types IS 'Top-level type definitions (name-level). Each type can have multiple TypeVersions. Sourced from definitions/registry.yaml + definitions/types/.';
COMMENT ON COLUMN types.types_id IS 'Primary key (auto-synthesized: Types had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN types.name IS 'Type identifier slug. Example: ''report''. Acts as the primary key.';
COMMENT ON COLUMN types.owner IS 'Owner of this type.';
COMMENT ON COLUMN types.title IS 'Name-level title.';
COMMENT ON COLUMN types.description IS 'Name-level description.';
COMMENT ON COLUMN types.replaced_by IS 'Optional pointer to another Type that retires this one. If non-null, this type has been retired in favor of the named successor. Words are immutable and may only be retired at the registry level (not per-version, per-value, or per-attribute).';
COMMENT ON COLUMN types.python_class_name IS 'Tier-2 placeholder: ODXML-derived Python class name (populated when ODXML data absorbs in).';
COMMENT ON COLUMN types.make_data_class IS 'Tier-2 placeholder: ODXML invariant.';
COMMENT ON COLUMN types.is_cac IS 'Tier-2 placeholder: ODXML invariant (component access control marker).';
COMMENT ON COLUMN types.is_component IS 'Tier-2 placeholder: ODXML invariant.';

-- ----------------------------------------------------------------------------
-- TypeVersions: Specific versions of a type. Each declares its JSON-Schema shape. Versions follow a 3-digit suffix in the YAML files.
-- ----------------------------------------------------------------------------
CREATE TABLE type_versions (
  type_versions_id                    TEXT                 PRIMARY KEY,         -- Primary key (auto-synthesized: TypeVersions had no field named 'Id' or ending in 'Id').
  type                                TEXT                ,                     -- Foreign key to the parent Type.
  version                             TEXT                ,                     -- Three-digit version string. Example: '002'.
  schema_url                          TEXT                ,                     -- Schema URL from JSON-Schema $id.
  title                               TEXT                ,                     -- Human-readable title.
  description                         TEXT                ,                     -- Version-specific description.
  extra_allowed                       BOOLEAN             ,                     -- From JSON-Schema additionalProperties (true=open, false=closed).
  status                              TEXT                ,                     -- Lifecycle status.
  created                             TIMESTAMPTZ         ,                     -- Creation timestamp.
  raw_json                            TEXT                                      -- Escape hatch: unmodeled top-level JSON-Schema fields (if/then/else, conditionals, etc.).
);
COMMENT ON TABLE type_versions IS 'Specific versions of a type. Each declares its JSON-Schema shape. Versions follow a 3-digit suffix in the YAML files.';
COMMENT ON COLUMN type_versions.type_versions_id IS 'Primary key (auto-synthesized: TypeVersions had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN type_versions.type IS 'Foreign key to the parent Type.';
COMMENT ON COLUMN type_versions.version IS 'Three-digit version string. Example: ''002''.';
COMMENT ON COLUMN type_versions.schema_url IS 'Schema URL from JSON-Schema $id.';
COMMENT ON COLUMN type_versions.title IS 'Human-readable title.';
COMMENT ON COLUMN type_versions.description IS 'Version-specific description.';
COMMENT ON COLUMN type_versions.extra_allowed IS 'From JSON-Schema additionalProperties (true=open, false=closed).';
COMMENT ON COLUMN type_versions.status IS 'Lifecycle status.';
COMMENT ON COLUMN type_versions.created IS 'Creation timestamp.';
COMMENT ON COLUMN type_versions.raw_json IS 'Escape hatch: unmodeled top-level JSON-Schema fields (if/then/else, conditionals, etc.).';

-- ----------------------------------------------------------------------------
-- TypeAttributes: The shape-of-record for every property declared on a TypeVersion. Polymorphic via mutually-exclusive FK columns: at most one of FormatRef / EnumVersionRef / SubTypeVersionRef / HelperRef is non-null per row.
-- ----------------------------------------------------------------------------
CREATE TABLE type_attributes (
  type_attributes_id                  TEXT                 PRIMARY KEY,         -- Primary key (auto-synthesized: TypeAttributes had no field named 'Id' or ending in 'Id').
  type_version                        TEXT                ,                     -- Foreign key to the owning TypeVersion.
  attribute_name                      TEXT                ,                     -- Property key in the JSON-Schema.
  idx                                 INTEGER             ,                     -- Preserves YAML ordering of properties.
  description                         TEXT                ,                     -- Per-attribute description from JSON-Schema.
  "default"                           TEXT                ,                     -- JSON-encoded default value for this attribute (e.g., '"002"', '12', 'false', '1.0', 'null'). Mirrors the JSON Schema 'default:' keyword. Encode as JSON string for typing-uniformity (matches TypeUpgradeOps.LiteralValue convention).
  is_required                         BOOLEAN             ,                     -- Derived from the parent TypeVersion's 'required' array.
  is_list                             BOOLEAN             ,                     -- True if attribute is type=array. Refs then describe the item type.
  primitive_type                      TEXT                ,                     -- Primitive JSON type when none of the *Ref columns apply: string, integer, number, boolean, null.
  format_ref                          TEXT                ,                     -- FK to a Format, when this attribute uses a $ref to /formats/X.
  enum_version_ref                    TEXT                ,                     -- FK to an EnumVersion, when this attribute uses a $ref to /enums/X/NNN.
  sub_type_version_ref                TEXT                ,                     -- FK to another TypeVersion, when this attribute uses a $ref to /types/X/NNN.
  helper_ref                          TEXT                ,                     -- FK to a TypeHelper, when this attribute is an inline-nested object auto-promoted to a helper.
  raw_json                            TEXT                                      -- Escape hatch: unmodeled JSON-Schema specifics, including oneOf bodies (v1 parking lot for n=1 cases).
);
COMMENT ON TABLE type_attributes IS 'The shape-of-record for every property declared on a TypeVersion. Polymorphic via mutually-exclusive FK columns: at most one of FormatRef / EnumVersionRef / SubTypeVersionRef / HelperRef is non-null per row.';
COMMENT ON COLUMN type_attributes.type_attributes_id IS 'Primary key (auto-synthesized: TypeAttributes had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN type_attributes.type_version IS 'Foreign key to the owning TypeVersion.';
COMMENT ON COLUMN type_attributes.attribute_name IS 'Property key in the JSON-Schema.';
COMMENT ON COLUMN type_attributes.idx IS 'Preserves YAML ordering of properties.';
COMMENT ON COLUMN type_attributes.description IS 'Per-attribute description from JSON-Schema.';
COMMENT ON COLUMN type_attributes."default" IS 'JSON-encoded default value for this attribute (e.g., ''"002"'', ''12'', ''false'', ''1.0'', ''null''). Mirrors the JSON Schema ''default:'' keyword. Encode as JSON string for typing-uniformity (matches TypeUpgradeOps.LiteralValue convention).';
COMMENT ON COLUMN type_attributes.is_required IS 'Derived from the parent TypeVersion''s ''required'' array.';
COMMENT ON COLUMN type_attributes.is_list IS 'True if attribute is type=array. Refs then describe the item type.';
COMMENT ON COLUMN type_attributes.primitive_type IS 'Primitive JSON type when none of the *Ref columns apply: string, integer, number, boolean, null.';
COMMENT ON COLUMN type_attributes.format_ref IS 'FK to a Format, when this attribute uses a $ref to /formats/X.';
COMMENT ON COLUMN type_attributes.enum_version_ref IS 'FK to an EnumVersion, when this attribute uses a $ref to /enums/X/NNN.';
COMMENT ON COLUMN type_attributes.sub_type_version_ref IS 'FK to another TypeVersion, when this attribute uses a $ref to /types/X/NNN.';
COMMENT ON COLUMN type_attributes.helper_ref IS 'FK to a TypeHelper, when this attribute is an inline-nested object auto-promoted to a helper.';
COMMENT ON COLUMN type_attributes.raw_json IS 'Escape hatch: unmodeled JSON-Schema specifics, including oneOf bodies (v1 parking lot for n=1 cases).';

-- ----------------------------------------------------------------------------
-- TypeExamples: Per-TypeVersion full-instance examples (with order preserved). Sourced from JSON-Schema 'examples' arrays.
-- ----------------------------------------------------------------------------
CREATE TABLE type_examples (
  type_examples_id                    TEXT                 PRIMARY KEY,         -- Primary key (auto-synthesized: TypeExamples had no field named 'Id' or ending in 'Id').
  type_version                        TEXT                ,                     -- Foreign key to the parent TypeVersion.
  idx                                 INTEGER             ,                     -- Preserves YAML ordering.
  example_json                        TEXT                                      -- Full instance example, serialized as JSON string.
);
COMMENT ON TABLE type_examples IS 'Per-TypeVersion full-instance examples (with order preserved). Sourced from JSON-Schema ''examples'' arrays.';
COMMENT ON COLUMN type_examples.type_examples_id IS 'Primary key (auto-synthesized: TypeExamples had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN type_examples.type_version IS 'Foreign key to the parent TypeVersion.';
COMMENT ON COLUMN type_examples.idx IS 'Preserves YAML ordering.';
COMMENT ON COLUMN type_examples.example_json IS 'Full instance example, serialized as JSON string.';

-- ----------------------------------------------------------------------------
-- TypeAxioms: Per-TypeVersion axioms (numbered invariants stated in natural language). Sourced from x-gridworks.axioms in YAML.
-- ----------------------------------------------------------------------------
CREATE TABLE type_axioms (
  type_axioms_id                      TEXT                 PRIMARY KEY,         -- Primary key (auto-synthesized: TypeAxioms had no field named 'Id' or ending in 'Id').
  type_version                        TEXT                ,                     -- Foreign key to the parent TypeVersion.
  number                              INTEGER             ,                     -- Axiom number from YAML.
  axiom_name                          TEXT                ,                     -- Axiom name from YAML.
  statement                           TEXT                                      -- Axiom statement (the natural-language invariant).
);
COMMENT ON TABLE type_axioms IS 'Per-TypeVersion axioms (numbered invariants stated in natural language). Sourced from x-gridworks.axioms in YAML.';
COMMENT ON COLUMN type_axioms.type_axioms_id IS 'Primary key (auto-synthesized: TypeAxioms had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN type_axioms.type_version IS 'Foreign key to the parent TypeVersion.';
COMMENT ON COLUMN type_axioms.number IS 'Axiom number from YAML.';
COMMENT ON COLUMN type_axioms.axiom_name IS 'Axiom name from YAML.';
COMMENT ON COLUMN type_axioms.statement IS 'Axiom statement (the natural-language invariant).';

-- ----------------------------------------------------------------------------
-- TypeHelpers: Non-versioned reusable subtypes auto-promoted from inline nested objects (array items, oneOf branches). Synthesized at migration time. Origin metadata preserves provenance for round-trip YAML emission.
-- ----------------------------------------------------------------------------
CREATE TABLE type_helpers (
  type_helpers_id                     TEXT                 PRIMARY KEY,         -- Primary key (auto-synthesized: TypeHelpers had no field named 'Id' or ending in 'Id').
  name                                TEXT                ,                     -- Synthesized helper name. Example: 'scada.control.capabilities.RelayNode'. Acts as the primary key.
  title                               TEXT                ,                     -- From inline 'description' if present.
  description                         TEXT                ,                     -- Description of the helper.
  extra_allowed                       BOOLEAN             ,                     -- From inline additionalProperties.
  origin_type_version                 TEXT                ,                     -- The TypeVersion whose YAML body originally introduced this helper.
  origin_path                         TEXT                                      -- JSON-Pointer-ish path within origin (e.g. '/properties/RelayNodes/items') — used to re-inline on YAML emit.
);
COMMENT ON TABLE type_helpers IS 'Non-versioned reusable subtypes auto-promoted from inline nested objects (array items, oneOf branches). Synthesized at migration time. Origin metadata preserves provenance for round-trip YAML emission.';
COMMENT ON COLUMN type_helpers.type_helpers_id IS 'Primary key (auto-synthesized: TypeHelpers had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN type_helpers.name IS 'Synthesized helper name. Example: ''scada.control.capabilities.RelayNode''. Acts as the primary key.';
COMMENT ON COLUMN type_helpers.title IS 'From inline ''description'' if present.';
COMMENT ON COLUMN type_helpers.description IS 'Description of the helper.';
COMMENT ON COLUMN type_helpers.extra_allowed IS 'From inline additionalProperties.';
COMMENT ON COLUMN type_helpers.origin_type_version IS 'The TypeVersion whose YAML body originally introduced this helper.';
COMMENT ON COLUMN type_helpers.origin_path IS 'JSON-Pointer-ish path within origin (e.g. ''/properties/RelayNodes/items'') — used to re-inline on YAML emit.';

-- ----------------------------------------------------------------------------
-- TypeHelperAttributes: Properties of a TypeHelper. Same shape as TypeAttributes minus the oneOf machinery, since helpers are not versioned.
-- ----------------------------------------------------------------------------
CREATE TABLE type_helper_attributes (
  type_helper_attributes_id           TEXT                 PRIMARY KEY,         -- Primary key (auto-synthesized: TypeHelperAttributes had no field named 'Id' or ending in 'Id').
  type_helper                         TEXT                ,                     -- Foreign key to the parent TypeHelper.
  attribute_name                      TEXT                ,                     -- Property key.
  idx                                 INTEGER             ,                     -- Preserves YAML ordering.
  description                         TEXT                ,                     -- Per-attribute description.
  is_required                         BOOLEAN             ,                     -- From inline 'required' array.
  is_list                             BOOLEAN             ,                     -- True if type=array.
  primitive_type                      TEXT                ,                     -- Primitive JSON type when none of the *Ref columns apply.
  format_ref                          TEXT                ,                     -- FK to a Format, if this attribute references one.
  enum_version_ref                    TEXT                ,                     -- FK to an EnumVersion, if this attribute references one.
  sub_type_version_ref                TEXT                ,                     -- FK to a TypeVersion, if this attribute references one.
  helper_ref                          TEXT                ,                     -- FK to another TypeHelper (supports nested helpers).
  raw_json                            TEXT                                      -- Escape hatch for unmodeled JSON-Schema specifics.
);
COMMENT ON TABLE type_helper_attributes IS 'Properties of a TypeHelper. Same shape as TypeAttributes minus the oneOf machinery, since helpers are not versioned.';
COMMENT ON COLUMN type_helper_attributes.type_helper_attributes_id IS 'Primary key (auto-synthesized: TypeHelperAttributes had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN type_helper_attributes.type_helper IS 'Foreign key to the parent TypeHelper.';
COMMENT ON COLUMN type_helper_attributes.attribute_name IS 'Property key.';
COMMENT ON COLUMN type_helper_attributes.idx IS 'Preserves YAML ordering.';
COMMENT ON COLUMN type_helper_attributes.description IS 'Per-attribute description.';
COMMENT ON COLUMN type_helper_attributes.is_required IS 'From inline ''required'' array.';
COMMENT ON COLUMN type_helper_attributes.is_list IS 'True if type=array.';
COMMENT ON COLUMN type_helper_attributes.primitive_type IS 'Primitive JSON type when none of the *Ref columns apply.';
COMMENT ON COLUMN type_helper_attributes.format_ref IS 'FK to a Format, if this attribute references one.';
COMMENT ON COLUMN type_helper_attributes.enum_version_ref IS 'FK to an EnumVersion, if this attribute references one.';
COMMENT ON COLUMN type_helper_attributes.sub_type_version_ref IS 'FK to a TypeVersion, if this attribute references one.';
COMMENT ON COLUMN type_helper_attributes.helper_ref IS 'FK to another TypeHelper (supports nested helpers).';
COMMENT ON COLUMN type_helper_attributes.raw_json IS 'Escape hatch for unmodeled JSON-Schema specifics.';

-- ----------------------------------------------------------------------------
-- Projections: Named, deterministic enum-to-enum (or value-to-value) mappings used by AddProjected upgrade ops. Today: SpaceheatTelemetryQuantityProjection, Gw1UnitQuantityProjection.
-- ----------------------------------------------------------------------------
CREATE TABLE projections (
  projections_id                      TEXT                 PRIMARY KEY,         -- Primary key (auto-synthesized: Projections had no field named 'Id' or ending in 'Id').
  name                                TEXT                ,                     -- Projection name. Example: 'SpaceheatTelemetryQuantityProjection'. Acts as the primary key.
  description                         TEXT                ,                     -- Description of what the projection computes.
  from_enum_version                   TEXT                ,                     -- Source enum version.
  to_enum_version                     TEXT                ,                     -- Target enum version.
  raw_script                          TEXT                                      -- Populated only if the projection isn't a flat lookup (escape hatch).
);
COMMENT ON TABLE projections IS 'Named, deterministic enum-to-enum (or value-to-value) mappings used by AddProjected upgrade ops. Today: SpaceheatTelemetryQuantityProjection, Gw1UnitQuantityProjection.';
COMMENT ON COLUMN projections.projections_id IS 'Primary key (auto-synthesized: Projections had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN projections.name IS 'Projection name. Example: ''SpaceheatTelemetryQuantityProjection''. Acts as the primary key.';
COMMENT ON COLUMN projections.description IS 'Description of what the projection computes.';
COMMENT ON COLUMN projections.from_enum_version IS 'Source enum version.';
COMMENT ON COLUMN projections.to_enum_version IS 'Target enum version.';
COMMENT ON COLUMN projections.raw_script IS 'Populated only if the projection isn''t a flat lookup (escape hatch).';

-- ----------------------------------------------------------------------------
-- ProjectionMappings: Per-symbol mappings for flat-lookup Projections. Empty when the parent Projection uses RawScript.
-- ----------------------------------------------------------------------------
CREATE TABLE projection_mappings (
  projection_mappings_id              TEXT                 PRIMARY KEY,         -- Primary key (auto-synthesized: ProjectionMappings had no field named 'Id' or ending in 'Id').
  projection                          TEXT                ,                     -- Foreign key to the parent Projection.
  from_symbol                         TEXT                ,                     -- Source enum symbol.
  to_symbol                           TEXT                ,                     -- Target enum symbol.
  description                         TEXT                                      -- Optional per-mapping description.
);
COMMENT ON TABLE projection_mappings IS 'Per-symbol mappings for flat-lookup Projections. Empty when the parent Projection uses RawScript.';
COMMENT ON COLUMN projection_mappings.projection_mappings_id IS 'Primary key (auto-synthesized: ProjectionMappings had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN projection_mappings.projection IS 'Foreign key to the parent Projection.';
COMMENT ON COLUMN projection_mappings.from_symbol IS 'Source enum symbol.';
COMMENT ON COLUMN projection_mappings.to_symbol IS 'Target enum symbol.';
COMMENT ON COLUMN projection_mappings.description IS 'Optional per-mapping description.';

-- ----------------------------------------------------------------------------
-- TypeUpgrades: One row per ordered version pair (N, N+1) for a given type. Mirrors src/sema/runtime/types/old_versions/<type>_<NNN>.py.upgrade() methods.
-- ----------------------------------------------------------------------------
CREATE TABLE type_upgrades (
  type_upgrades_id                    TEXT                 PRIMARY KEY,         -- Primary key (auto-synthesized: TypeUpgrades had no field named 'Id' or ending in 'Id').
  from_type_version                   TEXT                ,                     -- Source TypeVersion.
  to_type_version                     TEXT                ,                     -- Target TypeVersion.
  description                         TEXT                ,                     -- Description (typically the docstring summary from the .py method).
  raw_script                          TEXT                                      -- Whole-method escape hatch when no clean op decomposition is possible. Prefer per-op RawScript on TypeUpgradeOps.
);
COMMENT ON TABLE type_upgrades IS 'One row per ordered version pair (N, N+1) for a given type. Mirrors src/sema/runtime/types/old_versions/<type>_<NNN>.py.upgrade() methods.';
COMMENT ON COLUMN type_upgrades.type_upgrades_id IS 'Primary key (auto-synthesized: TypeUpgrades had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN type_upgrades.from_type_version IS 'Source TypeVersion.';
COMMENT ON COLUMN type_upgrades.to_type_version IS 'Target TypeVersion.';
COMMENT ON COLUMN type_upgrades.description IS 'Description (typically the docstring summary from the .py method).';
COMMENT ON COLUMN type_upgrades.raw_script IS 'Whole-method escape hatch when no clean op decomposition is possible. Prefer per-op RawScript on TypeUpgradeOps.';

-- ----------------------------------------------------------------------------
-- TypeUpgradeOps: Atomic operations within a TypeUpgrade. Most upgrades decompose into 1-4 ops. OpKind controls semantics (vocabulary: AddOptional, AddWithDefault, Remove, RequireToOptional, OptionalToRequire, EnumVersionBump, CoerceToEnum, UpgradeChild, UpgradeChildIf, UpgradeListItems, UpgradeListItemsIf, AddProjected, Custom).
-- ----------------------------------------------------------------------------
CREATE TABLE type_upgrade_ops (
  type_upgrade_ops_id                 TEXT                 PRIMARY KEY,         -- Primary key (auto-synthesized: TypeUpgradeOps had no field named 'Id' or ending in 'Id').
  type_upgrade                        TEXT                ,                     -- Foreign key to the parent TypeUpgrade.
  idx                                 INTEGER             ,                     -- Execution order within the upgrade.
  op_kind                             TEXT                ,                     -- Op vocabulary: AddOptional, AddWithDefault, Remove, RequireToOptional, OptionalToRequire, EnumVersionBump, CoerceToEnum, UpgradeChild, UpgradeChildIf, UpgradeListItems, UpgradeListItemsIf, AddProjected, Custom.
  field_name                          TEXT                ,                     -- The attribute name being touched (most ops).
  literal_value                       TEXT                ,                     -- JSON-encoded literal default (AddWithDefault) or source field name (AddProjected).
  from_version                        TEXT                ,                     -- Source version for conditional upgrades (UpgradeChildIf, UpgradeListItemsIf).
  to_version                          TEXT                ,                     -- Target version for explicit version bumps.
  enum_version_ref                    TEXT                ,                     -- FK for enum-related ops (EnumVersionBump, CoerceToEnum).
  projection_ref                      TEXT                ,                     -- FK for AddProjected ops.
  raw_script                          TEXT                ,                     -- Per-op Python escape hatch for Custom ops. Snippet runs in scope of `self` and `data` dict.
  description                         TEXT                                      -- Optional op-level description.
);
COMMENT ON TABLE type_upgrade_ops IS 'Atomic operations within a TypeUpgrade. Most upgrades decompose into 1-4 ops. OpKind controls semantics (vocabulary: AddOptional, AddWithDefault, Remove, RequireToOptional, OptionalToRequire, EnumVersionBump, CoerceToEnum, UpgradeChild, UpgradeChildIf, UpgradeListItems, UpgradeListItemsIf, AddProjected, Custom).';
COMMENT ON COLUMN type_upgrade_ops.type_upgrade_ops_id IS 'Primary key (auto-synthesized: TypeUpgradeOps had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN type_upgrade_ops.type_upgrade IS 'Foreign key to the parent TypeUpgrade.';
COMMENT ON COLUMN type_upgrade_ops.idx IS 'Execution order within the upgrade.';
COMMENT ON COLUMN type_upgrade_ops.op_kind IS 'Op vocabulary: AddOptional, AddWithDefault, Remove, RequireToOptional, OptionalToRequire, EnumVersionBump, CoerceToEnum, UpgradeChild, UpgradeChildIf, UpgradeListItems, UpgradeListItemsIf, AddProjected, Custom.';
COMMENT ON COLUMN type_upgrade_ops.field_name IS 'The attribute name being touched (most ops).';
COMMENT ON COLUMN type_upgrade_ops.literal_value IS 'JSON-encoded literal default (AddWithDefault) or source field name (AddProjected).';
COMMENT ON COLUMN type_upgrade_ops.from_version IS 'Source version for conditional upgrades (UpgradeChildIf, UpgradeListItemsIf).';
COMMENT ON COLUMN type_upgrade_ops.to_version IS 'Target version for explicit version bumps.';
COMMENT ON COLUMN type_upgrade_ops.enum_version_ref IS 'FK for enum-related ops (EnumVersionBump, CoerceToEnum).';
COMMENT ON COLUMN type_upgrade_ops.projection_ref IS 'FK for AddProjected ops.';
COMMENT ON COLUMN type_upgrade_ops.raw_script IS 'Per-op Python escape hatch for Custom ops. Snippet runs in scope of `self` and `data` dict.';
COMMENT ON COLUMN type_upgrade_ops.description IS 'Optional op-level description.';

-- ----------------------------------------------------------------------------
-- EnumUpgrades: Mirror of TypeUpgrades for enum value renames or splits when name preservation breaks. Today's 5 multi-version enums all preserved names, so this table starts empty.
-- ----------------------------------------------------------------------------
CREATE TABLE enum_upgrades (
  enum_upgrades_id                    TEXT                 PRIMARY KEY,         -- Primary key (auto-synthesized: EnumUpgrades had no field named 'Id' or ending in 'Id').
  from_enum_version                   TEXT                ,                     -- Source EnumVersion.
  to_enum_version                     TEXT                ,                     -- Target EnumVersion.
  description                         TEXT                ,                     -- Description of the enum upgrade.
  raw_script                          TEXT                                      -- Whole-upgrade escape hatch.
);
COMMENT ON TABLE enum_upgrades IS 'Mirror of TypeUpgrades for enum value renames or splits when name preservation breaks. Today''s 5 multi-version enums all preserved names, so this table starts empty.';
COMMENT ON COLUMN enum_upgrades.enum_upgrades_id IS 'Primary key (auto-synthesized: EnumUpgrades had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN enum_upgrades.from_enum_version IS 'Source EnumVersion.';
COMMENT ON COLUMN enum_upgrades.to_enum_version IS 'Target EnumVersion.';
COMMENT ON COLUMN enum_upgrades.description IS 'Description of the enum upgrade.';
COMMENT ON COLUMN enum_upgrades.raw_script IS 'Whole-upgrade escape hatch.';

-- ----------------------------------------------------------------------------
-- EnumUpgradeMappings: Per-symbol value renames for an EnumUpgrade. Empty when the parent EnumUpgrade preserves all names.
-- ----------------------------------------------------------------------------
CREATE TABLE enum_upgrade_mappings (
  enum_upgrade_mappings_id            TEXT                 PRIMARY KEY,         -- Primary key (auto-synthesized: EnumUpgradeMappings had no field named 'Id' or ending in 'Id').
  enum_upgrade                        TEXT                ,                     -- Foreign key to the parent EnumUpgrade.
  from_symbol                         TEXT                ,                     -- Source enum symbol.
  to_symbol                           TEXT                ,                     -- Target enum symbol (or empty/null when symbol is removed).
  description                         TEXT                                      -- Optional per-mapping description.
);
COMMENT ON TABLE enum_upgrade_mappings IS 'Per-symbol value renames for an EnumUpgrade. Empty when the parent EnumUpgrade preserves all names.';
COMMENT ON COLUMN enum_upgrade_mappings.enum_upgrade_mappings_id IS 'Primary key (auto-synthesized: EnumUpgradeMappings had no field named ''Id'' or ending in ''Id'').';
COMMENT ON COLUMN enum_upgrade_mappings.enum_upgrade IS 'Foreign key to the parent EnumUpgrade.';
COMMENT ON COLUMN enum_upgrade_mappings.from_symbol IS 'Source enum symbol.';
COMMENT ON COLUMN enum_upgrade_mappings.to_symbol IS 'Target enum symbol (or empty/null when symbol is removed).';
COMMENT ON COLUMN enum_upgrade_mappings.description IS 'Optional per-mapping description.';

