-- ============================================================================
-- DROP AND CREATE TABLES - Clean slate + Normalized schema
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Total Tables: 1
-- Total Raw Fields: 9
-- ============================================================================

SET timezone = 'UTC';

-- ============================================================================
-- DROP SPECIFIC OBJECTS - Only dropping objects that will be recreated
-- ============================================================================

-- Drop functions (order: first, because views depend on them)

-- Drop views (order: second, because they depend on tables)
DROP VIEW IF EXISTS vw_owners CASCADE;

-- Drop tables (order: last, after dependent objects are removed)
DROP TABLE IF EXISTS owners CASCADE;

-- ============================================================================
-- CREATE TABLES - Normalized data only (no calculated fields)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Owners: Table: Owners — entities (organizations or individuals) that own Types, Enums, and Formats. Sourced from definitions/owners.yaml.
-- ----------------------------------------------------------------------------
CREATE TABLE owners (
  name                                TEXT                ,                     -- Owner identifier slug. Example: 'gridworks-energy'. Acts as the primary key.
  owner_type                          TEXT                ,                     -- Either 'organization' or 'individual'.
  contact                             TEXT                ,                     -- Primary contact email.
  website                             TEXT                ,                     -- Owner's website URL.
  github                              TEXT                ,                     -- Owner's GitHub URL (optional).
  organization                        TEXT                ,                     -- Full legal/organization name.
  description                         TEXT                ,                     -- Free-text description of the owner's domain or focus.
  support_policy                      TEXT                ,                     -- How users get support from this owner (e.g. 'Community support via GitHub issues').
  license                             TEXT                                      -- License under which the owner's contributions are published (e.g. 'MIT').
);
COMMENT ON TABLE owners IS 'Table: Owners — entities (organizations or individuals) that own Types, Enums, and Formats. Sourced from definitions/owners.yaml.';
COMMENT ON COLUMN owners.name IS 'Owner identifier slug. Example: ''gridworks-energy''. Acts as the primary key.';
COMMENT ON COLUMN owners.owner_type IS 'Either ''organization'' or ''individual''.';
COMMENT ON COLUMN owners.contact IS 'Primary contact email.';
COMMENT ON COLUMN owners.website IS 'Owner''s website URL.';
COMMENT ON COLUMN owners.github IS 'Owner''s GitHub URL (optional).';
COMMENT ON COLUMN owners.organization IS 'Full legal/organization name.';
COMMENT ON COLUMN owners.description IS 'Free-text description of the owner''s domain or focus.';
COMMENT ON COLUMN owners.support_policy IS 'How users get support from this owner (e.g. ''Community support via GitHub issues'').';
COMMENT ON COLUMN owners.license IS 'License under which the owner''s contributions are published (e.g. ''MIT'').';

