-- ============================================================================
-- CREATE FUNCTIONS - Calculation functions for lookup/calculated fields
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- ============================================================================


-- Disable body validation so LANGUAGE sql functions can forward-reference
-- each other within this file. (pg_dump does the same thing for the same
-- reason.) Without this, SQL functions parse-check at CREATE time and fail
-- on the first forward call site; plpgsql didn't, which is how this file
-- ever worked. Dependency order is still enforced at EXECUTION time.
SET check_function_bodies = off;

-- ============================================================================
-- LOOKUP FUNCTIONS
-- These functions perform lookups via foreign key relationships
-- ============================================================================

-- calc_owners_is_organization
-- Field: Owners.IsOrganization
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_owners_is_organization(p_owners_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (CASE WHEN (SELECT NULLIF(owner_type, '') FROM owners WHERE owners_id = p_owners_id) = 'organization' THEN TRUE ELSE FALSE END)::boolean;
$$ LANGUAGE sql STABLE;

-- calc_owners_has_github
-- Field: Owners.HasGithub
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_owners_has_github(p_owners_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (CASE WHEN (SELECT NULLIF(github, '') FROM owners WHERE owners_id = p_owners_id) IS NOT NULL THEN TRUE ELSE FALSE END)::boolean;
$$ LANGUAGE sql STABLE;

-- calc_owners_format_count
-- Field: Owners.FormatCount
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_owners_format_count(p_owners_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM formats WHERE owner = (SELECT NULLIF(name, '') FROM owners WHERE owners_id = p_owners_id)))::integer;
$$ LANGUAGE sql STABLE;

-- calc_owners_enum_count
-- Field: Owners.EnumCount
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_owners_enum_count(p_owners_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM enums WHERE owner = (SELECT NULLIF(name, '') FROM owners WHERE owners_id = p_owners_id)))::integer;
$$ LANGUAGE sql STABLE;

-- calc_owners_type_count
-- Field: Owners.TypeCount
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_owners_type_count(p_owners_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM types WHERE owner = (SELECT NULLIF(name, '') FROM owners WHERE owners_id = p_owners_id)))::integer;
$$ LANGUAGE sql STABLE;

-- get_owners_name
-- Helper function: Get Name from Owners by OwnersId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_owners_name(p_owners_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT name FROM owners WHERE owners_id = p_owners_id);
$$ LANGUAGE sql STABLE;

-- get_owners_owner_type
-- Helper function: Get OwnerType from Owners by OwnersId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_owners_owner_type(p_owners_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT owner_type FROM owners WHERE owners_id = p_owners_id);
$$ LANGUAGE sql STABLE;

-- get_owners_contact
-- Helper function: Get Contact from Owners by OwnersId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_owners_contact(p_owners_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT contact FROM owners WHERE owners_id = p_owners_id);
$$ LANGUAGE sql STABLE;

-- get_owners_website
-- Helper function: Get Website from Owners by OwnersId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_owners_website(p_owners_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT website FROM owners WHERE owners_id = p_owners_id);
$$ LANGUAGE sql STABLE;

-- get_owners_github
-- Helper function: Get Github from Owners by OwnersId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_owners_github(p_owners_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT github FROM owners WHERE owners_id = p_owners_id);
$$ LANGUAGE sql STABLE;

-- get_owners_organization
-- Helper function: Get Organization from Owners by OwnersId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_owners_organization(p_owners_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT organization FROM owners WHERE owners_id = p_owners_id);
$$ LANGUAGE sql STABLE;

-- get_owners_description
-- Helper function: Get Description from Owners by OwnersId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_owners_description(p_owners_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT description FROM owners WHERE owners_id = p_owners_id);
$$ LANGUAGE sql STABLE;

-- get_owners_support_policy
-- Helper function: Get SupportPolicy from Owners by OwnersId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_owners_support_policy(p_owners_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT support_policy FROM owners WHERE owners_id = p_owners_id);
$$ LANGUAGE sql STABLE;

-- get_owners_license
-- Helper function: Get License from Owners by OwnersId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_owners_license(p_owners_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT license FROM owners WHERE owners_id = p_owners_id);
$$ LANGUAGE sql STABLE;

-- get_formats_name
-- Helper function: Get Name from Formats by FormatsId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_formats_name(p_formats_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT name FROM formats WHERE formats_id = p_formats_id);
$$ LANGUAGE sql STABLE;

-- get_formats_schema_url
-- Helper function: Get SchemaUrl from Formats by FormatsId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_formats_schema_url(p_formats_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT schema_url FROM formats WHERE formats_id = p_formats_id);
$$ LANGUAGE sql STABLE;

-- get_formats_title
-- Helper function: Get Title from Formats by FormatsId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_formats_title(p_formats_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT title FROM formats WHERE formats_id = p_formats_id);
$$ LANGUAGE sql STABLE;

-- get_formats_description
-- Helper function: Get Description from Formats by FormatsId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_formats_description(p_formats_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT description FROM formats WHERE formats_id = p_formats_id);
$$ LANGUAGE sql STABLE;

-- get_formats_pattern
-- Helper function: Get Pattern from Formats by FormatsId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_formats_pattern(p_formats_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT pattern FROM formats WHERE formats_id = p_formats_id);
$$ LANGUAGE sql STABLE;

-- get_formats_min_length
-- Helper function: Get MinLength from Formats by FormatsId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_formats_min_length(p_formats_id TEXT)
RETURNS INTEGER AS $$
  SELECT (SELECT min_length FROM formats WHERE formats_id = p_formats_id);
$$ LANGUAGE sql STABLE;

-- get_formats_max_length
-- Helper function: Get MaxLength from Formats by FormatsId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_formats_max_length(p_formats_id TEXT)
RETURNS INTEGER AS $$
  SELECT (SELECT max_length FROM formats WHERE formats_id = p_formats_id);
$$ LANGUAGE sql STABLE;

-- get_formats_json_schema_format
-- Helper function: Get JsonSchemaFormat from Formats by FormatsId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_formats_json_schema_format(p_formats_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT json_schema_format FROM formats WHERE formats_id = p_formats_id);
$$ LANGUAGE sql STABLE;

-- get_formats_created
-- Helper function: Get Created from Formats by FormatsId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_formats_created(p_formats_id TEXT)
RETURNS TIMESTAMPTZ AS $$
  SELECT (SELECT created FROM formats WHERE formats_id = p_formats_id);
$$ LANGUAGE sql STABLE;

-- get_formats_raw_json
-- Helper function: Get RawJson from Formats by FormatsId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_formats_raw_json(p_formats_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT raw_json FROM formats WHERE formats_id = p_formats_id);
$$ LANGUAGE sql STABLE;

-- calc_formats_is_retired
-- Field: Formats.IsRetired
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_formats_is_retired(p_formats_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (CASE WHEN (SELECT NULLIF(replaced_by, '') FROM formats WHERE formats_id = p_formats_id) IS NOT NULL THEN TRUE ELSE FALSE END)::boolean;
$$ LANGUAGE sql STABLE;

-- calc_formats_has_pattern
-- Field: Formats.HasPattern
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_formats_has_pattern(p_formats_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (CASE WHEN (SELECT NULLIF(pattern, '') FROM formats WHERE formats_id = p_formats_id) IS NOT NULL THEN TRUE ELSE FALSE END)::boolean;
$$ LANGUAGE sql STABLE;

-- calc_formats_has_length_bounds
-- Field: Formats.HasLengthBounds
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_formats_has_length_bounds(p_formats_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (CASE WHEN (((SELECT min_length FROM formats WHERE formats_id = p_formats_id))::NUMERIC > 0 OR ((SELECT max_length FROM formats WHERE formats_id = p_formats_id))::NUMERIC > 0) THEN TRUE ELSE FALSE END)::boolean;
$$ LANGUAGE sql STABLE;

-- calc_formats_example_count
-- Field: Formats.ExampleCount
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_formats_example_count(p_formats_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM format_examples WHERE format = (SELECT NULLIF(name, '') FROM formats WHERE formats_id = p_formats_id) AND is_counter = FALSE))::integer;
$$ LANGUAGE sql STABLE;

-- calc_formats_counter_example_count
-- Field: Formats.CounterExampleCount
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_formats_counter_example_count(p_formats_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM format_examples WHERE format = (SELECT NULLIF(name, '') FROM formats WHERE formats_id = p_formats_id) AND is_counter = TRUE))::integer;
$$ LANGUAGE sql STABLE;

-- calc_format_examples_name
-- Field: FormatExamples.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_format_examples_name(p_format_examples_id TEXT)
RETURNS TEXT AS $$
  SELECT (CONCAT((SELECT NULLIF(format, '') FROM format_examples WHERE format_examples_id = p_format_examples_id), '[', (SELECT idx FROM format_examples WHERE format_examples_id = p_format_examples_id), CASE WHEN COALESCE((SELECT is_counter FROM format_examples WHERE format_examples_id = p_format_examples_id), FALSE) THEN ('x')::text ELSE ('')::text END, ']'))::text;
$$ LANGUAGE sql STABLE;

-- calc_format_examples_example_kind
-- Field: FormatExamples.ExampleKind
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_format_examples_example_kind(p_format_examples_id TEXT)
RETURNS TEXT AS $$
  SELECT (CASE WHEN COALESCE((SELECT is_counter FROM format_examples WHERE format_examples_id = p_format_examples_id), FALSE) THEN ('counter')::text ELSE ('positive')::text END)::text;
$$ LANGUAGE sql STABLE;

-- get_enums_name
-- Helper function: Get Name from Enums by EnumsId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_enums_name(p_enums_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT name FROM enums WHERE enums_id = p_enums_id);
$$ LANGUAGE sql STABLE;

-- get_enums_enum_type
-- Helper function: Get EnumType from Enums by EnumsId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_enums_enum_type(p_enums_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT enum_type FROM enums WHERE enums_id = p_enums_id);
$$ LANGUAGE sql STABLE;

-- get_enums_value_type
-- Helper function: Get ValueType from Enums by EnumsId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_enums_value_type(p_enums_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT value_type FROM enums WHERE enums_id = p_enums_id);
$$ LANGUAGE sql STABLE;

-- get_enums_description
-- Helper function: Get Description from Enums by EnumsId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_enums_description(p_enums_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT description FROM enums WHERE enums_id = p_enums_id);
$$ LANGUAGE sql STABLE;

-- get_enums_raw_json
-- Helper function: Get RawJson from Enums by EnumsId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_enums_raw_json(p_enums_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT raw_json FROM enums WHERE enums_id = p_enums_id);
$$ LANGUAGE sql STABLE;

-- calc_enums_is_retired
-- Field: Enums.IsRetired
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_enums_is_retired(p_enums_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (CASE WHEN (SELECT NULLIF(replaced_by, '') FROM enums WHERE enums_id = p_enums_id) IS NOT NULL THEN TRUE ELSE FALSE END)::boolean;
$$ LANGUAGE sql STABLE;

-- calc_enums_is_versioned
-- Field: Enums.IsVersioned
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_enums_is_versioned(p_enums_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (CASE WHEN (SELECT NULLIF(enum_type, '') FROM enums WHERE enums_id = p_enums_id) = 'versioned' THEN TRUE ELSE FALSE END)::boolean;
$$ LANGUAGE sql STABLE;

-- calc_enums_is_literal
-- Field: Enums.IsLiteral
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_enums_is_literal(p_enums_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (CASE WHEN (SELECT NULLIF(enum_type, '') FROM enums WHERE enums_id = p_enums_id) = 'literal' THEN TRUE ELSE FALSE END)::boolean;
$$ LANGUAGE sql STABLE;

-- calc_enums_is_integer_valued
-- Field: Enums.IsIntegerValued
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_enums_is_integer_valued(p_enums_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (CASE WHEN (SELECT NULLIF(value_type, '') FROM enums WHERE enums_id = p_enums_id) = 'integer' THEN TRUE ELSE FALSE END)::boolean;
$$ LANGUAGE sql STABLE;

-- calc_enums_version_count
-- Field: Enums.VersionCount
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_enums_version_count(p_enums_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM enum_versions WHERE enum = (SELECT NULLIF(name, '') FROM enums WHERE enums_id = p_enums_id)))::integer;
$$ LANGUAGE sql STABLE;

-- calc_enum_versions_name
-- Field: EnumVersions.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_enum_versions_name(p_enum_versions_id TEXT)
RETURNS TEXT AS $$
  SELECT (CONCAT((SELECT NULLIF(enum, '') FROM enum_versions WHERE enum_versions_id = p_enum_versions_id), '/', (SELECT NULLIF(version, '') FROM enum_versions WHERE enum_versions_id = p_enum_versions_id)))::text;
$$ LANGUAGE sql STABLE;

-- calc_enum_versions_is_active
-- Field: EnumVersions.IsActive
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_enum_versions_is_active(p_enum_versions_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (CASE WHEN (SELECT NULLIF(status, '') FROM enum_versions WHERE enum_versions_id = p_enum_versions_id) = 'active' THEN TRUE ELSE FALSE END)::boolean;
$$ LANGUAGE sql STABLE;

-- calc_enum_versions_is_deprecated
-- Field: EnumVersions.IsDeprecated
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_enum_versions_is_deprecated(p_enum_versions_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (CASE WHEN (SELECT NULLIF(status, '') FROM enum_versions WHERE enum_versions_id = p_enum_versions_id) = 'deprecated' THEN TRUE ELSE FALSE END)::boolean;
$$ LANGUAGE sql STABLE;

-- calc_enum_versions_has_default_symbol
-- Field: EnumVersions.HasDefaultSymbol
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_enum_versions_has_default_symbol(p_enum_versions_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (CASE WHEN (SELECT NULLIF(default_symbol, '') FROM enum_versions WHERE enum_versions_id = p_enum_versions_id) IS NOT NULL THEN TRUE ELSE FALSE END)::boolean;
$$ LANGUAGE sql STABLE;

-- calc_enum_versions_value_count
-- Field: EnumVersions.ValueCount
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_enum_versions_value_count(p_enum_versions_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM enum_values WHERE enum_version = calc_enum_versions_name(p_enum_versions_id)))::integer;
$$ LANGUAGE sql STABLE;

-- get_enum_versions_version
-- Helper function: Get Version from EnumVersions by EnumVersionsId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_enum_versions_version(p_enum_versions_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT version FROM enum_versions WHERE enum_versions_id = p_enum_versions_id);
$$ LANGUAGE sql STABLE;

-- get_enum_versions_schema_url
-- Helper function: Get SchemaUrl from EnumVersions by EnumVersionsId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_enum_versions_schema_url(p_enum_versions_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT schema_url FROM enum_versions WHERE enum_versions_id = p_enum_versions_id);
$$ LANGUAGE sql STABLE;

-- get_enum_versions_title
-- Helper function: Get Title from EnumVersions by EnumVersionsId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_enum_versions_title(p_enum_versions_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT title FROM enum_versions WHERE enum_versions_id = p_enum_versions_id);
$$ LANGUAGE sql STABLE;

-- get_enum_versions_description
-- Helper function: Get Description from EnumVersions by EnumVersionsId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_enum_versions_description(p_enum_versions_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT description FROM enum_versions WHERE enum_versions_id = p_enum_versions_id);
$$ LANGUAGE sql STABLE;

-- get_enum_versions_default_symbol
-- Helper function: Get DefaultSymbol from EnumVersions by EnumVersionsId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_enum_versions_default_symbol(p_enum_versions_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT default_symbol FROM enum_versions WHERE enum_versions_id = p_enum_versions_id);
$$ LANGUAGE sql STABLE;

-- get_enum_versions_status
-- Helper function: Get Status from EnumVersions by EnumVersionsId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_enum_versions_status(p_enum_versions_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT status FROM enum_versions WHERE enum_versions_id = p_enum_versions_id);
$$ LANGUAGE sql STABLE;

-- get_enum_versions_created
-- Helper function: Get Created from EnumVersions by EnumVersionsId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_enum_versions_created(p_enum_versions_id TEXT)
RETURNS TIMESTAMPTZ AS $$
  SELECT (SELECT created FROM enum_versions WHERE enum_versions_id = p_enum_versions_id);
$$ LANGUAGE sql STABLE;

-- get_enum_versions_raw_json
-- Helper function: Get RawJson from EnumVersions by EnumVersionsId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_enum_versions_raw_json(p_enum_versions_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT raw_json FROM enum_versions WHERE enum_versions_id = p_enum_versions_id);
$$ LANGUAGE sql STABLE;

-- calc_enum_values_name
-- Field: EnumValues.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_enum_values_name(p_enum_values_id TEXT)
RETURNS TEXT AS $$
  SELECT (CONCAT((SELECT NULLIF(enum_version, '') FROM enum_values WHERE enum_values_id = p_enum_values_id), ':', (SELECT NULLIF(symbol, '') FROM enum_values WHERE enum_values_id = p_enum_values_id)))::text;
$$ LANGUAGE sql STABLE;

-- calc_enum_values_has_description
-- Field: EnumValues.HasDescription
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_enum_values_has_description(p_enum_values_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (CASE WHEN (SELECT NULLIF(description, '') FROM enum_values WHERE enum_values_id = p_enum_values_id) IS NOT NULL THEN TRUE ELSE FALSE END)::boolean;
$$ LANGUAGE sql STABLE;

-- get_types_name
-- Helper function: Get Name from Types by TypesId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_types_name(p_types_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT name FROM types WHERE types_id = p_types_id);
$$ LANGUAGE sql STABLE;

-- get_types_title
-- Helper function: Get Title from Types by TypesId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_types_title(p_types_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT title FROM types WHERE types_id = p_types_id);
$$ LANGUAGE sql STABLE;

-- get_types_description
-- Helper function: Get Description from Types by TypesId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_types_description(p_types_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT description FROM types WHERE types_id = p_types_id);
$$ LANGUAGE sql STABLE;

-- get_types_python_class_name
-- Helper function: Get PythonClassName from Types by TypesId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_types_python_class_name(p_types_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT python_class_name FROM types WHERE types_id = p_types_id);
$$ LANGUAGE sql STABLE;

-- get_types_make_data_class
-- Helper function: Get MakeDataClass from Types by TypesId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_types_make_data_class(p_types_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (SELECT make_data_class FROM types WHERE types_id = p_types_id);
$$ LANGUAGE sql STABLE;

-- get_types_is_cac
-- Helper function: Get IsCac from Types by TypesId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_types_is_cac(p_types_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (SELECT is_cac FROM types WHERE types_id = p_types_id);
$$ LANGUAGE sql STABLE;

-- get_types_is_component
-- Helper function: Get IsComponent from Types by TypesId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_types_is_component(p_types_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (SELECT is_component FROM types WHERE types_id = p_types_id);
$$ LANGUAGE sql STABLE;

-- calc_types_is_retired
-- Field: Types.IsRetired
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_types_is_retired(p_types_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (CASE WHEN (SELECT NULLIF(replaced_by, '') FROM types WHERE types_id = p_types_id) IS NOT NULL THEN TRUE ELSE FALSE END)::boolean;
$$ LANGUAGE sql STABLE;

-- calc_types_version_count
-- Field: Types.VersionCount
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_types_version_count(p_types_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM type_versions WHERE type = (SELECT NULLIF(name, '') FROM types WHERE types_id = p_types_id)))::integer;
$$ LANGUAGE sql STABLE;

-- calc_type_versions_name
-- Field: TypeVersions.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_type_versions_name(p_type_versions_id TEXT)
RETURNS TEXT AS $$
  SELECT (CONCAT((SELECT NULLIF(type, '') FROM type_versions WHERE type_versions_id = p_type_versions_id), '/', (SELECT NULLIF(version, '') FROM type_versions WHERE type_versions_id = p_type_versions_id)))::text;
$$ LANGUAGE sql STABLE;

-- calc_type_versions_is_active
-- Field: TypeVersions.IsActive
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_type_versions_is_active(p_type_versions_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (CASE WHEN (SELECT NULLIF(status, '') FROM type_versions WHERE type_versions_id = p_type_versions_id) = 'active' THEN TRUE ELSE FALSE END)::boolean;
$$ LANGUAGE sql STABLE;

-- calc_type_versions_is_deprecated
-- Field: TypeVersions.IsDeprecated
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_type_versions_is_deprecated(p_type_versions_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (CASE WHEN (SELECT NULLIF(status, '') FROM type_versions WHERE type_versions_id = p_type_versions_id) = 'deprecated' THEN TRUE ELSE FALSE END)::boolean;
$$ LANGUAGE sql STABLE;

-- calc_type_versions_is_closed
-- Field: TypeVersions.IsClosed
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_type_versions_is_closed(p_type_versions_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (CASE WHEN COALESCE((SELECT extra_allowed FROM type_versions WHERE type_versions_id = p_type_versions_id), FALSE) THEN FALSE ELSE TRUE END)::boolean;
$$ LANGUAGE sql STABLE;

-- calc_type_versions_attribute_count
-- Field: TypeVersions.AttributeCount
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_type_versions_attribute_count(p_type_versions_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM type_attributes WHERE type_version = calc_type_versions_name(p_type_versions_id)))::integer;
$$ LANGUAGE sql STABLE;

-- calc_type_versions_required_attribute_count
-- Field: TypeVersions.RequiredAttributeCount
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_type_versions_required_attribute_count(p_type_versions_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM type_attributes WHERE type_version = calc_type_versions_name(p_type_versions_id) AND is_required = TRUE))::integer;
$$ LANGUAGE sql STABLE;

-- calc_type_versions_axiom_count
-- Field: TypeVersions.AxiomCount
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_type_versions_axiom_count(p_type_versions_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM type_axioms WHERE type_version = calc_type_versions_name(p_type_versions_id)))::integer;
$$ LANGUAGE sql STABLE;

-- calc_type_versions_example_count
-- Field: TypeVersions.ExampleCount
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_type_versions_example_count(p_type_versions_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM type_examples WHERE type_version = calc_type_versions_name(p_type_versions_id)))::integer;
$$ LANGUAGE sql STABLE;

-- get_type_versions_version
-- Helper function: Get Version from TypeVersions by TypeVersionsId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_type_versions_version(p_type_versions_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT version FROM type_versions WHERE type_versions_id = p_type_versions_id);
$$ LANGUAGE sql STABLE;

-- get_type_versions_schema_url
-- Helper function: Get SchemaUrl from TypeVersions by TypeVersionsId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_type_versions_schema_url(p_type_versions_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT schema_url FROM type_versions WHERE type_versions_id = p_type_versions_id);
$$ LANGUAGE sql STABLE;

-- get_type_versions_title
-- Helper function: Get Title from TypeVersions by TypeVersionsId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_type_versions_title(p_type_versions_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT title FROM type_versions WHERE type_versions_id = p_type_versions_id);
$$ LANGUAGE sql STABLE;

-- get_type_versions_description
-- Helper function: Get Description from TypeVersions by TypeVersionsId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_type_versions_description(p_type_versions_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT description FROM type_versions WHERE type_versions_id = p_type_versions_id);
$$ LANGUAGE sql STABLE;

-- get_type_versions_extra_allowed
-- Helper function: Get ExtraAllowed from TypeVersions by TypeVersionsId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_type_versions_extra_allowed(p_type_versions_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (SELECT extra_allowed FROM type_versions WHERE type_versions_id = p_type_versions_id);
$$ LANGUAGE sql STABLE;

-- get_type_versions_status
-- Helper function: Get Status from TypeVersions by TypeVersionsId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_type_versions_status(p_type_versions_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT status FROM type_versions WHERE type_versions_id = p_type_versions_id);
$$ LANGUAGE sql STABLE;

-- get_type_versions_created
-- Helper function: Get Created from TypeVersions by TypeVersionsId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_type_versions_created(p_type_versions_id TEXT)
RETURNS TIMESTAMPTZ AS $$
  SELECT (SELECT created FROM type_versions WHERE type_versions_id = p_type_versions_id);
$$ LANGUAGE sql STABLE;

-- get_type_versions_raw_json
-- Helper function: Get RawJson from TypeVersions by TypeVersionsId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_type_versions_raw_json(p_type_versions_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT raw_json FROM type_versions WHERE type_versions_id = p_type_versions_id);
$$ LANGUAGE sql STABLE;

-- get_type_helpers_name
-- Helper function: Get Name from TypeHelpers by TypeHelpersId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_type_helpers_name(p_type_helpers_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT name FROM type_helpers WHERE type_helpers_id = p_type_helpers_id);
$$ LANGUAGE sql STABLE;

-- get_type_helpers_title
-- Helper function: Get Title from TypeHelpers by TypeHelpersId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_type_helpers_title(p_type_helpers_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT title FROM type_helpers WHERE type_helpers_id = p_type_helpers_id);
$$ LANGUAGE sql STABLE;

-- get_type_helpers_description
-- Helper function: Get Description from TypeHelpers by TypeHelpersId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_type_helpers_description(p_type_helpers_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT description FROM type_helpers WHERE type_helpers_id = p_type_helpers_id);
$$ LANGUAGE sql STABLE;

-- get_type_helpers_extra_allowed
-- Helper function: Get ExtraAllowed from TypeHelpers by TypeHelpersId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_type_helpers_extra_allowed(p_type_helpers_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (SELECT extra_allowed FROM type_helpers WHERE type_helpers_id = p_type_helpers_id);
$$ LANGUAGE sql STABLE;

-- get_type_helpers_origin_path
-- Helper function: Get OriginPath from TypeHelpers by TypeHelpersId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_type_helpers_origin_path(p_type_helpers_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT origin_path FROM type_helpers WHERE type_helpers_id = p_type_helpers_id);
$$ LANGUAGE sql STABLE;

-- calc_type_attributes_name
-- Field: TypeAttributes.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_type_attributes_name(p_type_attributes_id TEXT)
RETURNS TEXT AS $$
  SELECT (CONCAT((SELECT NULLIF(type_version, '') FROM type_attributes WHERE type_attributes_id = p_type_attributes_id), '.', (SELECT NULLIF(attribute_name, '') FROM type_attributes WHERE type_attributes_id = p_type_attributes_id)))::text;
$$ LANGUAGE sql STABLE;

-- calc_type_attributes_is_optional
-- Field: TypeAttributes.IsOptional
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_type_attributes_is_optional(p_type_attributes_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (CASE WHEN COALESCE((SELECT is_required FROM type_attributes WHERE type_attributes_id = p_type_attributes_id), FALSE) THEN FALSE ELSE TRUE END)::boolean;
$$ LANGUAGE sql STABLE;

-- calc_type_attributes_has_default
-- Field: TypeAttributes.HasDefault
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_type_attributes_has_default(p_type_attributes_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (CASE WHEN (SELECT NULLIF("default", '') FROM type_attributes WHERE type_attributes_id = p_type_attributes_id) IS NOT NULL THEN TRUE ELSE FALSE END)::boolean;
$$ LANGUAGE sql STABLE;

-- calc_type_attributes_ref_kind
-- Field: TypeAttributes.RefKind
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_type_attributes_ref_kind(p_type_attributes_id TEXT)
RETURNS TEXT AS $$
  SELECT (CASE WHEN (SELECT NULLIF(format_ref, '') FROM type_attributes WHERE type_attributes_id = p_type_attributes_id) IS NOT NULL THEN ('format')::text ELSE (CASE WHEN (SELECT NULLIF(enum_version_ref, '') FROM type_attributes WHERE type_attributes_id = p_type_attributes_id) IS NOT NULL THEN ('enum')::text ELSE (CASE WHEN (SELECT NULLIF(sub_type_version_ref, '') FROM type_attributes WHERE type_attributes_id = p_type_attributes_id) IS NOT NULL THEN ('subtype')::text ELSE (CASE WHEN (SELECT NULLIF(helper_ref, '') FROM type_attributes WHERE type_attributes_id = p_type_attributes_id) IS NOT NULL THEN ('helper')::text ELSE ('primitive')::text END)::text END)::text END)::text END)::text;
$$ LANGUAGE sql STABLE;

-- calc_type_examples_name
-- Field: TypeExamples.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_type_examples_name(p_type_examples_id TEXT)
RETURNS TEXT AS $$
  SELECT (CONCAT((SELECT NULLIF(type_version, '') FROM type_examples WHERE type_examples_id = p_type_examples_id), '[', (SELECT idx FROM type_examples WHERE type_examples_id = p_type_examples_id), ']'))::text;
$$ LANGUAGE sql STABLE;

-- calc_type_axioms_name
-- Field: TypeAxioms.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_type_axioms_name(p_type_axioms_id TEXT)
RETURNS TEXT AS $$
  SELECT (CONCAT((SELECT NULLIF(type_version, '') FROM type_axioms WHERE type_axioms_id = p_type_axioms_id), '.axiom', (SELECT number FROM type_axioms WHERE type_axioms_id = p_type_axioms_id), '.', (SELECT NULLIF(axiom_name, '') FROM type_axioms WHERE type_axioms_id = p_type_axioms_id)))::text;
$$ LANGUAGE sql STABLE;

-- calc_type_axioms_has_statement
-- Field: TypeAxioms.HasStatement
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_type_axioms_has_statement(p_type_axioms_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (CASE WHEN (SELECT NULLIF(statement, '') FROM type_axioms WHERE type_axioms_id = p_type_axioms_id) IS NOT NULL THEN TRUE ELSE FALSE END)::boolean;
$$ LANGUAGE sql STABLE;

-- calc_type_helpers_attribute_count
-- Field: TypeHelpers.AttributeCount
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_type_helpers_attribute_count(p_type_helpers_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM type_helper_attributes WHERE type_helper = (SELECT NULLIF(name, '') FROM type_helpers WHERE type_helpers_id = p_type_helpers_id)))::integer;
$$ LANGUAGE sql STABLE;

-- calc_type_helpers_required_attribute_count
-- Field: TypeHelpers.RequiredAttributeCount
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_type_helpers_required_attribute_count(p_type_helpers_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM type_helper_attributes WHERE type_helper = (SELECT NULLIF(name, '') FROM type_helpers WHERE type_helpers_id = p_type_helpers_id) AND is_required = TRUE))::integer;
$$ LANGUAGE sql STABLE;

-- calc_type_helpers_is_closed
-- Field: TypeHelpers.IsClosed
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_type_helpers_is_closed(p_type_helpers_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (CASE WHEN COALESCE((SELECT extra_allowed FROM type_helpers WHERE type_helpers_id = p_type_helpers_id), FALSE) THEN FALSE ELSE TRUE END)::boolean;
$$ LANGUAGE sql STABLE;

-- calc_type_helper_attributes_name
-- Field: TypeHelperAttributes.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_type_helper_attributes_name(p_type_helper_attributes_id TEXT)
RETURNS TEXT AS $$
  SELECT (CONCAT((SELECT NULLIF(type_helper, '') FROM type_helper_attributes WHERE type_helper_attributes_id = p_type_helper_attributes_id), '.', (SELECT NULLIF(attribute_name, '') FROM type_helper_attributes WHERE type_helper_attributes_id = p_type_helper_attributes_id)))::text;
$$ LANGUAGE sql STABLE;

-- calc_type_helper_attributes_is_optional
-- Field: TypeHelperAttributes.IsOptional
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_type_helper_attributes_is_optional(p_type_helper_attributes_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (CASE WHEN COALESCE((SELECT is_required FROM type_helper_attributes WHERE type_helper_attributes_id = p_type_helper_attributes_id), FALSE) THEN FALSE ELSE TRUE END)::boolean;
$$ LANGUAGE sql STABLE;

-- calc_type_helper_attributes_ref_kind
-- Field: TypeHelperAttributes.RefKind
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_type_helper_attributes_ref_kind(p_type_helper_attributes_id TEXT)
RETURNS TEXT AS $$
  SELECT (CASE WHEN (SELECT NULLIF(format_ref, '') FROM type_helper_attributes WHERE type_helper_attributes_id = p_type_helper_attributes_id) IS NOT NULL THEN ('format')::text ELSE (CASE WHEN (SELECT NULLIF(enum_version_ref, '') FROM type_helper_attributes WHERE type_helper_attributes_id = p_type_helper_attributes_id) IS NOT NULL THEN ('enum')::text ELSE (CASE WHEN (SELECT NULLIF(sub_type_version_ref, '') FROM type_helper_attributes WHERE type_helper_attributes_id = p_type_helper_attributes_id) IS NOT NULL THEN ('subtype')::text ELSE (CASE WHEN (SELECT NULLIF(helper_ref, '') FROM type_helper_attributes WHERE type_helper_attributes_id = p_type_helper_attributes_id) IS NOT NULL THEN ('helper')::text ELSE ('primitive')::text END)::text END)::text END)::text END)::text;
$$ LANGUAGE sql STABLE;

-- calc_projections_mapping_count
-- Field: Projections.MappingCount
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_projections_mapping_count(p_projections_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM projection_mappings WHERE projection = (SELECT NULLIF(name, '') FROM projections WHERE projections_id = p_projections_id)))::integer;
$$ LANGUAGE sql STABLE;

-- calc_projections_is_scripted
-- Field: Projections.IsScripted
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_projections_is_scripted(p_projections_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (CASE WHEN (SELECT NULLIF(raw_script, '') FROM projections WHERE projections_id = p_projections_id) IS NOT NULL THEN TRUE ELSE FALSE END)::boolean;
$$ LANGUAGE sql STABLE;

-- calc_projections_is_flat_lookup
-- Field: Projections.IsFlatLookup
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_projections_is_flat_lookup(p_projections_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (CASE WHEN (SELECT NULLIF(raw_script, '') FROM projections WHERE projections_id = p_projections_id) IS NOT NULL THEN FALSE ELSE TRUE END)::boolean;
$$ LANGUAGE sql STABLE;

-- get_projections_name
-- Helper function: Get Name from Projections by ProjectionsId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_projections_name(p_projections_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT name FROM projections WHERE projections_id = p_projections_id);
$$ LANGUAGE sql STABLE;

-- get_projections_description
-- Helper function: Get Description from Projections by ProjectionsId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_projections_description(p_projections_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT description FROM projections WHERE projections_id = p_projections_id);
$$ LANGUAGE sql STABLE;

-- get_projections_raw_script
-- Helper function: Get RawScript from Projections by ProjectionsId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_projections_raw_script(p_projections_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT raw_script FROM projections WHERE projections_id = p_projections_id);
$$ LANGUAGE sql STABLE;

-- calc_projection_mappings_name
-- Field: ProjectionMappings.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_projection_mappings_name(p_projection_mappings_id TEXT)
RETURNS TEXT AS $$
  SELECT (CONCAT((SELECT NULLIF(projection, '') FROM projection_mappings WHERE projection_mappings_id = p_projection_mappings_id), ':', (SELECT NULLIF(from_symbol, '') FROM projection_mappings WHERE projection_mappings_id = p_projection_mappings_id)))::text;
$$ LANGUAGE sql STABLE;

-- calc_projection_mappings_is_removal
-- Field: ProjectionMappings.IsRemoval
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_projection_mappings_is_removal(p_projection_mappings_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (CASE WHEN (SELECT NULLIF(to_symbol, '') FROM projection_mappings WHERE projection_mappings_id = p_projection_mappings_id) IS NOT NULL THEN FALSE ELSE TRUE END)::boolean;
$$ LANGUAGE sql STABLE;

-- calc_projection_mappings_is_identity
-- Field: ProjectionMappings.IsIdentity
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_projection_mappings_is_identity(p_projection_mappings_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (CASE WHEN (SELECT NULLIF(from_symbol, '') FROM projection_mappings WHERE projection_mappings_id = p_projection_mappings_id) = (SELECT NULLIF(to_symbol, '') FROM projection_mappings WHERE projection_mappings_id = p_projection_mappings_id) THEN TRUE ELSE FALSE END)::boolean;
$$ LANGUAGE sql STABLE;

-- calc_type_upgrades_name
-- Field: TypeUpgrades.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_type_upgrades_name(p_type_upgrades_id TEXT)
RETURNS TEXT AS $$
  SELECT (CONCAT((SELECT NULLIF(from_type_version, '') FROM type_upgrades WHERE type_upgrades_id = p_type_upgrades_id), ' -> ', (SELECT NULLIF(to_type_version, '') FROM type_upgrades WHERE type_upgrades_id = p_type_upgrades_id)))::text;
$$ LANGUAGE sql STABLE;

-- get_type_upgrades_description
-- Helper function: Get Description from TypeUpgrades by TypeUpgradesId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_type_upgrades_description(p_type_upgrades_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT description FROM type_upgrades WHERE type_upgrades_id = p_type_upgrades_id);
$$ LANGUAGE sql STABLE;

-- get_type_upgrades_raw_script
-- Helper function: Get RawScript from TypeUpgrades by TypeUpgradesId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_type_upgrades_raw_script(p_type_upgrades_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT raw_script FROM type_upgrades WHERE type_upgrades_id = p_type_upgrades_id);
$$ LANGUAGE sql STABLE;

-- calc_type_upgrade_ops_name
-- Field: TypeUpgradeOps.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_type_upgrade_ops_name(p_type_upgrade_ops_id TEXT)
RETURNS TEXT AS $$
  SELECT (CONCAT((SELECT NULLIF(type_upgrade, '') FROM type_upgrade_ops WHERE type_upgrade_ops_id = p_type_upgrade_ops_id), '#', (SELECT idx FROM type_upgrade_ops WHERE type_upgrade_ops_id = p_type_upgrade_ops_id)))::text;
$$ LANGUAGE sql STABLE;

-- calc_enum_upgrades_name
-- Field: EnumUpgrades.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_enum_upgrades_name(p_enum_upgrades_id TEXT)
RETURNS TEXT AS $$
  SELECT (CONCAT((SELECT NULLIF(from_enum_version, '') FROM enum_upgrades WHERE enum_upgrades_id = p_enum_upgrades_id), ' -> ', (SELECT NULLIF(to_enum_version, '') FROM enum_upgrades WHERE enum_upgrades_id = p_enum_upgrades_id)))::text;
$$ LANGUAGE sql STABLE;

-- get_enum_upgrades_description
-- Helper function: Get Description from EnumUpgrades by EnumUpgradesId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_enum_upgrades_description(p_enum_upgrades_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT description FROM enum_upgrades WHERE enum_upgrades_id = p_enum_upgrades_id);
$$ LANGUAGE sql STABLE;

-- get_enum_upgrades_raw_script
-- Helper function: Get RawScript from EnumUpgrades by EnumUpgradesId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_enum_upgrades_raw_script(p_enum_upgrades_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT raw_script FROM enum_upgrades WHERE enum_upgrades_id = p_enum_upgrades_id);
$$ LANGUAGE sql STABLE;

-- calc_enum_upgrade_mappings_name
-- Field: EnumUpgradeMappings.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_enum_upgrade_mappings_name(p_enum_upgrade_mappings_id TEXT)
RETURNS TEXT AS $$
  SELECT (CONCAT((SELECT NULLIF(enum_upgrade, '') FROM enum_upgrade_mappings WHERE enum_upgrade_mappings_id = p_enum_upgrade_mappings_id), ':', (SELECT NULLIF(from_symbol, '') FROM enum_upgrade_mappings WHERE enum_upgrade_mappings_id = p_enum_upgrade_mappings_id)))::text;
$$ LANGUAGE sql STABLE;

-- ============================================================================
-- MANY-SIDE RELATIONSHIP FUNCTIONS
-- These functions aggregate child records for many-side relationships
-- ============================================================================

-- ============================================================================
-- INVERSE RELATIONSHIP FUNCTIONS
-- These functions perform reverse FK lookups for inverse-side relationships
-- ============================================================================

