-- ============================================================================
-- CREATE VIEWS - Combine raw data with calculated fields
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Total Views: 20
-- ============================================================================

-- ----------------------------------------------------------------------------
-- vw_erb_versions_test: Table: ERBVersions
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE VIEW vw_erb_versions_test WITH (security_invoker = ON) AS
SELECT
  t.erb_version_id,
  t.name,
  t.message,
  t.notes,
  t.commit_date,
  t.is_published
FROM erb_versions_test t;

