-- ============================================================================
-- CREATE VIEWS - Combine raw data with calculated fields
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: check-add    Stage: dev
-- Total Views: 26
-- ============================================================================

-- ----------------------------------------------------------------------------
-- vw_owners: Entities (organizations or individuals) that own Types, Enums, and Formats. Sourced from definitions/owners.yaml.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE VIEW vw_owners WITH (security_invoker = ON) AS
SELECT
  t.owners_id,                                                                  -- Primary key (auto-synthesized: Owners had no field named 'Id' or ending in 'Id').
  t.name,                                                                       -- Owner identifier slug. Example: 'gridworks-energy'. Acts as the primary key.
  t.owner_type,                                                                 -- Either 'organization' or 'individual'.
  t.contact,                                                                    -- Primary contact email.
  t.website,                                                                    -- Owner's website URL.
  t.github,                                                                     -- Owner's GitHub URL (optional).
  t.organization,                                                               -- Full legal/organization name.
  t.description,                                                                -- Free-text description of the owner's domain or focus.
  t.support_policy,                                                             -- How users get support from this owner.
  t.license,                                                                    -- License under which the owner's contributions are published (e.g. 'MIT').
  calc_owners_is_organization(t.owners_id) AS is_organization,                  -- True when OwnerType is 'organization' (vs 'individual'). Cheap classifier for grouping owners.
  calc_owners_has_github(t.owners_id) AS has_github,                            -- True when this owner has a Github URL on file.
  calc_owners_format_count(t.owners_id) AS format_count,                        -- Number of Formats owned by this owner.
  calc_owners_enum_count(t.owners_id) AS enum_count,                            -- Number of Enums owned by this owner.
  calc_owners_type_count(t.owners_id) AS type_count,                            -- Number of Types owned by this owner.
  calc_owners_draft_type_version_count(t.owners_id) AS draft_type_version_count,-- Number of draft TypeVersions across all this owner's Words. Drives §7 'drafts open: N' badge on the Vocabularies grid.
  calc_owners_published_type_version_count(t.owners_id) AS published_type_version_count,-- Number of published TypeVersions.
  calc_owners_draft_enum_version_count(t.owners_id) AS draft_enum_version_count,-- Number of draft EnumVersions across this owner's Enums.
  calc_owners_published_enum_version_count(t.owners_id) AS published_enum_version_count,-- Number of published EnumVersions.
  calc_owners_has_open_drafts(t.owners_id) AS has_open_drafts,                  -- True iff this owner has any draft Type or Enum versions. Drives the amber dot on the Vocabularies card.
  calc_owners_has_published_artifacts(t.owners_id) AS has_published_artifacts,  -- True iff this owner has any artifacts at all (Types, Enums, or Formats). Drives empty-state vs populated rendering.
  calc_owners_latest_type_version_at(t.owners_id) AS latest_type_version_at,    -- Most recent TypeVersions.Created among this owner's Words.
  calc_owners_latest_enum_version_at(t.owners_id) AS latest_enum_version_at,    -- Most recent EnumVersions.Created among this owner's Enums.
  calc_owners_latest_format_at(t.owners_id) AS latest_format_at                 -- Most recent Formats.Created among this owner's Formats.
FROM owners t;

-- ----------------------------------------------------------------------------
-- vw_formats: JSON-Schema string formats with regex patterns and length bounds. Sourced from definitions/formats/*.yaml. Formats are not versioned.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE VIEW vw_formats WITH (security_invoker = ON) AS
SELECT
  t.formats_id,                                                                 -- Primary key (auto-synthesized: Formats had no field named 'Id' or ending in 'Id').
  t.name,                                                                       -- Format identifier slug. Example: 'uuid4.str'. Acts as the primary key.
  t.owner,                                                                      -- Owner of this format.
  t.schema_url,                                                                 -- Schema URL from JSON-Schema $id.
  t.title,                                                                      -- Human-readable title.
  t.description,                                                                -- Free-text description of the format.
  t.replaced_by,                                                                -- Advisory pointer to another Format that supersedes this one. The original Format remains valid and queryable — ReplacedBy is just a hint to consumers about a preferred successor. NOT a state change; published versions are immutable.
  t.pattern,                                                                    -- Regex pattern that valid values must match.
  t.min_length,                                                                 -- Minimum string length, if constrained.
  t.max_length,                                                                 -- Maximum string length, if constrained.
  t.json_schema_format,                                                         -- JSON-Schema 'format' keyword if present (e.g. 'date-time', 'email').
  t.created,                                                                    -- Created timestamp from registry.yaml.
  t.raw_json,                                                                   -- Escape hatch: any unmodeled JSON-Schema fields, serialized as JSON string.
  calc_formats_has_pattern(t.formats_id) AS has_pattern,                        -- True when a regex Pattern constraint is defined.
  calc_formats_has_length_bounds(t.formats_id) AS has_length_bounds,            -- True when at least one of MinLength / MaxLength is defined.
  calc_formats_example_count(t.formats_id) AS example_count,                    -- Number of positive examples on this format (FormatExamples where IsCounter=false).
  calc_formats_counter_example_count(t.formats_id) AS counter_example_count,    -- Number of counterexamples on this format (FormatExamples where IsCounter=true).
  calc_formats_type_attribute_usage_count(t.formats_id) AS type_attribute_usage_count,-- Number of TypeAttributes that point at this Format via FormatRef.
  calc_formats_type_helper_attribute_usage_count(t.formats_id) AS type_helper_attribute_usage_count,-- Number of TypeHelperAttributes that point at this Format via FormatRef.
  calc_formats_total_usage_count(t.formats_id) AS total_usage_count,            -- Total references across TypeAttributes + TypeHelperAttributes (sum of the two usage counts).
  calc_formats_is_used(t.formats_id) AS is_used,                                -- True when at least one TypeAttribute or TypeHelperAttribute references this format.
  calc_formats_is_unused(t.formats_id) AS is_unused,                            -- True when no attribute references this format — candidate for removal.
  calc_formats_owner_name(t.formats_id) AS owner_name                           -- Owner of this Format, passed through from Formats.Owner. Symmetry with TypeVersions.OwnerName / EnumVersions.OwnerName so list views render owner uniformly.
FROM formats t;

-- ----------------------------------------------------------------------------
-- vw_format_examples: Per-format examples and counterexamples (with order preserved). Sourced from format YAML 'examples' and 'counterexamples' arrays.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE VIEW vw_format_examples WITH (security_invoker = ON) AS
SELECT
  t.format_examples_id,                                                         -- Primary key (auto-synthesized: FormatExamples had no field named 'Id' or ending in 'Id').
  calc_format_examples_name(t.format_examples_id) AS name,                      -- Compound key combining the parent format, ordering index, and counterexample flag.
  t.format,                                                                     -- Foreign key to the parent Format.
  t.idx,                                                                        -- Preserves YAML ordering (0-indexed within examples or counterexamples).
  t.is_counter,                                                                 -- True if this is a counterexample (must NOT match), false if a positive example.
  t.value,                                                                      -- The example string itself.
  t.description,                                                                -- Optional description (e.g. YAML inline comment).
  calc_format_examples_example_kind(t.format_examples_id) AS example_kind       -- 'counter' when IsCounter is true, else 'positive'. Convenience label.
FROM format_examples t;

-- ----------------------------------------------------------------------------
-- vw_enums: Top-level enum definitions (name-level). Versioned enums have multiple EnumVersions; literal enums have one. Sourced from definitions/registry.yaml + definitions/enums/.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE VIEW vw_enums WITH (security_invoker = ON) AS
SELECT
  t.enums_id,                                                                   -- Primary key (auto-synthesized: Enums had no field named 'Id' or ending in 'Id').
  t.name,                                                                       -- Enum identifier slug. Example: 'gw1.actor.class'. Acts as the primary key.
  t.owner,                                                                      -- Owner of this enum.
  t.enum_type,                                                                  -- Either 'versioned' (additive-only multi-version) or 'literal' (single immutable version).
  t.value_type,                                                                 -- JSON Schema datatype of the enum's symbols. If present, SHALL be 'integer' and version YAML files SHALL have type: integer. If null, the enum SHALL be treated as string-valued.
  t.description,                                                                -- Name-level description (registry-level).
  t.replaced_by,                                                                -- Advisory pointer to another Enum that supersedes this one. The original Enum remains valid and queryable — ReplacedBy is just a hint to consumers about a preferred successor. NOT a state change; published versions are immutable.
  t.raw_json,                                                                   -- Escape hatch: any unmodeled YAML keys (e.g., x-gridworks extended_description). JSON-encoded.
  calc_enums_is_versioned(t.enums_id) AS is_versioned,                          -- True when EnumType is 'versioned' (additive-only multi-version enum).
  calc_enums_is_literal(t.enums_id) AS is_literal,                              -- True when EnumType is 'literal' (single immutable version, frozen vocabulary).
  calc_enums_is_integer_valued(t.enums_id) AS is_integer_valued,                -- True when ValueType is 'integer' (otherwise the enum's symbols are strings).
  calc_enums_version_count(t.enums_id) AS version_count,                        -- Number of EnumVersions for this enum.
  calc_enums_draft_version_count(t.enums_id) AS draft_version_count,            -- Number of EnumVersions of this Word with Status='draft'.
  calc_enums_published_version_count(t.enums_id) AS published_version_count,    -- Number of published EnumVersions.
  calc_enums_has_drafts(t.enums_id) AS has_drafts,                              -- True iff this Word has at least one draft Definition.
  calc_enums_first_created(t.enums_id) AS first_created,                        -- When the first EnumVersion for this Word was created.
  calc_enums_last_modified(t.enums_id) AS last_modified                         -- Latest EnumVersions.Created among this Word's Definitions.
FROM enums t;

-- ----------------------------------------------------------------------------
-- vw_enum_versions: Specific versions of an enum. Each enum can have multiple versions (e.g. gw1.actor.class has versions 009, 010, 011).
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE VIEW vw_enum_versions WITH (security_invoker = ON) AS
SELECT
  t.enum_versions_id,                                                           -- Primary key (auto-synthesized: EnumVersions had no field named 'Id' or ending in 'Id').
  calc_enum_versions_name(t.enum_versions_id) AS name,                          -- Compound key: <enum-name>/<version>.
  t.enum,                                                                       -- Foreign key to the parent Enum.
  t.version,                                                                    -- Three-digit version string. Example: '007'.
  t.schema_url,                                                                 -- Schema URL from JSON-Schema $id.
  t.title,                                                                      -- Human-readable title.
  t.description,                                                                -- Version-specific description.
  t.default_symbol,                                                             -- The default symbol value for this version.
  t.status,                                                                     -- Lifecycle status. One of 'draft' (still being designed; mutable) or 'published' (promoted; immutable thereafter). Versions never leave 'published' — successors are introduced as new versions, optionally pointed at via the parent Word's ReplacedBy.
  t.created,                                                                    -- Creation timestamp from registry.yaml.
  t.raw_json,                                                                   -- Escape hatch: any unmodeled YAML keys (e.g., type: integer for non-string enums, x-gridworks extended_description). JSON-encoded.
  calc_enum_versions_is_published(t.enum_versions_id) AS is_published,          -- True when Status is 'published'.
  calc_enum_versions_is_draft(t.enum_versions_id) AS is_draft,                  -- True when Status is 'draft'. Drives the Editor's 'Edit unlocked' affordance.
  calc_enum_versions_has_default_symbol(t.enum_versions_id) AS has_default_symbol,-- True when DefaultSymbol is set on this version.
  calc_enum_versions_value_count(t.enum_versions_id) AS value_count,            -- Number of EnumValues (symbols) declared in this version.
  calc_enum_versions_type_attribute_usage_count(t.enum_versions_id) AS type_attribute_usage_count,-- Number of TypeAttributes that point at this EnumVersion via EnumVersionRef.
  calc_enum_versions_type_helper_attribute_usage_count(t.enum_versions_id) AS type_helper_attribute_usage_count,-- Number of TypeHelperAttributes that point at this EnumVersion via EnumVersionRef.
  calc_enum_versions_outgoing_projection_count(t.enum_versions_id) AS outgoing_projection_count,-- Number of Projections starting from this version (i.e. where this is FromEnumVersion).
  calc_enum_versions_incoming_projection_count(t.enum_versions_id) AS incoming_projection_count,-- Number of Projections landing on this version (i.e. where this is ToEnumVersion).
  calc_enum_versions_outgoing_upgrade_count(t.enum_versions_id) AS outgoing_upgrade_count,-- Number of EnumUpgrades that bump from this version.
  calc_enum_versions_upgrade_template_out_count(t.enum_versions_id) AS upgrade_template_out_count,-- Number of upgrade Templates whose UpgradeFromEnumVersion is this EnumVersion.
  calc_enum_versions_has_upgrade_template(t.enum_versions_id) AS has_upgrade_template,-- True iff this EnumVersion has at least one outgoing upgrade template wired in.
  calc_enum_versions_incoming_upgrade_count(t.enum_versions_id) AS incoming_upgrade_count,-- Number of EnumUpgrades that bump to this version.
  calc_enum_versions_type_upgrade_op_usage_count(t.enum_versions_id) AS type_upgrade_op_usage_count,-- Number of TypeUpgradeOps referencing this version (via EnumVersionRef on EnumVersionBump / CoerceToEnum ops).
  calc_enum_versions_total_attribute_usage_count(t.enum_versions_id) AS total_attribute_usage_count,-- Total references across TypeAttributes + TypeHelperAttributes.
  calc_enum_versions_is_used_by_attributes(t.enum_versions_id) AS is_used_by_attributes,-- True when at least one attribute references this enum version.
  calc_enum_versions_has_incoming_projection(t.enum_versions_id) AS has_incoming_projection,-- True when at least one Projection lands on this version.
  calc_enum_versions_has_outgoing_projection(t.enum_versions_id) AS has_outgoing_projection,-- True when at least one Projection starts from this version.
  calc_enum_versions_has_incoming_upgrade(t.enum_versions_id) AS has_incoming_upgrade,-- True when at least one EnumUpgrade bumps to this version (this version was reached from a predecessor).
  calc_enum_versions_has_outgoing_upgrade(t.enum_versions_id) AS has_outgoing_upgrade,-- True when at least one EnumUpgrade bumps from this version (this version has a successor).
  calc_enum_versions_is_root(t.enum_versions_id) AS is_root,                    -- True when this version has no incoming upgrade — it was created fresh, not bumped from a predecessor.
  calc_enum_versions_is_leaf(t.enum_versions_id) AS is_leaf,                    -- True when this version has no outgoing upgrade — it has no successor and is a tip of the version chain.
  calc_enum_versions_owner_name(t.enum_versions_id) AS owner_name,              -- Owner of this EnumVersion's Word, passed through from Enums.Owner.
  calc_enum_versions_word_description(t.enum_versions_id) AS word_description,  -- Description of the parent Enum.
  t.last_modified,                                                              -- Most recent edit to this EnumVersion or its child EnumValues.
  t.promoted_at,                                                                -- When Status flipped from draft to active.
  calc_enum_versions_is_promotable(t.enum_versions_id) AS is_promotable         -- True iff this draft EnumVersion can be promoted: it is a draft and has at least one symbol.
FROM enum_versions t;

-- ----------------------------------------------------------------------------
-- vw_enum_values: Individual symbol values within an EnumVersion (with order preserved and per-symbol descriptions).
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE VIEW vw_enum_values WITH (security_invoker = ON) AS
SELECT
  t.enum_values_id,                                                             -- Primary key (auto-synthesized: EnumValues had no field named 'Id' or ending in 'Id').
  calc_enum_values_name(t.enum_values_id) AS name,                              -- Compound key: <enum-version>:<symbol>.
  t.enum_version,                                                               -- Foreign key to the parent EnumVersion.
  t.symbol,                                                                     -- The literal symbol value, e.g. 'Power'.
  t.idx,                                                                        -- Preserves YAML ordering of symbols.
  t.description,                                                                -- Per-symbol description from value_descriptions map.
  calc_enum_values_has_description(t.enum_values_id) AS has_description         -- True when a per-symbol Description is present.
FROM enum_values t;

-- ----------------------------------------------------------------------------
-- vw_types: Top-level type definitions (name-level). Each type can have multiple TypeVersions. Sourced from definitions/registry.yaml + definitions/types/.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE VIEW vw_types WITH (security_invoker = ON) AS
SELECT
  t.types_id,                                                                   -- Primary key (auto-synthesized: Types had no field named 'Id' or ending in 'Id').
  t.name,                                                                       -- Type identifier slug. Example: 'report'. Acts as the primary key.
  t.owner,                                                                      -- Owner of this type.
  t.title,                                                                      -- Name-level title.
  t.description,                                                                -- Name-level description.
  t.replaced_by,                                                                -- Advisory pointer to another Type that supersedes this one. The original Type remains valid and queryable — ReplacedBy is just a hint to consumers about a preferred successor. NOT a state change; published versions are immutable.
  t.python_class_name,                                                          -- Tier-2 placeholder: ODXML-derived Python class name (populated when ODXML data absorbs in).
  t.make_data_class,                                                            -- Tier-2 placeholder: ODXML invariant.
  t.is_cac,                                                                     -- Tier-2 placeholder: ODXML invariant (component access control marker).
  t.is_component,                                                               -- Tier-2 placeholder: ODXML invariant.
  calc_types_version_count(t.types_id) AS version_count,                        -- Number of TypeVersions for this type.
  calc_types_draft_version_count(t.types_id) AS draft_version_count,            -- Number of TypeVersions of this Word with Status='draft'. Drives 'drafts open' badge on Word cards.
  calc_types_published_version_count(t.types_id) AS published_version_count,    -- Number of published TypeVersions.
  calc_types_has_drafts(t.types_id) AS has_drafts,                              -- True iff this Word has at least one draft Definition. Drives the amber 'drafts open' badge on Word rows.
  calc_types_first_created(t.types_id) AS first_created,                        -- When the first Definition for this Word was created. Drives 'Word age' displays.
  calc_types_last_modified(t.types_id) AS last_modified                         -- Latest TypeVersions.Created among this Word's Definitions. Drives 'recently active' sort.
FROM types t;

-- ----------------------------------------------------------------------------
-- vw_type_versions: Specific versions of a type. Each declares its JSON-Schema shape. Versions follow a 3-digit suffix in the YAML files.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE VIEW vw_type_versions WITH (security_invoker = ON) AS
SELECT
  t.type_versions_id,                                                           -- Primary key (auto-synthesized: TypeVersions had no field named 'Id' or ending in 'Id').
  calc_type_versions_name(t.type_versions_id) AS name,                          -- Compound key: <type-name>/<version>.
  t.type,                                                                       -- Foreign key to the parent Type.
  t.version,                                                                    -- Three-digit version string. Example: '002'.
  t.schema_url,                                                                 -- Schema URL from JSON-Schema $id.
  t.title,                                                                      -- Human-readable title.
  t.description,                                                                -- Version-specific description.
  t.extra_allowed,                                                              -- From JSON-Schema additionalProperties (true=open, false=closed).
  t.status,                                                                     -- Lifecycle status. One of 'draft' (still being designed; mutable) or 'published' (promoted; immutable thereafter). Versions never leave 'published' — successors are introduced as new versions, optionally pointed at via the parent Word's ReplacedBy.
  t.created,                                                                    -- Creation timestamp.
  t.raw_json,                                                                   -- Escape hatch: unmodeled top-level JSON-Schema fields (if/then/else, conditionals, etc.).
  calc_type_versions_is_published(t.type_versions_id) AS is_published,          -- True when Status is 'published'.
  calc_type_versions_is_draft(t.type_versions_id) AS is_draft,                  -- True when Status is 'draft'. Drives the Editor's 'Edit unlocked' affordance.
  calc_type_versions_is_closed(t.type_versions_id) AS is_closed,                -- True when ExtraAllowed is FALSE (additionalProperties: false in JSON-Schema).
  calc_type_versions_attribute_count(t.type_versions_id) AS attribute_count,    -- Number of TypeAttributes declared on this version.
  calc_type_versions_required_attribute_count(t.type_versions_id) AS required_attribute_count,-- Number of TypeAttributes on this version where IsRequired=true.
  calc_type_versions_axiom_count(t.type_versions_id) AS axiom_count,            -- Number of natural-language axioms declared on this version.
  calc_type_versions_axiom_template_count(t.type_versions_id) AS axiom_template_count,-- Number of axiom Templates whose AxiomTypeVersion is this TypeVersion.
  calc_type_versions_has_axiom_template(t.type_versions_id) AS has_axiom_template,-- True iff this TypeVersion has at least one axiom template wired in. Required for runtime generation when AxiomCount > 0.
  calc_type_versions_example_count(t.type_versions_id) AS example_count,        -- Number of TypeExamples attached to this version.
  calc_type_versions_type_attribute_as_subtype_count(t.type_versions_id) AS type_attribute_as_subtype_count,-- Number of TypeAttributes that nest this version as a sub-type via SubTypeVersionRef.
  calc_type_versions_type_helper_attribute_as_subtype_count(t.type_versions_id) AS type_helper_attribute_as_subtype_count,-- Number of TypeHelperAttributes that nest this version as a sub-type via SubTypeVersionRef.
  calc_type_versions_outgoing_upgrade_count(t.type_versions_id) AS outgoing_upgrade_count,-- Number of TypeUpgrades that bump from this version (this version has a successor).
  calc_type_versions_upgrade_template_out_count(t.type_versions_id) AS upgrade_template_out_count,-- Number of upgrade Templates whose UpgradeFromTypeVersion is this TypeVersion (i.e. templates emanating from here).
  calc_type_versions_has_upgrade_template(t.type_versions_id) AS has_upgrade_template,-- True iff this TypeVersion has at least one outgoing upgrade template wired in. Required for runtime generation when OutgoingUpgradeCount > 0.
  calc_type_versions_incoming_upgrade_count(t.type_versions_id) AS incoming_upgrade_count,-- Number of TypeUpgrades that bump to this version (this version was reached from a predecessor).
  calc_type_versions_originated_helper_count(t.type_versions_id) AS originated_helper_count,-- Number of TypeHelpers whose YAML body originally introduced them in this version.
  calc_type_versions_total_subtype_usage_count(t.type_versions_id) AS total_subtype_usage_count,-- Total nest-as-subtype references across TypeAttributes + TypeHelperAttributes.
  calc_type_versions_is_used_as_subtype(t.type_versions_id) AS is_used_as_subtype,-- True when at least one attribute nests this version as a sub-type.
  calc_type_versions_has_incoming_upgrade(t.type_versions_id) AS has_incoming_upgrade,-- True when at least one TypeUpgrade bumps to this version.
  calc_type_versions_has_outgoing_upgrade(t.type_versions_id) AS has_outgoing_upgrade,-- True when at least one TypeUpgrade bumps from this version (this version has a successor).
  calc_type_versions_is_root(t.type_versions_id) AS is_root,                    -- True when this version has no incoming upgrade — it was created fresh.
  calc_type_versions_is_leaf(t.type_versions_id) AS is_leaf,                    -- True when this version has no outgoing upgrade — a tip of the version chain.
  calc_type_versions_originates_helpers(t.type_versions_id) AS originates_helpers,-- True when at least one TypeHelper was originally introduced by this version's YAML body.
  calc_type_versions_owner_name(t.type_versions_id) AS owner_name,              -- Owner of this Definition's Word, passed through from Types.Owner. Lets list views render owner without joining.
  calc_type_versions_word_title(t.type_versions_id) AS word_title,              -- Title of this Definition's Word, passed through from Types.Title. Used in breadcrumbs.
  t.last_modified,                                                              -- Most recent edit to this Definition or any of its child rows. Null until the editor lands. Drives Activity-feed sort.
  t.promoted_at,                                                                -- When Status flipped from draft to active. Null for never-promoted drafts. Activity feed renders 'promoted on...' distinct from 'created on...'.
  calc_type_versions_is_promotable(t.type_versions_id) AS is_promotable         -- True iff this TypeVersion is a draft with at least one attribute defined — i.e., ready to promote to published.
FROM type_versions t;

-- ----------------------------------------------------------------------------
-- vw_type_attributes: The shape-of-record for every property declared on a TypeVersion. Polymorphic via mutually-exclusive FK columns: at most one of FormatRef / EnumVersionRef / SubTypeVersionRef / HelperRef is non-null per row.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE VIEW vw_type_attributes WITH (security_invoker = ON) AS
SELECT
  t.type_attributes_id,                                                         -- Primary key (auto-synthesized: TypeAttributes had no field named 'Id' or ending in 'Id').
  calc_type_attributes_name(t.type_attributes_id) AS name,                      -- Compound key: <type-version>.<attribute-name>.
  t.type_version,                                                               -- Foreign key to the owning TypeVersion.
  t.attribute_name,                                                             -- Property key in the JSON-Schema.
  t.idx,                                                                        -- Preserves YAML ordering of properties.
  t.description,                                                                -- Per-attribute description from JSON-Schema.
  t."default",                                                                  -- JSON-encoded default value for this attribute (e.g., '"002"', '12', 'false', '1.0', 'null'). Mirrors the JSON Schema 'default:' keyword. Encode as JSON string for typing-uniformity (matches TypeUpgradeOps.LiteralValue convention).
  t.is_required,                                                                -- Derived from the parent TypeVersion's 'required' array.
  t.is_list,                                                                    -- True if attribute is type=array. Refs then describe the item type.
  t.primitive_type,                                                             -- Primitive JSON type when none of the *Ref columns apply: string, integer, number, boolean, null.
  t.format_ref,                                                                 -- FK to a Format, when this attribute uses a $ref to /formats/X.
  t.enum_version_ref,                                                           -- FK to an EnumVersion, when this attribute uses a $ref to /enums/X/NNN.
  t.sub_type_version_ref,                                                       -- FK to another TypeVersion, when this attribute uses a $ref to /types/X/NNN.
  t.helper_ref,                                                                 -- FK to a TypeHelper, when this attribute is an inline-nested object auto-promoted to a helper.
  t.raw_json,                                                                   -- Escape hatch: unmodeled JSON-Schema specifics, including oneOf bodies (v1 parking lot for n=1 cases).
  calc_type_attributes_is_optional(t.type_attributes_id) AS is_optional,        -- True when this attribute is NOT required (inverse of IsRequired). Convenience predicate.
  calc_type_attributes_has_default(t.type_attributes_id) AS has_default,        -- True when a JSON-encoded Default value is present for this attribute.
  calc_type_attributes_ref_kind(t.type_attributes_id) AS ref_kind,              -- Which $ref family this attribute uses: 'format', 'enum', 'subtype', 'helper', or 'primitive' when only PrimitiveType is set.
  calc_type_attributes_ref_enum_is_published(t.type_attributes_id) AS ref_enum_is_published,-- Whether the EnumVersionRef target has Status='published'. Null when EnumVersionRef is unset.
  calc_type_attributes_ref_enum_is_draft(t.type_attributes_id) AS ref_enum_is_draft,-- Whether the EnumVersionRef target is still a draft. Promoting a draft TypeVersion that points at a draft EnumVersion is not allowed.
  calc_type_attributes_ref_subtype_is_published(t.type_attributes_id) AS ref_subtype_is_published,-- Whether the SubTypeVersionRef target has Status='published'.
  calc_type_attributes_ref_subtype_is_draft(t.type_attributes_id) AS ref_subtype_is_draft-- Whether the SubTypeVersionRef target is still a draft.
FROM type_attributes t;

-- ----------------------------------------------------------------------------
-- vw_type_examples: Per-TypeVersion full-instance examples (with order preserved). Sourced from JSON-Schema 'examples' arrays.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE VIEW vw_type_examples WITH (security_invoker = ON) AS
SELECT
  t.type_examples_id,                                                           -- Primary key (auto-synthesized: TypeExamples had no field named 'Id' or ending in 'Id').
  calc_type_examples_name(t.type_examples_id) AS name,                          -- Compound key: <type-version>[<idx>].
  t.type_version,                                                               -- Foreign key to the parent TypeVersion.
  t.idx,                                                                        -- Preserves YAML ordering.
  t.example_json,                                                               -- Full instance example, serialized as JSON string.
  calc_type_examples_owner_name(t.type_examples_id) AS owner_name               -- Owner passthrough.
FROM type_examples t;

-- ----------------------------------------------------------------------------
-- vw_type_axioms: Per-TypeVersion axioms (numbered invariants stated in natural language). Sourced from x-gridworks.axioms in YAML.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE VIEW vw_type_axioms WITH (security_invoker = ON) AS
SELECT
  t.type_axioms_id,                                                             -- Primary key (auto-synthesized: TypeAxioms had no field named 'Id' or ending in 'Id').
  calc_type_axioms_name(t.type_axioms_id) AS name,                              -- Compound key: <type-version>.axiom<number>.<axiom-name>.
  t.type_version,                                                               -- Foreign key to the parent TypeVersion.
  t.number,                                                                     -- Axiom number from YAML.
  t.axiom_name,                                                                 -- Axiom name from YAML.
  t.statement,                                                                  -- Axiom statement (the natural-language invariant).
  calc_type_axioms_has_statement(t.type_axioms_id) AS has_statement,            -- True when the axiom carries a non-empty Statement.
  calc_type_axioms_owner_name(t.type_axioms_id) AS owner_name                   -- Owner passthrough via TypeVersion → Type → Owner.
FROM type_axioms t;

-- ----------------------------------------------------------------------------
-- vw_type_helpers: Non-versioned reusable subtypes auto-promoted from inline nested objects (array items, oneOf branches). Synthesized at migration time. Origin metadata preserves provenance for round-trip YAML emission.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE VIEW vw_type_helpers WITH (security_invoker = ON) AS
SELECT
  t.type_helpers_id,                                                            -- Primary key (auto-synthesized: TypeHelpers had no field named 'Id' or ending in 'Id').
  t.name,                                                                       -- Synthesized helper name. Example: 'scada.control.capabilities.RelayNode'. Acts as the primary key.
  t.title,                                                                      -- From inline 'description' if present.
  t.description,                                                                -- Description of the helper.
  t.extra_allowed,                                                              -- From inline additionalProperties.
  t.origin_type_version,                                                        -- The TypeVersion whose YAML body originally introduced this helper.
  t.origin_path,                                                                -- JSON-Pointer-ish path within origin (e.g. '/properties/RelayNodes/items') — used to re-inline on YAML emit.
  calc_type_helpers_attribute_count(t.type_helpers_id) AS attribute_count,      -- Number of TypeHelperAttributes declared on this helper.
  calc_type_helpers_required_attribute_count(t.type_helpers_id) AS required_attribute_count,-- Number of TypeHelperAttributes on this helper where IsRequired=true.
  calc_type_helpers_is_closed(t.type_helpers_id) AS is_closed,                  -- True when ExtraAllowed is FALSE (the helper rejects unknown properties).
  calc_type_helpers_type_attribute_usage_count(t.type_helpers_id) AS type_attribute_usage_count,-- Number of TypeAttributes that point at this helper via HelperRef.
  calc_type_helpers_type_helper_attribute_usage_count(t.type_helpers_id) AS type_helper_attribute_usage_count,-- Number of TypeHelperAttributes that point at this helper via HelperRef (nested helpers).
  calc_type_helpers_total_usage_count(t.type_helpers_id) AS total_usage_count,  -- Total references across TypeAttributes + TypeHelperAttributes (nested helpers).
  calc_type_helpers_is_used(t.type_helpers_id) AS is_used,                      -- True when at least one attribute references this helper.
  calc_type_helpers_origin_owner_name(t.type_helpers_id) AS origin_owner_name,  -- Owner of the helper's origin Definition.
  calc_type_helpers_origin_type_name(t.type_helpers_id) AS origin_type_name,    -- Word name of the helper's origin Definition.
  calc_type_helpers_is_origin_draft(t.type_helpers_id) AS is_origin_draft,      -- Whether the origin Definition is still a draft. Gates the 'Edit helper' CTA in §9c.
  calc_type_helpers_is_origin_active(t.type_helpers_id) AS is_origin_active     -- Whether the origin Definition is active.
FROM type_helpers t;

-- ----------------------------------------------------------------------------
-- vw_type_helper_attributes: Properties of a TypeHelper. Same shape as TypeAttributes minus the oneOf machinery, since helpers are not versioned.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE VIEW vw_type_helper_attributes WITH (security_invoker = ON) AS
SELECT
  t.type_helper_attributes_id,                                                  -- Primary key (auto-synthesized: TypeHelperAttributes had no field named 'Id' or ending in 'Id').
  calc_type_helper_attributes_name(t.type_helper_attributes_id) AS name,        -- Compound key: <type-helper>.<attribute-name>.
  t.type_helper,                                                                -- Foreign key to the parent TypeHelper.
  t.attribute_name,                                                             -- Property key.
  t.idx,                                                                        -- Preserves YAML ordering.
  t.description,                                                                -- Per-attribute description.
  t.is_required,                                                                -- From inline 'required' array.
  t.is_list,                                                                    -- True if type=array.
  t.primitive_type,                                                             -- Primitive JSON type when none of the *Ref columns apply.
  t.format_ref,                                                                 -- FK to a Format, if this attribute references one.
  t.enum_version_ref,                                                           -- FK to an EnumVersion, if this attribute references one.
  t.sub_type_version_ref,                                                       -- FK to a TypeVersion, if this attribute references one.
  t.helper_ref,                                                                 -- FK to another TypeHelper (supports nested helpers).
  t.raw_json,                                                                   -- Escape hatch for unmodeled JSON-Schema specifics.
  calc_type_helper_attributes_is_optional(t.type_helper_attributes_id) AS is_optional,-- True when this attribute is NOT required (inverse of IsRequired). Convenience predicate.
  calc_type_helper_attributes_ref_kind(t.type_helper_attributes_id) AS ref_kind,-- Which $ref family this attribute uses: 'format', 'enum', 'subtype', 'helper', or 'primitive'.
  calc_type_helper_attributes_ref_enum_is_draft(t.type_helper_attributes_id) AS ref_enum_is_draft,-- Whether the EnumVersionRef target is still a draft.
  calc_type_helper_attributes_ref_subtype_is_draft(t.type_helper_attributes_id) AS ref_subtype_is_draft-- Whether the SubTypeVersionRef target is still a draft.
FROM type_helper_attributes t;

-- ----------------------------------------------------------------------------
-- vw_projections: Named, deterministic enum-to-enum (or value-to-value) mappings used by AddProjected upgrade ops. Today: SpaceheatTelemetryQuantityProjection, Gw1UnitQuantityProjection.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE VIEW vw_projections WITH (security_invoker = ON) AS
SELECT
  t.projections_id,                                                             -- Primary key (auto-synthesized: Projections had no field named 'Id' or ending in 'Id').
  t.name,                                                                       -- Projection name. Example: 'SpaceheatTelemetryQuantityProjection'. Acts as the primary key.
  t.description,                                                                -- Description of what the projection computes.
  t.from_enum_version,                                                          -- Source enum version.
  t.to_enum_version,                                                            -- Target enum version.
  t.raw_script,                                                                 -- Populated only if the projection isn't a flat lookup (escape hatch).
  calc_projections_mapping_count(t.projections_id) AS mapping_count,            -- Number of ProjectionMappings (FromSymbol -> ToSymbol pairs) declared on this projection.
  calc_projections_is_scripted(t.projections_id) AS is_scripted,                -- True when RawScript is set — projection isn't a flat lookup and falls back to a script.
  calc_projections_is_flat_lookup(t.projections_id) AS is_flat_lookup,          -- True when this projection is a pure flat lookup (no RawScript). The common, well-behaved case.
  calc_projections_type_upgrade_op_usage_count(t.projections_id) AS type_upgrade_op_usage_count,-- Number of TypeUpgradeOps referencing this projection via ProjectionRef (typically AddProjected ops).
  calc_projections_is_used_in_upgrades(t.projections_id) AS is_used_in_upgrades,-- True when at least one TypeUpgradeOp uses this projection (via AddProjected).
  calc_projections_from_owner_name(t.projections_id) AS from_owner_name,        -- Owner of the FromEnumVersion.
  calc_projections_to_owner_name(t.projections_id) AS to_owner_name,            -- Owner of the ToEnumVersion.
  calc_projections_from_enum_name(t.projections_id) AS from_enum_name,          -- Enum name of the FromEnumVersion.
  calc_projections_to_enum_name(t.projections_id) AS to_enum_name,              -- Enum name of the ToEnumVersion.
  calc_projections_from_is_draft(t.projections_id) AS from_is_draft,            -- Whether the FromEnumVersion is still a draft.
  calc_projections_to_is_draft(t.projections_id) AS to_is_draft,                -- Whether the ToEnumVersion is still a draft.
  calc_projections_has_draft_endpoints(t.projections_id) AS has_draft_endpoints,-- True iff either endpoint EnumVersion is still a draft.
  calc_projections_is_cross_owner(t.projections_id) AS is_cross_owner,          -- True iff the projection crosses two different owners' enums (a meaningful editorial signal).
  calc_projections_is_cross_enum(t.projections_id) AS is_cross_enum             -- True iff the projection crosses two different Enums (vs versions of the same Enum).
FROM projections t;

-- ----------------------------------------------------------------------------
-- vw_projection_mappings: Per-symbol mappings for flat-lookup Projections. Empty when the parent Projection uses RawScript.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE VIEW vw_projection_mappings WITH (security_invoker = ON) AS
SELECT
  t.projection_mappings_id,                                                     -- Primary key (auto-synthesized: ProjectionMappings had no field named 'Id' or ending in 'Id').
  calc_projection_mappings_name(t.projection_mappings_id) AS name,              -- Compound key: <projection>:<from-symbol>.
  t.projection,                                                                 -- Foreign key to the parent Projection.
  t.from_symbol,                                                                -- Source enum symbol.
  t.to_symbol,                                                                  -- Target enum symbol.
  t.description,                                                                -- Optional per-mapping description.
  calc_projection_mappings_is_removal(t.projection_mappings_id) AS is_removal,  -- True when ToSymbol is empty/null — the source symbol is dropped during projection.
  calc_projection_mappings_is_identity(t.projection_mappings_id) AS is_identity -- True when FromSymbol equals ToSymbol — the projection passes the symbol through unchanged.
FROM projection_mappings t;

-- ----------------------------------------------------------------------------
-- vw_type_upgrades: One row per ordered version pair (N, N+1) for a given type. Mirrors src/sema/runtime/types/old_versions/<type>_<NNN>.py.upgrade() methods.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE VIEW vw_type_upgrades WITH (security_invoker = ON) AS
SELECT
  t.type_upgrades_id,                                                           -- Primary key (auto-synthesized: TypeUpgrades had no field named 'Id' or ending in 'Id').
  calc_type_upgrades_name(t.type_upgrades_id) AS name,                          -- Compound key: <from-type-version> -> <to-type-version>.
  t.from_type_version,                                                          -- Source TypeVersion.
  t.to_type_version,                                                            -- Target TypeVersion.
  t.description,                                                                -- Description (typically the docstring summary from the .py method).
  t.raw_script,                                                                 -- Whole-method escape hatch when no clean op decomposition is possible. Prefer per-op RawScript on TypeUpgradeOps.
  calc_type_upgrades_op_count(t.type_upgrades_id) AS op_count,                  -- Number of TypeUpgradeOps that compose this upgrade.
  calc_type_upgrades_is_scripted(t.type_upgrades_id) AS is_scripted,            -- True when RawScript is set — the upgrade is a whole-method escape hatch instead of a clean op decomposition.
  calc_type_upgrades_is_decomposed(t.type_upgrades_id) AS is_decomposed,        -- True when RawScript is empty — the upgrade is composed of structured TypeUpgradeOps. The desired form.
  calc_type_upgrades_from_word(t.type_upgrades_id) AS from_word,                -- Word name of FromTypeVersion (should equal ToWord — IsCrossWord catches violations).
  calc_type_upgrades_to_word(t.type_upgrades_id) AS to_word,                    -- Word name of ToTypeVersion.
  calc_type_upgrades_from_version(t.type_upgrades_id) AS from_version,          -- Version string (e.g. '000') of FromTypeVersion.
  calc_type_upgrades_to_version(t.type_upgrades_id) AS to_version,              -- Version string (e.g. '001') of ToTypeVersion.
  calc_type_upgrades_owner_name(t.type_upgrades_id) AS owner_name,              -- Owner of the upgrade (passes through FromTypeVersion).
  calc_type_upgrades_is_cross_word(t.type_upgrades_id) AS is_cross_word         -- True iff the upgrade crosses two different Words — should always be FALSE; flags malformed upgrades.
FROM type_upgrades t;

-- ----------------------------------------------------------------------------
-- vw_type_upgrade_ops: Atomic operations within a TypeUpgrade. Most upgrades decompose into 1-4 ops. OpKind controls semantics (vocabulary: AddOptional, AddWithDefault, Remove, RequireToOptional, OptionalToRequire, EnumVersionBump, CoerceToEnum, UpgradeChild, UpgradeChildIf, UpgradeListItems, UpgradeListItemsIf, AddProjected, Custom).
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE VIEW vw_type_upgrade_ops WITH (security_invoker = ON) AS
SELECT
  t.type_upgrade_ops_id,                                                        -- Primary key (auto-synthesized: TypeUpgradeOps had no field named 'Id' or ending in 'Id').
  calc_type_upgrade_ops_name(t.type_upgrade_ops_id) AS name,                    -- Compound key: <type-upgrade>#<idx>.
  t.type_upgrade,                                                               -- Foreign key to the parent TypeUpgrade.
  t.idx,                                                                        -- Execution order within the upgrade.
  t.op_kind,                                                                    -- Op vocabulary: AddOptional, AddWithDefault, Remove, RequireToOptional, OptionalToRequire, EnumVersionBump, CoerceToEnum, UpgradeChild, UpgradeChildIf, UpgradeListItems, UpgradeListItemsIf, AddProjected, Custom.
  t.field_name,                                                                 -- The attribute name being touched (most ops).
  t.literal_value,                                                              -- JSON-encoded literal default (AddWithDefault) or source field name (AddProjected).
  t.from_version,                                                               -- Source version for conditional upgrades (UpgradeChildIf, UpgradeListItemsIf).
  t.to_version,                                                                 -- Target version for explicit version bumps.
  t.enum_version_ref,                                                           -- FK for enum-related ops (EnumVersionBump, CoerceToEnum).
  t.projection_ref,                                                             -- FK for AddProjected ops.
  t.raw_script,                                                                 -- Per-op Python escape hatch for Custom ops. Snippet runs in scope of `self` and `data` dict.
  t.description,                                                                -- Optional op-level description.
  calc_type_upgrade_ops_is_custom(t.type_upgrade_ops_id) AS is_custom,          -- True when OpKind is 'Custom' — falls back to per-op RawScript, the escape hatch.
  calc_type_upgrade_ops_has_raw_script(t.type_upgrade_ops_id) AS has_raw_script,-- True when this op carries an inline RawScript snippet (typically only Custom ops).
  calc_type_upgrade_ops_reference_kind(t.type_upgrade_ops_id) AS reference_kind -- Which cross-table reference this op carries: 'enum' (EnumVersionRef), 'projection' (ProjectionRef), or 'none'.
FROM type_upgrade_ops t;

-- ----------------------------------------------------------------------------
-- vw_enum_upgrades: Mirror of TypeUpgrades for enum value renames or splits when name preservation breaks. Today's 5 multi-version enums all preserved names, so this table starts empty.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE VIEW vw_enum_upgrades WITH (security_invoker = ON) AS
SELECT
  t.enum_upgrades_id,                                                           -- Primary key (auto-synthesized: EnumUpgrades had no field named 'Id' or ending in 'Id').
  calc_enum_upgrades_name(t.enum_upgrades_id) AS name,                          -- Compound key: <from-enum-version> -> <to-enum-version>.
  t.from_enum_version,                                                          -- Source EnumVersion.
  t.to_enum_version,                                                            -- Target EnumVersion.
  t.description,                                                                -- Description of the enum upgrade.
  t.raw_script,                                                                 -- Whole-upgrade escape hatch.
  calc_enum_upgrades_mapping_count(t.enum_upgrades_id) AS mapping_count,        -- Number of EnumUpgradeMappings that compose this upgrade.
  calc_enum_upgrades_is_scripted(t.enum_upgrades_id) AS is_scripted,            -- True when RawScript is set (whole-upgrade escape hatch).
  calc_enum_upgrades_is_decomposed(t.enum_upgrades_id) AS is_decomposed,        -- True when RawScript is empty — upgrade is composed of structured mappings.
  calc_enum_upgrades_from_word(t.enum_upgrades_id) AS from_word,                -- Enum name of FromEnumVersion.
  calc_enum_upgrades_to_word(t.enum_upgrades_id) AS to_word,                    -- Enum name of ToEnumVersion.
  calc_enum_upgrades_from_version(t.enum_upgrades_id) AS from_version,          -- Version of FromEnumVersion.
  calc_enum_upgrades_to_version(t.enum_upgrades_id) AS to_version,              -- Version of ToEnumVersion.
  calc_enum_upgrades_owner_name(t.enum_upgrades_id) AS owner_name,              -- Owner of the upgrade.
  calc_enum_upgrades_is_cross_word(t.enum_upgrades_id) AS is_cross_word         -- True iff the upgrade crosses two different Enum Words — flags malformed upgrades.
FROM enum_upgrades t;

-- ----------------------------------------------------------------------------
-- vw_enum_upgrade_mappings: Per-symbol value renames for an EnumUpgrade. Empty when the parent EnumUpgrade preserves all names.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE VIEW vw_enum_upgrade_mappings WITH (security_invoker = ON) AS
SELECT
  t.enum_upgrade_mappings_id,                                                   -- Primary key (auto-synthesized: EnumUpgradeMappings had no field named 'Id' or ending in 'Id').
  calc_enum_upgrade_mappings_name(t.enum_upgrade_mappings_id) AS name,          -- Compound key: <enum-upgrade>:<from-symbol>.
  t.enum_upgrade,                                                               -- Foreign key to the parent EnumUpgrade.
  t.from_symbol,                                                                -- Source enum symbol.
  t.to_symbol,                                                                  -- Target enum symbol (or empty/null when symbol is removed).
  t.description,                                                                -- Optional per-mapping description.
  calc_enum_upgrade_mappings_is_removal(t.enum_upgrade_mappings_id) AS is_removal,-- True when ToSymbol is empty/null — the source symbol is dropped in this upgrade.
  calc_enum_upgrade_mappings_is_identity(t.enum_upgrade_mappings_id) AS is_identity-- True when FromSymbol equals ToSymbol — the symbol passes through unchanged.
FROM enum_upgrade_mappings t;

-- ----------------------------------------------------------------------------
-- vw_app_users: Application users authenticated via magic-links. The Name field is the lowercased email — it is both the primary key and the value that the JWT 'email' claim resolves against. AppUsers are editing principals (who can sign in and act in the Explorer); they are independent of Owners (who own published artifacts in the registry).
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE VIEW vw_app_users WITH (security_invoker = ON) AS
SELECT
  t.app_users_id,                                                               -- Primary key (auto-synthesized: AppUsers had no field named 'Id' or ending in 'Id').
  t.name,                                                                       -- Lowercased email address. Acts as the primary key. The verified 'email' claim from a magic-links JWT must equal this value for the user to be recognized.
  t.display_name,                                                               -- Optional human-friendly display name shown in the Explorer UI.
  t.role,                                                                       -- App role. One of: 'admin' (full edit/promote rights once Phase 5 lands) or 'member' (read-only today). Word-level promotion to a finer-grained role table can land later as an additive change.
  t.notes,                                                                      -- Free-text notes — provenance, why-granted, whatever the registry maintainer wants future readers to know.
  t.created,                                                                    -- Creation timestamp.
  calc_app_users_is_admin(t.app_users_id) AS is_admin,                          -- True when Role is 'admin'. Drives admin-gated affordances in the Explorer and (eventually) RLS predicates.
  calc_app_users_is_member(t.app_users_id) AS is_member                         -- True when Role is 'member'. Inverse of IsAdmin while only two roles exist.
FROM app_users t;

-- ----------------------------------------------------------------------------
-- vw_seed_requests: Seed requests catalogued by the snapshot pipeline. Each row describes the inputs of one `effortless snapshot prepare`/`build` invocation — which Types/Enums to include and how to pin their versions. Mirrors the legacy seed YAML schema (see template_seed_request.yaml).
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE VIEW vw_seed_requests WITH (security_invoker = ON) AS
SELECT
  t.seed_requests_id,                                                           -- Primary key (auto-synthesized: SeedRequests had no field named 'Id' or ending in 'Id').
  t.name,                                                                       -- Identifier for this seed request (e.g. 'gridworks-spaceheat'). Acts as the primary key.
  t.owner,                                                                      -- Owner sponsoring this seed request.
  t.package_name,                                                               -- Python package name produced when this seed request is built (e.g. 'gridworks_sema').
  t.description,                                                                -- What this seed request covers and why.
  t.include_all_versions_default,                                               -- When true, entries default to include_all_versions=true unless overridden. Mirrors the top-level convenience flag in the legacy seed YAML.
  t.created,                                                                    -- When this seed request was added to the registry.
  calc_seed_requests_entry_count(t.seed_requests_id) AS entry_count,            -- Number of SeedRequestEntries belonging to this seed request.
  calc_seed_requests_snapshot_count(t.seed_requests_id) AS snapshot_count       -- Number of Snapshots built from this seed request.
FROM seed_requests t;

-- ----------------------------------------------------------------------------
-- vw_seed_request_entries: Individual targets within a SeedRequest. Each row is one Type or one Enum to include (Formats are never listed directly — they come in via type dependencies).
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE VIEW vw_seed_request_entries WITH (security_invoker = ON) AS
SELECT
  t.seed_request_entries_id,                                                    -- Primary key (auto-synthesized: SeedRequestEntries had no field named 'Id' or ending in 'Id').
  calc_seed_request_entries_name(t.seed_request_entries_id) AS name,            -- Composite identifier: SeedRequest:Kind:TargetName.
  t.seed_request,                                                               -- Parent SeedRequest.
  t.entry_kind,                                                                 -- What kind of registry word this entry pulls in. One of 'type', 'enum'. (Formats are never listed directly — they come in via type dependencies.)
  t.target_name,                                                                -- The Word's Name (e.g. 'synced.readings.bundle', 'relay.energization.state').
  t.include_all_versions,                                                       -- When true, expand all registry versions for this target. Mirrors `include_all_versions: true` in the seed YAML.
  t.versions,                                                                   -- Comma-separated explicit version list (e.g. '001,003'). Null/empty means 'use only the latest registry version' unless IncludeAllVersions is true.
  t.reason                                                                      -- Free-text why this target is in the request.
FROM seed_request_entries t;

-- ----------------------------------------------------------------------------
-- vw_snapshots: Built snapshots produced by the snapshot pipeline. Each row records one materialized `output/sema/<name>` directory plus pointers back to the SeedRequest that produced it.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE VIEW vw_snapshots WITH (security_invoker = ON) AS
SELECT
  t.snapshots_id,                                                               -- Primary key (auto-synthesized: Snapshots had no field named 'Id' or ending in 'Id').
  t.name,                                                                       -- Identifier for this snapshot build (e.g. 'gridworks-spaceheat@2026-05-13'). Acts as the primary key.
  t.seed_request,                                                               -- Seed request that produced this snapshot.
  t.built_at,                                                                   -- When this snapshot was built (UTC).
  t.output_path,                                                                -- Filesystem path where the snapshot was written (e.g. 'output/sema/gridworks-spaceheat').
  t.package_import_root,                                                        -- Python import root used for the generated SDK (e.g. 'gridworks_sema').
  t.status,                                                                     -- One of 'prepared' (definitions restricted + indexes written), 'built' (runtime generated), or 'published' (released externally).
  t.commit_sha,                                                                 -- Git commit sha of the rulebook used to build this snapshot.
  calc_snapshots_local_name_count(t.snapshots_id) AS local_name_count           -- Count of LocalNames carried by this snapshot.
FROM snapshots t;

-- ----------------------------------------------------------------------------
-- vw_local_names: Per-snapshot local-naming overrides. Models `local_names.yaml` inside a snapshot — each row pairs a canonical registry name with the local rebranding used inside the snapshot's generated package.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE VIEW vw_local_names WITH (security_invoker = ON) AS
SELECT
  t.local_names_id,                                                             -- Primary key (auto-synthesized: LocalNames had no field named 'Id' or ending in 'Id').
  calc_local_names_name(t.local_names_id) AS name,                              -- Composite identifier: Snapshot/Kind/CanonicalName.
  t.snapshot,                                                                   -- Parent Snapshot.
  t.kind,                                                                       -- One of 'type', 'enum', 'format'.
  t.canonical_name,                                                             -- The full canonical name as it appears in the registry (e.g. 'synced.readings.bundle').
  t.local_name                                                                  -- The locally-rebranded name within this snapshot's local_names.yaml. Often identical to CanonicalName when no rebranding is applied.
FROM local_names t;

-- ----------------------------------------------------------------------------
-- vw_index_builders: Catalogue of the Python builder scripts orchestrated by scripts/build_indexes.sh. The rulebook describes the build sequence (run order, output path, re-run pass) rather than the output files themselves — those are downstream artifacts.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE VIEW vw_index_builders WITH (security_invoker = ON) AS
SELECT
  t.index_builders_id,                                                          -- Primary key (auto-synthesized: IndexBuilders had no field named 'Id' or ending in 'Id').
  t.name,                                                                       -- Builder name (e.g. 'build_public_registry'). Primary key.
  t.script_path,                                                                -- Path to the Python script that implements this builder (relative to repo root).
  t.run_order,                                                                  -- Position in the orchestrated build sequence (lower runs first).
  t.output_path,                                                                -- Path of the YAML index file this builder emits (relative to repo root).
  t.inputs_description,                                                         -- Brief description of what this builder reads to produce its output.
  t.description,                                                                -- What the builder does and why it exists.
  t.rerun_at_end                                                                -- True iff this builder is re-run as a final pass after all other builders complete (currently only build_public_registry needs this, to incorporate facts surfaced by downstream builders).
FROM index_builders t;

-- ----------------------------------------------------------------------------
-- vw_templates: Generator templates that implement axiom and upgrade behavior. Runtime generation REQUIRES that every TypeVersion declaring an axiom (or upgrade) has a matching Templates row pointing at the corresponding `.jinja2` file (see runtime_generation/templates/).
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE VIEW vw_templates WITH (security_invoker = ON) AS
SELECT
  t.templates_id,                                                               -- Primary key (auto-synthesized: Templates had no field named 'Id' or ending in 'Id').
  t.name,                                                                       -- Composite template identifier. Convention: '<kind>:<owner-version-id>' (e.g. 'axiom:atn.bid/002', 'upgrade:bid/000->bid/002'). Primary key.
  t.kind,                                                                       -- Template kind. One of 'axiom' or 'upgrade'.
  t.path,                                                                       -- Path to the .jinja2 template file relative to repo root.
  t.language,                                                                   -- Target language. Currently always 'python'.
  t.status,                                                                     -- Template status: 'present' (file exists), 'missing' (declared but not yet scaffolded), 'deprecated'.
  t.axiom_type_version,                                                         -- When Kind='axiom': the TypeVersion this axiom implements.
  t.upgrade_from_type_version,                                                  -- When Kind='upgrade' between types: the source TypeVersion.
  t.upgrade_to_type_version,                                                    -- When Kind='upgrade' between types: the destination TypeVersion.
  t.upgrade_from_enum_version,                                                  -- When Kind='upgrade' between enums: the source EnumVersion.
  t.upgrade_to_enum_version,                                                    -- When Kind='upgrade' between enums: the destination EnumVersion.
  calc_templates_is_axiom(t.templates_id) AS is_axiom,                          -- True iff this template implements an axiom.
  calc_templates_is_type_upgrade(t.templates_id) AS is_type_upgrade,            -- True iff this template implements a type-version upgrade.
  calc_templates_is_enum_upgrade(t.templates_id) AS is_enum_upgrade             -- True iff this template implements an enum-version upgrade.
FROM templates t;

