-- ============================================================================
-- CREATE POLICIES - Row Level Security policies
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- ============================================================================

-- Enable RLS on all tables

ALTER TABLE owners ENABLE ROW LEVEL SECURITY;
ALTER TABLE formats ENABLE ROW LEVEL SECURITY;
ALTER TABLE format_examples ENABLE ROW LEVEL SECURITY;
ALTER TABLE enums ENABLE ROW LEVEL SECURITY;
ALTER TABLE enum_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE enum_values ENABLE ROW LEVEL SECURITY;
ALTER TABLE types ENABLE ROW LEVEL SECURITY;
ALTER TABLE type_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE type_attributes ENABLE ROW LEVEL SECURITY;
ALTER TABLE type_examples ENABLE ROW LEVEL SECURITY;
ALTER TABLE type_axioms ENABLE ROW LEVEL SECURITY;
ALTER TABLE type_helpers ENABLE ROW LEVEL SECURITY;
ALTER TABLE type_helper_attributes ENABLE ROW LEVEL SECURITY;
ALTER TABLE projections ENABLE ROW LEVEL SECURITY;
ALTER TABLE projection_mappings ENABLE ROW LEVEL SECURITY;
ALTER TABLE type_upgrades ENABLE ROW LEVEL SECURITY;
ALTER TABLE type_upgrade_ops ENABLE ROW LEVEL SECURITY;
ALTER TABLE enum_upgrades ENABLE ROW LEVEL SECURITY;
ALTER TABLE enum_upgrade_mappings ENABLE ROW LEVEL SECURITY;
ALTER TABLE erb_versions_test ENABLE ROW LEVEL SECURITY;

-- TODO: Add specific RLS policies based on your security requirements
-- Example:
-- CREATE POLICY "Users can view their own data" ON app_user
--   FOR SELECT USING (auth.uid() = user_id);

