-- ============================================================================
-- INSERT DATA - Load data from rulebook
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Owners: Entities (organizations or individuals) that own Types, Enums, and Formats. Sourced from definitions/owners.yaml.
-- ----------------------------------------------------------------------------
INSERT INTO owners (name, owner_type, contact, website, github, organization, description, support_policy, license)
VALUES ('gridworks-energy', 'organization', 'gridworks@gridworks-consulting.com', 'https://gridworks.readthedocs.io', 'https://github.com/thegridelectric', 'GridWorks Energy Consulting LLC', 'Transactive energy infrastructure and thermal storage systems', 'Community support via GitHub issues', 'MIT');

