#!/bin/bash
# ============================================================================
# demo - Database Initialization Script
# ============================================================================
# Generated by rulebook-to-postgres tool
# ============================================================================

set -e  # Exit on error

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# SQL Files in execution order
# Base files (XX-*) are generated by ERB tooling
# Customization files (XXb-*) are for user modifications and won't be overwritten
SQL_FILES=(
    "${SCRIPT_DIR}/00-bootstrap.sql"
    "${SCRIPT_DIR}/01-drop-and-create-tables.sql"
    "${SCRIPT_DIR}/01b-customize-schema.sql"
    "${SCRIPT_DIR}/02-create-functions.sql"
    "${SCRIPT_DIR}/02b-customize-functions.sql"
    "${SCRIPT_DIR}/03-create-views.sql"
    "${SCRIPT_DIR}/03b-customize-views.sql"
    "${SCRIPT_DIR}/04-create-policies.sql"
    "${SCRIPT_DIR}/04b-customize-policies.sql"
    "${SCRIPT_DIR}/05-insert-data.sql"
    "${SCRIPT_DIR}/05b-customize-data.sql"
)

# Default connection string
DEFAULT_CONN="postgresql://postgres@localhost:5432/sema"

# Get connection string from argument or use default
CONNECTION_STRING="${1:-$DEFAULT_CONN}"

echo "Initializing database: $CONNECTION_STRING"
echo ""

# Execute each SQL file
# Base files (XX-*) stop on error; customize files (XXb-*) log errors and continue.
for sql_file in "${SQL_FILES[@]}"; do
    if [[ ! -f "$sql_file" ]]; then continue; fi
    filename=$(basename "$sql_file")
    echo "Executing: $filename"
    if [[ "$filename" == *b-* ]]; then
        psql "$CONNECTION_STRING" -f "$sql_file"
    else
        psql "$CONNECTION_STRING" -f "$sql_file" -v ON_ERROR_STOP=1
    fi
    echo "✓ $filename completed"
    echo ""
done

# Execute function overrides - one file per function, errors are non-fatal.
# Two-pass: non-policy files first (functions, rls_state toggles, etc.), then
# policy__* files. Policies often reference custom functions, so the functions
# must exist before the policies are created.
run_override() {
    local sql_file="$1"
    local filename
    filename=$(basename "$sql_file")
    echo "Executing: function-overrides/$filename"
    psql "$CONNECTION_STRING" -f "$sql_file"
    echo "✓ function-overrides/$filename completed"
    echo ""
}

if compgen -G "${SCRIPT_DIR}/function-overrides/*.sql" > /dev/null 2>&1; then
    for sql_file in "${SCRIPT_DIR}/function-overrides/"*.sql; do
        filename=$(basename "$sql_file")
        [[ "$filename" == policy__* ]] && continue
        run_override "$sql_file"
    done
    for sql_file in "${SCRIPT_DIR}/function-overrides/"policy__*.sql; do
        [[ -f "$sql_file" ]] || continue
        run_override "$sql_file"
    done
fi

echo "Database initialization complete!"
